"""C1 modules 3–6 (dossiers 3–6) : 24 séquences."""


def D(**k):
    return k


REST2 = [
    # ----- C1-3 dossier 3 soin -----
    D(
        title="Dons et parcours",
        lang="passif ; reformulation d'un parcours ; vocabulaire du soin (inventé)",
        lang_type="rel_synthese",
        obj="Reformuler les difficultés d'un parcours à l'Infirmerie des Herbes sans jargon abandonnant.",
        theme="le parcours à l'Infirmerie des Herbes",
        slogan="il suffit d'attendre",
        promise="réduise l'attente à une vertu",
        obstacle="une porte trop longue à s'ouvrir pour Hawa",
        who="Hawa Diallo",
        concede="un don de temps peut aider l'infirmerie",
        cond="l'on n'appelle pas don le silence imposé au malade",
        implicit="il suffit d'attendre veut souvent dire votre douleur n'a pas de place dans l'emploi du temps",
        implicit_short="La douleur n'a pas de place dans l'emploi du temps",
        reform="le parcours n'est pas une ligne : c'est une série de portes, de mots, de peurs nommées",
        proposal="un podcast qui reformule le parcours d'Hawa sans voler sa voix",
        datum="Hawa a compté onze passages de porte, trois jargon incompréhensibles, une main de Dieudonné sur le banc.",
        datum_short="Onze portes, trois jargon, une main sur le banc",
        stake="il s'agit que le consentement soit clair, pas seulement signé trop vite",
        hearer="Inès Mukama",
        doc_a="les notes d'Hawa au Cahier des dons",
        doc_b="la fiche trop technique d'un passage inventé",
        ce_doc="La porte trop longue",
        w1="parcours", d1="suite de portes et de mots, plus qu'une attente",
        w2="consentement", d2="accord clair, pas une signature trop vite",
        w3="jargon", d3="langue qui abandonne le malade",
        w4="don", d4="geste, distinct du silence imposé",
        sv=("reformuler", "reformule"), nom="parcours", nom2="consentement",
        decoy1="Que Hawa refuse tout soin",
        decoy2="Que Inès a fermé l'infirmerie",
        decoy3="Que Dieudonné prescrit les infusions",
        beats="Hawa : on m'a dit d'attendre comme on dit merci. | Inès refuse le jargon qui abandonne : elle traduit, elle n'humilie pas. | Dieudonné répare la porte d'attente pour qu'elle grince moins. | Aline : le passif a été reçue trop tard n'est pas une excuse, c'est une phrase à relire. | Patrick demande ce dont on a besoin : une explication, pas un mot savant. | Solange apporte une infusion et sort : elle n'est pas le protocole. | Lila enregistrera le podcast si Hawa le veut, pas pour le spectacle. | Marc : reformuler un parcours, c'est rendre les portes visibles.",
    ),
    D(
        title="Le graphique n'efface pas la peur",
        lang="rapporter une enquête ; il apparaîtrait que ; modalisation",
        lang_type="stats",
        obj="Rapporter une enquête du Filtre et expliciter une découverte sans triomphalisme.",
        theme="une découverte du Filtre des Herbes",
        slogan="la science a parlé",
        promise="close la peur par un graphique",
        obstacle="une crainte qui n'est pas une ignorance",
        who="Inès Mukama",
        concede="un résultat peut rassurer",
        cond="l'on dise aussi ce que l'enquête n'a pas vu",
        implicit="la science a parlé sert parfois à ne plus écouter ceux qui ont peur pour de vraies raisons",
        implicit_short="Ne plus écouter une peur fondée",
        reform="il apparaîtrait que le filtre réduit un risque : ce conditionnel de prudence n'est pas une faiblesse",
        proposal="une mini-conférence : résultat, limite, crainte légitime, geste de cour",
        datum="Le Filtre avance : risque moindre dans un échantillon inventé de quarante bols ; deux craintes non mesurées restent sur le banc.",
        datum_short="Quarante bols, risque moindre, deux craintes hors graphique",
        stake="il s'agit de nommer le progrès sans chasser la crainte comme une honte",
        hearer="Hawa Diallo",
        doc_a="le rapport du Filtre",
        doc_b="la conférence d'Inès sous le figuier",
        ce_doc="Le graphique n'efface pas la peur",
        w1="enquête", d1="recherche datée, avec limites",
        w2="découverte", d2="résultat, pas un triomphe",
        w3="crainte", d3="peur fondée, distincte de l'ignorance",
        w4="échantillon", d4="portion observée, pas tout le Seuil",
        sv=("rapporter", "rapporte"), nom="enquête", nom2="découverte",
        decoy1="Que le Filtre a tout mesuré",
        decoy2="Que Hawa refuse les graphiques",
        decoy3="Que Inès promet l'immortalité",
        beats="Inès : il apparaîtrait que le risque baisse, et j'entends déjà ceux qui veulent que je cesse le conditionnel. | Hawa : ma crainte n'est pas une erreur de calcul. | Karim exige la taille de l'échantillon, pas le mot miracle. | Aline : modaliser, c'est rester honnête. | Patrick veut une mini-conférence, pas une messe. | Solange demande ce que l'on fera des deux craintes hors graphique. | Lila notera le conditionnel à l'antenne, exprès. | Marc : expliciter une découverte, c'est aussi dire où elle s'arrête.",
    ),
    D(
        title="Une vie de formation",
        lang="journal intime ; imparfait / plus-que-parfait ; modalisation du doute",
        lang_type="compte_rendu",
        obj="Raconter les difficultés d'une formation trop longue sans pathos de sacrifice.",
        theme="une formation trop longue au Seuil",
        slogan="c'est le prix à payer",
        promise="transforme l'épuisement en vertu",
        obstacle="des gardes qui volent les heures d'écriture d'Aline",
        who="Aline Uwase",
        concede="apprendre longtemps peut être juste",
        cond="l'on n'appelle pas vocation ce qui use sans transmettre",
        implicit="c'est le prix à payer interdit souvent de demander qui encaisse",
        implicit_short="Interdiction de demander qui encaisse",
        reform="le journal n'est pas une plainte : c'est une archive de ce que la blouse cache",
        proposal="trois pages de journal : faits, doute, ce qui reste transmissible",
        datum="Aline a noté vingt gardes, quatre cours manqués, une élève qui attend encore la fiche.",
        datum_short="Vingt gardes, quatre cours manqués, une élève en attente",
        stake="il s'agit que la transmission ne meure pas sous le mot sacrifice",
        hearer="Patrick Habimana",
        doc_a="le journal d'Aline",
        doc_b="l'émission où l'on parle trop vite de vocation",
        ce_doc="Ce que la blouse cache",
        w1="formation", d1="temps d'apprendre, pas une épreuve sacrée",
        w2="journal", d2="écriture datée, archive du doute",
        w3="garde", d3="heure prise sur le sommeil et la transmission",
        w4="vocation", d4="mot trop large, parfois une excuse",
        sv=("écrire", "écrive"), nom="formation", nom2="journal",
        decoy1="Que Aline quitte le Seuil demain",
        decoy2="Que Patrick interdit les journaux",
        decoy3="Que les gardes sont une fête",
        beats="Aline : j'avais cru que former, c'était parler ; j'ai appris que c'était d'abord ne pas disparaître. | Patrick lit le journal sans corriger l'émotion, seulement la syntaxe. | Inès reconnaît les gardes : elle les a faites, elle refuse d'en faire une légende. | Hawa dit qu'une élève n'a pas à payer le sommeil de la formatrice. | Lila n'enregistrera le journal que si Aline le veut. | Dieudonné apporte du thé à l'aube, sans discours. | Yvette : un métier difficile n'est pas une religion. | Marc : selon le journal, il ressort que la transmission exige des heures, pas un martyre.",
    ),
    D(
        title="L'herbe et la porte",
        lang="présenter une polémique ; certains affirment / d'autres objectent",
        lang_type="cause",
        obj="Présenter une polémique sur les infusions de Solange sans caricature.",
        theme="les infusions de Solange Mukamana",
        slogan="c'est naturel donc c'est sûr",
        promise="remplace l'infirmerie par une casserole",
        obstacle="une confiance trop simple dans l'herbe",
        who="Solange Mukamana",
        concede="une infusion peut apaiser",
        cond="l'on n'y voie pas un remplacement du consentement et du suivi",
        implicit="naturel donc sûr permet de vendre une calme ignorance",
        implicit_short="Vendre une calme ignorance",
        reform="la polémique n'est pas Solange contre Inès : c'est le mot sûr collé trop vite à l'herbe",
        proposal="présenter deux positions, une limite, un geste : l'herbe n'efface pas la porte d'Inès",
        datum="Solange a servi douze infusions ; Inès a reçu trois personnes trop tard, persuadées que l'herbe suffisait.",
        datum_short="Douze infusions, trois arrivées trop tard",
        stake="il s'agit de soigner sans magie, ni mépris de l'herbe, ni abandon du suivi",
        hearer="Inès Mukama",
        doc_a="la chronique de Solange",
        doc_b="la mise au point d'Inès",
        ce_doc="L'herbe n'est pas un sort",
        w1="polémique", d1="désaccord public à présenter, non à envenimer",
        w2="infusion", d2="préparation d'herbe, parfois un apaisement",
        w3="suivi", d3="continuité du soin, plus qu'un bol chaud",
        w4="limite", d4="ligne où l'herbe ne remplace pas la porte",
        sv=("présenter", "présente"), nom="polémique", nom2="infusion",
        decoy1="Que Solange interdit l'infirmerie",
        decoy2="Que Inès brûle les herbes",
        decoy3="Que le figuier guérit tout",
        beats="Solange : certains affirment que l'herbe suffit ; je n'ai jamais dit cela, j'ai dit qu'elle console. | Inès : d'autres objectent que console veut dire guérir, et c'est là que les portes s'ouvrent trop tard. | Aline exige les deux voix dans le même exposé. | Hawa a goûté l'infusion et gardé son rendez-vous. | Karim refuse le donc trop rapide : naturel donc sûr. | Lila présentera la polémique sans chercher une gagnante. | Dieudonné : une casserole n'est pas une infamie, c'est un outil. | Marc : expliquer le fonctionnement d'une thérapie, c'est aussi dire où elle s'arrête.",
    ),
    D(
        title="Mini-conférence du Filtre",
        lang="plan déductif ; il s'ensuit que ; en conséquence",
        lang_type="reco",
        obj="Tenir une mini-conférence claire : résultat, limite, geste.",
        theme="la mini-conférence sous le figuier",
        slogan="faites confiance",
        promise="remplace le plan par le charisme",
        obstacle="une salle qui applaudit trop tôt",
        who="Inès Mukama",
        concede="un oral peut emporter l'adhésion",
        cond="l'on ait d'abord posé les limites de l'échantillon",
        implicit="faites confiance veut souvent dire ne demandez pas le plan",
        implicit_short="Ne pas demander le plan",
        reform="déduire, ce n'est pas enchaîner des mots savants : c'est montrer ce qui s'ensuit, et ce qui ne s'ensuit pas",
        proposal="un plan en trois temps : fait, limite, recommandation pour la cour",
        datum="Inès a parlé onze minutes ; trois questions ; zéro mot miracle.",
        datum_short="Onze minutes, trois questions, zéro miracle",
        stake="il s'agit que la cour puisse relire la conférence demain sans se sentir trompée",
        hearer="Aline Uwase",
        doc_a="le plan d'Inès",
        doc_b="les questions d'Hawa et de Karim",
        ce_doc="Ce qui s'ensuit, ce qui ne s'ensuit pas",
        w1="conférence", d1="oral structuré, distinct d'un spectacle",
        w2="déduction", d2="enchaînement justifié, pas un saut",
        w3="limite", d3="bord de ce que l'on peut dire",
        w4="recommandation", d4="geste proposé après le fait",
        sv=("conclure", "conclue"), nom="conférence", nom2="déduction",
        decoy1="Que Inès a parlé une heure sans questions",
        decoy2="Que Aline a interdit les limites",
        decoy3="Que le Filtre est une magie",
        beats="Inès pose le fait, puis la limite, puis le geste : la salle voudrait inverser. | Aline : il convient que l'on entende le donc avant l'applaudissement. | Karim demande ce qui ne s'ensuit pas. | Hawa pose la question que le graphique évite. | Patrick chronomètre sans brutalité. | Lila gardera les trois questions, pas seulement la formule claire. | Solange apporte de l'eau, pas une conclusion. | Marc : une mini-conférence est une hospitalité faite au doute.",
    ),
    D(
        title="Podcast du parcours",
        lang="discours rapporté complexe ; elle a dit qu'elle / si",
        lang_type="disc_ind",
        obj="Enregistrer un podcast qui rapporte un parcours médical inventé sans le voler.",
        theme="le podcast de Radio Figuier sur le parcours",
        slogan="donner la voix aux patients",
        promise="coupe la parole d'Hawa pour faire plus vrai",
        obstacle="un montage trop lisse",
        who="Lila Sow",
        concede="monter peut clarifier",
        cond="l'on n'efface pas les silences qu'Hawa a choisis",
        implicit="donner la voix peut cacher le fait qu'on la prend",
        implicit_short="Prendre la voix en prétendant la donner",
        reform="rapporter, ce n'est pas sténographier, et ce n'est pas non plus embellir la peur",
        proposal="un épisode : Hawa, Inès, un silence gardé, une reformulation signalée",
        datum="Lila a gardé quatre silences ; coupé deux répétitions ; refusé un fond musical trop doux.",
        datum_short="Quatre silences gardés, deux coupures, zéro musique trop douce",
        stake="il s'agit que le podcast reste un soin de parole, pas un spectacle de douleur",
        hearer="Hawa Diallo",
        doc_a="le rush du podcast",
        doc_b="les consignes d'Hawa sur ce qui ne se dit pas",
        ce_doc="Ce qui ne se monte pas",
        w1="podcast", d1="épisode parlé, monté avec éthique",
        w2="montage", d2="choix de garder ou couper, jamais anodin",
        w3="silence", d3="partie du récit, pas un trou à remplir",
        w4="voix", d4="parole d'Hawa, non un objet de radio",
        sv=("couper", "coupe"), nom="podcast", nom2="montage",
        decoy1="Que Lila a vendu l'épisode aux Lampions",
        decoy2="Que Hawa a tout interdit",
        decoy3="Que Inès a parlé à la place d'Hawa",
        beats="Hawa a dit qu'elle voulait le silence après le mot porte. | Lila a demandé si l'on pouvait reformuler jargon ; Hawa a dit que oui, à condition de le signaler. | Inès a prétendu que le protocole était clair ; Hawa a ri, puis s'est tue. | Aline : le discours indirect ici protège, il n'habille pas. | Dieudonné n'apparaît que s'il accepte. | Patrick écoute le rush et refuse le fond musical. | Yvette : donner la voix n'est pas une décoration. | Marc : Radio Figuier rapportera, elle n'éditera pas la peur.",
    ),
    # ----- C1-4 dossier 4 corps -----
    D(
        title="Image de soi sous le figuier",
        lang="commenter une tendance ; on dirait que ; registre du regard",
        lang_type="registre",
        obj="Commenter une tendance du regard sans répéter les mots d'un fil.",
        theme="le regard que la cour porte sur les corps",
        slogan="sois toi-même",
        promise="transforme le corps en vitrine du fil",
        obstacle="un compliment qui mesure trop",
        who="Léa Niyonzima",
        concede="un portrait peut réjouir",
        cond="l'on n'y lise pas une note de conformité",
        implicit="sois toi-même arrive souvent après une liste de ce que toi-même devrait être",
        implicit_short="Une liste déguisée en liberté",
        reform="commenter une tendance, c'est nommer qui gagne à ce que l'on se compare",
        proposal="un billet pour le Cahier du chemin : tendance, implicite, geste de ne pas mesurer",
        datum="Léa a vu six portraits trop semblables au fil inventé de la cour, un seul où l'ombre n'était pas gommée.",
        datum_short="Six portraits trop semblables, une ombre gardée",
        stake="il s'agit de se voir sans se mettre en vitrine",
        hearer="Rose Iradukunda",
        doc_a="les portraits trop nets du fil de la cour",
        doc_b="le billet de Léa",
        ce_doc="Toi-même, après la liste",
        w1="regard", d1="manière de voir, parfois une mesure",
        w2="portrait", d2="image, trop souvent une note",
        w3="tendance", d3="mode du regard, à commenter",
        w4="vitrine", d4="exposition, distincte d'une présence",
        sv=("commenter", "commente"), nom="regard", nom2="portrait",
        decoy1="Que Léa interdit les portraits",
        decoy2="Que Rose ne coud plus",
        decoy3="Que le figuier mesure les visages",
        beats="Léa : on dirait que le fil n'aime que les midis sans ombre. | Rose coud un col trop large, exprès, pour que le corps respire. | Sami pose un portrait et le retire : trop de commentaires. | Aline distingue le registre du banc et celui du fil. | Hawa refuse le compliment qui pèse. | Joël ne se photographie pas portant les lanternes : ce n'est pas un spectacle. | Lila n'ouvrira pas une émission de notes. | Marc : commenter, ce n'est pas noter.",
    ),
    D(
        title="La planche n'est pas une rampe",
        lang="dénoncer une inégalité ; relatives complexes ; il n'est que trop",
        lang_type="cause",
        obj="Dénoncer ce que la cour rend invisible, notamment l'accès.",
        theme="ce que la cour ne voit pas",
        slogan="on s'adapte",
        promise="mette la rampe à plus tard",
        obstacle="une assemblée sans place pour Joël le jour de la pluie",
        who="Joël Mugisha",
        concede="la cour a déjà posé une planche",
        cond="l'on n'appelle pas planche une rampe, ni patience une justice",
        implicit="on s'adapte veut dire c'est à toi de disparaître quand il pleut",
        implicit_short="Disparaître quand il pleut",
        reform="dénoncer, ce n'est pas insulter : c'est rendre visible une inégalité que l'habitude a rendue normale",
        proposal="un manifeste : rampe, heures, bancs, signatures du Bureau des Escales",
        datum="Joël a manqué trois assemblées de pluie ; la planche a glissé huit fois ; zéro date de rampe.",
        datum_short="Trois assemblées manquées, huit glissades, zéro date",
        stake="il s'agit que la cour soit une cour, pas un club de ceux qui montent vite",
        hearer="Solange Mukamana",
        doc_a="le manifeste de Joël et de Léa",
        doc_b="les minutes trop vagues de l'assemblée",
        ce_doc="La planche n'est pas une rampe",
        w1="inégalité", d1="écart d'accès rendu normal par l'habitude",
        w2="rampe", d2="accès réel, distinct d'une planche",
        w3="manifeste", d3="texte qui dénonce et exige",
        w4="accès", d4="possibilité d'entrer, pas une faveur",
        sv=("dénoncer", "dénonce"), nom="inégalité", nom2="rampe",
        decoy1="Que Joël refuse toute assemblée",
        decoy2="Que Solange a volé la planche",
        decoy3="Que la pluie est une excuse de Marc",
        beats="Joël : il n'est que trop évident que la pluie choisit qui parle. | Solange a honte de la planche, et la honte n'est pas une rampe. | Léa écrit le manifeste au nom de ceux qui n'ont pas pu monter. | Dieudonné peut souder, il demande une date. | Karim chiffre le fer, refuse le mot bientôt. | Aline : la relative dont on se passe trop souvent, c'est ceux pour qui la cour se ferme. | Lila lira le manifeste sans musique héroïque. | Marc : dénoncer une inégalité, c'est rendre le banc habitable.",
    ),
    D(
        title="Les épaules ne sont pas un verdict",
        lang="idiomes corporels ; ne pas les calquer ; interpréter un geste",
        lang_type="registre",
        obj="Interpréter la gestuelle de la cour et des idiomes, sans les prendre pour des preuves.",
        theme="les gestes sous le figuier",
        slogan="le corps ne ment pas",
        promise="fasse d'un haussement d'épaules un verdict",
        obstacle="une lecture trop sûre des mains de Rose",
        who="Sami",
        concede="un geste peut dire ce que la bouche retient",
        cond="l'on n'y lise pas un tribunal",
        implicit="le corps ne ment pas est souvent une excuse pour ne plus écouter les mots",
        implicit_short="Cesser d'écouter les mots",
        reform="un idiome (avoir les bras cassés, tourner les talons) décrit une relation, pas une anatomie",
        proposal="interpréter trois gestes filmés par Léa, puis laisser à Rose le dernier mot",
        datum="Léa a noté cinq épaules trop vite lues, deux silences, un tambour de Sami qui n'était pas une colère.",
        datum_short="Cinq épaules trop lues, un tambour qui n'était pas une colère",
        stake="il s'agit de lire le corps comme un texte, avec des hypothèses, pas des sentences",
        hearer="Rose Iradukunda",
        doc_a="les notes de Léa sur les gestes",
        doc_b="le slam inventé de Sami",
        ce_doc="Les épaules ne sont pas un verdict",
        w1="geste", d1="mouvement à interpréter, non à juger trop vite",
        w2="idiome", d2="expression figée, souvent corporelle",
        w3="épaule", d3="signe possible de doute, pas une preuve",
        w4="slam", d4="parole rythmée de Sami, inventée",
        sv=("interpréter", "interprète"), nom="geste", nom2="idiome",
        decoy1="Que Rose a avoué par les mains",
        decoy2="Que Sami accuse Léa",
        decoy3="Que le tambour est interdit",
        beats="Sami : j'ai les mots dans les mains, et ce n'est pas une preuve contre Rose. | Rose tourne les talons pour coudre, non pour fuir un procès. | Aline explique avoir les bras cassés : fatigue, pas anatomie. | Léa filme trop près ; Patrick lui demande de reculer. | Hawa dit qu'un silence n'est pas un aveu. | Joël porte les lanternes : ses épaules parlent de fer, pas de honte. | Lila : interpréter, c'est proposer, c'est laisser corriger. | Marc : le corps ne ment pas est un slogan trop sûr pour une cour.",
    ),
    D(
        title="Le lin tient le geste",
        lang="décrire une œuvre ; présent de reportage ; métaphore contrôlée",
        lang_type="hypotypose",
        obj="Analyser une œuvre inventée de Rose pour un audioguide.",
        theme="l'œuvre de Rose à la Salle des Herbes",
        slogan="c'est beau point",
        promise="remplace l'analyse par l'admiration muette",
        obstacle="une toile dont on ne dit que le prix",
        who="Rose Iradukunda",
        concede="l'admiration a sa place",
        cond="l'on dise aussi comment le lin tient le geste",
        implicit="c'est beau point permet de ne pas voir le corps trop réel que Rose a cousu",
        implicit_short="Ne pas voir le corps trop réel",
        reform="décrire, c'est choisir un angle : couture, ombre, regard, pas un mot magique",
        proposal="un audioguide de trois minutes : matériaux, geste, hypothèse, silence",
        datum="Rose a cousu onze pièces d'ocre ; Léa a écrit trois hypothèses ; zéro prix annoncé au banc.",
        datum_short="Onze pièces d'ocre, trois hypothèses, zéro prix au banc",
        stake="il s'agit d'interpréter sans posséder l'œuvre par le jargon",
        hearer="Léa Niyonzima",
        doc_a="l'œuvre de Rose",
        doc_b="le brouillon d'audioguide de Léa",
        ce_doc="Le lin tient le geste",
        w1="œuvre", d1="travail de Rose, à décrire sans le posséder",
        w2="audioguide", d2="parole de visite, courte et honnête",
        w3="lin", d3="matériau ocre, plus parlant qu'un prix",
        w4="hypothèse", d4="lecture proposée, corrigeable",
        sv=("décrire", "décrive"), nom="œuvre", nom2="audioguide",
        decoy1="Que Rose a vendu l'œuvre aux Lampions",
        decoy2="Que Léa a cousu à sa place",
        decoy3="Que le lin est un slogan",
        beats="On dirait que le lin marcherait si l'on cessait de le clouer du regard. | Rose : je n'ai pas animé un corps, j'ai donné une ombre à une couture. | Léa choisit le présent : la pièce avance, l'ocre retient. | Aline refuse le jargon d'école trop loin du fil. | Sami veut frapper le tambour trop près ; Rose dit non. | Patrick décrit les onze pièces sans les compter comme un exploit. | Lila enregistrera l'audioguide dans la salle vide, d'abord. | Marc : analyser une œuvre, c'est proposer, c'est se taire à temps.",
    ),
    D(
        title="Manifeste de la rampe",
        lang="injonction vs subjonctif de volonté ; nous exigeons que",
        lang_type="reco",
        obj="Écrire un manifeste qui exige sans insulter, et qui nomme des gestes.",
        theme="le manifeste pour la rampe",
        slogan="assez",
        promise="réduise le manifeste à un cri",
        obstacle="un assez sans destinataire ni date",
        who="Joël Mugisha",
        concede="un cri ouvre parfois l'oreille",
        cond="l'on écrive ensuite qui, quand, quoi",
        implicit="assez tout seul laisse à la cour le loisir de n'avoir rien entendu",
        implicit_short="N'avoir rien entendu",
        reform="nous exigeons que la rampe soit datée : le subjonctif ici est une volonté, pas une décoration",
        proposal="un manifeste signé : rampe, bancs, pluie, fer, jeudi",
        datum="Vingt-deux signatures ; une date proposée ; zéro insulte dans le texte retenu.",
        datum_short="Vingt-deux signatures, une date, zéro insulte",
        stake="il s'agit que le manifeste puisse se relire sans honte quand la rampe sera là",
        hearer="Karim Bamba",
        doc_a="le manifeste",
        doc_b="les ratures de Solange et d'Aline",
        ce_doc="Assez, puis la date",
        w1="manifeste", d1="texte d'exigence argumentée",
        w2="exigence", d2="volonté nommée, avec subjonctif",
        w3="signature", d3="nom posé, pas un like",
        w4="date", d4="jour du fer, plus précis qu'assez",
        sv=("exiger", "exige"), nom="manifeste", nom2="exigence",
        decoy1="Que Joël a insulté l'assemblée",
        decoy2="Que Karim a refusé toute date",
        decoy3="Que Solange a caché les signatures",
        beats="Joël : nous exigeons que la rampe soit posée avant les pluies, non après les excuses. | Il convient que l'on nomme Dieudonné et le fer. | Solange rature les insultes, garde la colère. | Aline corrige le subjonctif, pas le fond. | Léa ajoute les bancs. | Lila lira le manifeste à l'antenne, lentement. | Yvette signe ; Sami aussi, sans grimace. | Marc : une injonction sans date est un assez qui s'évapore.",
    ),
    D(
        title="Audioguide de Rose",
        lang="deuxième personne de guide ; hypotaxe ; hypothèse signalée",
        lang_type="hypotypose",
        obj="Enregistrer un audioguide qui guide sans posséder l'œuvre.",
        theme="l'audioguide de la Salle des Herbes",
        slogan="vous allez aimer",
        promise="force l'admiration",
        obstacle="un vous trop sûr de ce que l'œil doit sentir",
        who="Léa Niyonzima",
        concede="guider peut aider à voir",
        cond="l'on laisse à l'auditeur le droit de ne pas aimer",
        implicit="vous allez aimer est déjà une petite violence polie",
        implicit_short="Une violence polie",
        reform="vous pouvez voir, on dirait que, il se peut que : le guide propose, il n'assigne pas",
        proposal="trois minutes : matériaux, une hypothèse, un silence, une sortie",
        datum="Léa a chronométré 2 min 50 ; un silence de huit secondes ; zéro vous allez aimer.",
        datum_short="Deux minutes cinquante, un silence, zéro injonction d'aimer",
        stake="il s'agit d'accompagner le regard, pas de le remplacer",
        hearer="Rose Iradukunda",
        doc_a="le script d'audioguide",
        doc_b="les remarques de Rose",
        ce_doc="Vous pouvez voir",
        w1="guide", d1="voix qui propose un regard",
        w2="auditeur", d2="personne libre de ne pas aimer",
        w3="silence", d3="temps laissé à l'œil",
        w4="script", d4="texte lu, raturé avec Rose",
        sv=("guider", "guide"), nom="guide", nom2="auditeur",
        decoy1="Que Léa force l'admiration",
        decoy2="Que Rose a interdit l'écoute",
        decoy3="Que le silence est une panne",
        beats="Léa : vous pouvez vous tenir à gauche, là où le lin prend l'ombre. | On dirait qu'une couture avance ; il se peut que ce soit seulement votre pas. | Rose a demandé que l'on coupe vous allez aimer. | Aline : la deuxième personne n'est pas un ordre. | Sami chuchote trop près du micro ; Lila recule. | Patrick aime le silence de huit secondes. | Joël écoutera assis, si le banc est là. | Marc : un audioguide est une hospitalité, pas une leçon de goût.",
    ),
    # ----- C1-5 dossier 5 monde / chant / accueil / âges -----
    D(
        title="Chant de la cour",
        lang="expliquer un implicite ; métaphore ; message d'un chant inventé",
        lang_type="registre",
        obj="Expliquer le message d'un chant de cour inventé, y compris ce qu'il ne dit pas.",
        theme="le chant inventé de la cour",
        slogan="c'est juste une chanson",
        promise="réduise le chant à un air",
        obstacle="un refrain trop clair pour n'être pas une porte fermée",
        who="Sami",
        concede="on peut aimer l'air sans tout décoder",
        cond="l'on n'interdise pas à ceux qui habitent le refrain de l'expliquer",
        implicit="c'est juste une chanson permet de ne pas entendre qui reste derrière la colline",
        implicit_short="Ne pas entendre qui reste derrière la colline",
        reform="un chant engagé n'a pas besoin de slogan : l'implicite fait le travail, encore faut-il le lire",
        proposal="expliquer le message : qui parle, qui n'est pas nommé, quel geste le refrain demande",
        datum="Sami a changé un mot ; Lila a reçu trois lectures opposées ; zéro clip trop lisse retenu.",
        datum_short="Un mot changé, trois lectures, zéro clip trop lisse",
        stake="il s'agit d'entendre le chant comme une parole de cour, pas comme un décor",
        hearer="Solange Mukamana",
        doc_a="les paroles inventées de Sami",
        doc_b="l'article de Mado sur le refrain",
        ce_doc="Le refrain n'est pas un décor",
        w1="refrain", d1="retour d'un chant, parfois une porte",
        w2="implicite", d2="non-dit qui travaille le message",
        w3="métaphore", d3="image qui dit autrement",
        w4="message", d4="ce que le chant fait, au-delà de l'air",
        sv=("expliquer", "explique"), nom="refrain", nom2="implicite",
        decoy1="Que Sami a copié une affiche",
        decoy2="Que Solange interdit le chant",
        decoy3="Que le refrain nomme tous les noms",
        beats="Sami : le refrain dit colline, et l'on entend trop vite panorama. | Solange entend une porte. | Mado écrit que la métaphore n'est pas un ornement. | Aline : expliquer un chant, c'est risquer d'être trop clair, et il le faut parfois. | Léa refuse le mot verlan collé pour faire vrai. | Lila jouera l'air, puis le silence. | Yvette : c'est juste une chanson est déjà une politique. | Marc : le message, c'est aussi qui n'a pas le micro.",
    ),
    D(
        title="Biographie engagée",
        lang="plus-que-parfait ; il fut un temps ; résumé d'un discours",
        lang_type="compte_rendu",
        obj="Résumer un discours et écrire la biographie d'une voix engagée de la cour.",
        theme="la biographie de Solange Mukamana",
        slogan="une femme exceptionnelle",
        promise="transforme Solange en statue",
        obstacle="une nécrologie trop douce de son vivant",
        who="Mado",
        concede="honorer peut être juste",
        cond="l'on raconte les portes, pas seulement les couronnes",
        implicit="exceptionnelle permet de ne pas rendre ordinaires les droits qu'elle a exigés",
        implicit_short="Ne pas rendre ordinaires les droits exigés",
        reform="une biographie engagée relie les faits aux luttes, sans hagiographie",
        proposal="deux pages : dates, discours, ce qu'elle a refusé qu'on dise d'elle",
        datum="Solange a ouvert quatre portes ; Mado a raturé six adjectifs trop grands ; un discours lu deux fois.",
        datum_short="Quatre portes, six adjectifs raturés, un discours relu",
        stake="il s'agit d'écrire une vie qui reste une vie, pas un exemple impossible",
        hearer="Solange Mukamana",
        doc_a="le discours de Solange sous le figuier",
        doc_b="la biographie raturée de Mado",
        ce_doc="Pas une statue",
        w1="biographie", d1="récit d'une vie, sans statue",
        w2="discours", d2="parole publique à résumer",
        w3="lutte", d3="geste répété, plus qu'un adjectif",
        w4="hagiographie", d4="vie trop sainte pour rester vraie",
        sv=("raconter", "raconte"), nom="biographie", nom2="discours",
        decoy1="Que Solange a demandé une statue",
        decoy2="Que Mado a inventé les portes",
        decoy3="Que le discours n'a jamais eu lieu",
        beats="Il fut un temps où Solange parlait trop tôt pour trop de portes. | Elle avait déjà exigé la rampe quand on la disait trop pressée. | Mado résume le discours sans le sucrer. | Aline : le plus-que-parfait dit l'antériorité d'une lutte, pas le mythe. | Patrick refuse exceptionnelle : trop commode. | Lila lira la bio si Solange la signe. | Yvette se reconnaît dans une porte, pas dans une couronne. | Marc : selon le discours, il ressort que l'honneur véritable, c'est la date d'une rampe.",
    ),
    D(
        title="Le sourire n'est pas un lit",
        lang="humour et sous-entendu ; écrire un poème ; chronique",
        lang_type="ironie",
        obj="Comprendre une chronique d'accueil et écrire un poème sans slogan.",
        theme="l'accueil à Rukiri-Nord",
        slogan="nous sommes hospitaliers",
        promise="tienne lieu de lit et de papiers",
        obstacle="un sourire trop large à la porte du Pavillon",
        who="Hawa Diallo",
        concede="un mot doux peut ouvrir",
        cond="l'on pose ensuite un lit, une clé, une heure",
        implicit="nous sommes hospitaliers se dit trop souvent à ceux à qui l'on n'a rien donné",
        implicit_short="Rien donné, mot doux offert",
        reform="le poème peut dire l'accueil mieux qu'une affiche, s'il nomme la clé",
        proposal="une chronique d'humour sans mépris, puis un poème qui tient dans la poche",
        datum="Hawa a reçu trois valises ; deux clés ; un sourire sans banc. Mado en a fait huit vers.",
        datum_short="Trois valises, deux clés, un sourire sans banc",
        stake="il s'agit d'accueillir des personnes, pas d'illustrer une vertu",
        hearer="Dieudonné Hakizimana",
        doc_a="la chronique de Mado",
        doc_b="le poème d'Hawa",
        ce_doc="Le sourire n'est pas un lit",
        w1="accueil", d1="geste concret, distinct d'un mot",
        w2="chronique", d2="texte court, parfois humoristique",
        w3="poème", d3="forme brève qui peut nommer la clé",
        w4="hospitalité", d4="pratique, pas une affiche",
        sv=("accueillir", "accueille"), nom="accueil", nom2="chronique",
        decoy1="Que Hawa a fermé le Pavillon",
        decoy2="Que Mado se moque des valises",
        decoy3="Que Dieudonné refuse les clés",
        beats="Hawa : il ne s'agirait que d'un détail, le lit, à entendre certains sourires. | Loin de rassurer, le mot hospitaliers fatigue quand la clé manque. | Mado écrit une chronique où le sourire trébuche, sans écraser personne. | Aline : l'humour ici n'est pas une arme contre ceux qui arrivent. | Patrick pose un banc. | Rose coud un ourlet trop large pour une valise trop pleine. | Lila lira le poème lentement. | Marc : une terre d'accueil se mesure aux clés, pas aux phrases.",
    ),
    D(
        title="Deux vitesses une cour",
        lang="registres selon l'interlocuteur ; tutoiement / vouvoiement ; alors que",
        lang_type="registre",
        obj="Comparer deux générations et adapter le registre sans mépris.",
        theme="deux âges sous le figuier",
        slogan="de mon temps",
        promise="ferme l'oreille aux plus jeunes ou aux plus vieux",
        obstacle="un sketch trop sûr de ses cibles",
        who="Yvette",
        concede="les habitudes changent",
        cond="l'on n'en fasse pas une guerre de bancs",
        implicit="de mon temps veut souvent dire le vôtre ne compte pas",
        implicit_short="Votre temps ne compte pas",
        reform="comparer des âges, c'est croiser des registres, pas couronner une génération",
        proposal="un dialogue : Yvette et Sami, deux registres, une cour commune",
        datum="Yvette vouvoie Lila au micro ; tutole Sami au banc ; Sami inverse parfois, et l'on en parle.",
        datum_short="Vouvoiement au micro, tutoiement au banc, un écart discuté",
        stake="il s'agit que la cour tienne deux vitesses de parole sans humiliation",
        hearer="Sami",
        doc_a="le portrait d'Yvette par Mado",
        doc_b="le sketch trop dur de Sami, raturé",
        ce_doc="Deux vitesses, une cour",
        w1="génération", d1="âge d'une parole, pas une armée",
        w2="registre", d2="niveau de langue choisi",
        w3="tutoiement", d3="proximité, pas un droit automatique",
        w4="vouvoiement", d4="distance parfois respectueuse au micro",
        sv=("adapter", "adapte"), nom="génération", nom2="registre",
        decoy1="Que Yvette interdit Sami",
        decoy2="Que Sami a humilié Yvette à l'antenne",
        decoy3="Que Lila refuse les deux registres",
        beats="Yvette : de mon temps, on disait cela, et ce n'était pas toujours mieux. | Sami tutole trop vite le micro ; Aline lui rappelle l'oreille de l'assemblée. | Alors que les lanternes pèsent pareil, les récits d'effort divergent. | Patrick refuse le sketch qui écrase. | Mado rature trois vannes. | Lila vouvoie, puis explique pourquoi. | Joël se tait : le fer n'a pas d'âge, dit-il. | Marc : adapter le registre, c'est respecter l'oreille, pas trahir.",
    ),
    D(
        title="Poème et chronique",
        lang="croiser deux genres ; implicite ; humour sans mépris",
        lang_type="ironie",
        obj="Croiser un poème et une chronique pour dire le monde de la cour.",
        theme="le cahier des combats",
        slogan="il faut choisir un genre",
        promise="sépare trop net la gravité et le rire",
        obstacle="une cour qui n'aurait droit qu'à un seul ton",
        who="Mado",
        concede="un genre aide à tenir une forme",
        cond="l'on puisse passer de l'un à l'autre sans trahir le sujet",
        implicit="choisir un genre veut parfois dire ne sois pas trop vivant",
        implicit_short="Ne sois pas trop vivant",
        reform="la chronique peut porter un vers, le poème une date : le Seuil n'est pas une anthologie trop sage",
        proposal="un diptyque : huit vers, une chronique, un même non-dit",
        datum="Mado a publié les deux le même jeudi ; Lila a lu l'un, puis l'autre ; trois auditeurs ont entendu le même implicite.",
        datum_short="Un jeudi, deux formes, un même implicite",
        stake="il s'agit de garder plusieurs langues pour un même monde",
        hearer="Lila Sow",
        doc_a="le poème de Mado",
        doc_b="sa chronique du même jeudi",
        ce_doc="Deux formes, un non-dit",
        w1="diptyque", d1="deux volets d'un même propos",
        w2="vers", d2="unité du poème",
        w3="ton", d3="couleur de la voix, pas une cage",
        w4="non-dit", d4="charge que les deux textes partagent",
        sv=("croiser", "croise"), nom="diptyque", nom2="vers",
        decoy1="Que Mado a volé le chant de Sami",
        decoy2="Que Lila n'a lu qu'un genre",
        decoy3="Que le jeudi interdit les vers",
        beats="Mado : loin de s'opposer, le vers et la chronique se prêtent la date. | Il ne s'agirait que d'un détail, le genre, à entendre ceux qui ont peur du mélange. | Sami pose un rythme entre les deux. | Aline accepte le mélange si l'implicite tient. | Solange se reconnaît dans la chronique, Léa dans le vers. | Patrick a peur du désordre ; il relit, il cède. | Lila : deux lectures, une oreille. | Marc : le monde de la cour n'a pas un seul ton, et c'est tant mieux.",
    ),
    D(
        title="Comparaison de générations",
        lang="alors que / tandis que / à mesure que ; synthèse",
        lang_type="compte_rendu",
        obj="Comparer deux modes de vie d'âges différents sans couronner l'un des deux.",
        theme="la comparaison Yvette / Sami",
        slogan="c'était mieux avant",
        promise="gagne le débat par la nostalgie",
        obstacle="une synthèse qui n'est qu'un vainqueur",
        who="Patrick Habimana",
        concede="certaines heures calmes d'autrefois manquent",
        cond="l'on dise aussi ce que les heures calmes cachaient",
        implicit="c'était mieux avant efface trop souvent qui n'avait pas la parole",
        implicit_short="Qui n'avait pas la parole",
        reform="à mesure que la cour change, comparer n'est pas classer",
        proposal="une synthèse : deux emplois du temps, deux peurs, un banc commun",
        datum="Patrick a dressé deux colonnes ; six points communs ; zéro vainqueur.",
        datum_short="Deux colonnes, six communs, zéro vainqueur",
        stake="il s'agit que la comparaison serve la cour, pas une hiérarchie d'âges",
        hearer="Yvette",
        doc_a="les deux emplois du temps",
        doc_b="la synthèse de Patrick",
        ce_doc="Zéro vainqueur",
        w1="comparaison", d1="mise en regard, sans podium",
        w2="nostalgie", d2="regret, parfois une arme",
        w3="synthèse", d3="texte qui retient sans couronner",
        w4="emploi", d4="temps d'une journée, à croiser",
        sv=("comparer", "compare"), nom="comparaison", nom2="synthèse",
        decoy1="Que Patrick a déclaré Sami vainqueur",
        decoy2="Que Yvette a interdit les colonnes",
        decoy3="Que les heures calmes n'ont jamais existé",
        beats="Selon Yvette, les soirs étaient plus lents ; d'après Sami, ils étaient plus muets pour certains. | Il ressort que les lanternes pèsent autant. | Alors que l'un veut le silence, l'autre veut le micro, la cour a besoin des deux. | Aline : à mesure que l'on compare, on découvre les non-dits. | Mado rature mieux avant. | Lila lira les deux colonnes. | Joël : le fer n'a pas de nostalgie. | Marc : une synthèse sans vainqueur est déjà un geste politique.",
    ),
    # ----- C1-6 dossier 6 travail -----
    D(
        title="Pas de tout le monde dit",
        lang="selon tel cahier / tel micro ; organisation du travail",
        lang_type="compte_rendu",
        obj="Réaliser une revue de presse de l'atelier et de la radio, sans fusionner les sources.",
        theme="la revue de presse du Seuil",
        slogan="tout le monde dit",
        promise="efface les signatures",
        obstacle="une revue trop lisse pour être honnête",
        who="Lila Sow",
        concede="raccourcir aide l'oreille",
        cond="l'on garde selon et d'après",
        implicit="tout le monde dit est déjà une prise de pouvoir sur les sources",
        implicit_short="Une prise de pouvoir sur les sources",
        reform="la revue attribue : Cahier des racines, Radio Figuier, affiche de l'atelier",
        proposal="trois extraits, trois attributions, un point de friction nommé",
        datum="Lila a cité Marc, Rose, Karim ; coupé un anonymat trop commode ; gardé un désaccord.",
        datum_short="Trois noms, un anonymat refusé, un désaccord gardé",
        stake="il s'agit que le travail de la cour ait des voix, pas une rumeur",
        hearer="Marc Nkurunziza",
        doc_a="le Cahier des racines du mardi",
        doc_b="l'antenne de Radio Figuier du mercredi",
        ce_doc="Pas de tout le monde dit",
        w1="revue", d1="tour de sources attribuées",
        w2="source", d2="texte ou micro nommé",
        w3="attribution", d3="selon / d'après",
        w4="friction", d4="désaccord conservé, pas gommée",
        sv=("citer", "cite"), nom="revue", nom2="source",
        decoy1="Que Lila a fusionné Marc et Rose",
        decoy2="Que Marc a interdit l'antenne",
        decoy3="Que l'atelier n'a pas d'affiche",
        beats="Selon le Cahier, l'atelier manque de relais ; d'après l'antenne, la radio manque d'heures. | Il ressort que les deux manques se parlent. | Rose a dit que les mains n'apparaissent pas dans les unes. | Karim a chiffré les heures. | Aline : tout le monde dit est interdit en revue. | Joël écoute sa propre absence et la nomme. | Patrick veut la friction, pas la paix fausse. | Marc : une revue de presse est un art d'attribution.",
    ),
    D(
        title="Accroche et entretien",
        lang="discours indirect ; accroche d'offre ; témoignage",
        lang_type="disc_ind",
        obj="Témoigner d'un entretien et rédiger une accroche d'offre sans mensonge.",
        theme="l'entretien de Joël à l'atelier",
        slogan="super profil",
        promise="habille le poste d'un mot trop grand",
        obstacle="une accroche qui n'a pas de mains",
        who="Joël Mugisha",
        concede="une phrase courte attire l'œil",
        cond="l'on y lise encore le fer, les heures, le relais",
        implicit="super profil flatte pour ne pas dire ce que le poste exige vraiment",
        implicit_short="Ne pas dire ce que le poste exige",
        reform="Joël a dit qu'il poserait le casque ; l'accroche n'a pas à le transformer en héros",
        proposal="une accroche juste, puis un témoignage d'entretien au discours indirect",
        datum="Joël a parlé de relais ; Karim a parlé de chiffres ; l'accroche trop grande a été raturée deux fois.",
        datum_short="Relais, chiffres, accroche raturée deux fois",
        stake="il s'agit de recruter sans mentir sur la peine ni sur la joie",
        hearer="Karim Bamba",
        doc_a="l'accroche raturée",
        doc_b="le témoignage de Joël",
        ce_doc="Pas de super profil",
        w1="accroche", d1="première phrase d'une offre, à tenir juste",
        w2="entretien", d2="échange, pas un interrogatoire",
        w3="poste", d3="travail nommé, avec heures",
        w4="témoignage", d4="récit d'expérience, au DI souvent",
        sv=("raturer", "rature"), nom="accroche", nom2="entretien",
        decoy1="Que Joël a menti sur le casque",
        decoy2="Que Karim a écrit super profil",
        decoy3="Que Rose a interdit l'atelier",
        beats="Joël a dit qu'il poserait le casque dès l'aube si le relais existait. | Rose a demandé si l'on nommait les mains dans l'accroche. | Karim a prétendu que les heures étaient déjà trop longues, puis a corrigé. | Lila a exigé que l'on coupe super profil. | Aline : le DI au passé décale les temps, il n'embellit pas. | Dieudonné a écouté derrière la porte, puis s'est montré. | Yvette : un entretien n'est pas une chasse. | Marc : témoigner, c'est garder le fer dans la phrase.",
    ),
    D(
        title="Conflit à l'atelier",
        lang="rapporter une crise ; style indirect libre ; on aurait dit",
        lang_type="disc_ind",
        obj="Comprendre un conflit de travail et le rapporter sans le romancer.",
        theme="la crise de l'atelier",
        slogan="c'est la faute des autres",
        promise="désigne un coupable trop vite",
        obstacle="une table trop froide après la voix trop haute",
        who="Rose Iradukunda",
        concede="élever la voix arrive",
        cond="l'on revienne aux heures, au relais, au fer, pas à l'humiliation",
        implicit="c'est la faute des autres évite de compter les heures mal partagées",
        implicit_short="Éviter de compter les heures mal partagées",
        reform="rapporter un discours de crise, c'est garder les propos, signaler le ton, refuser le roman",
        proposal="un compte-rendu : ce qui a été dit, ce qui a été tu, ce que l'atelier peut décider",
        datum="Deux voix trop hautes ; une heure de silence ; un relais promis, puis oublié, puis réécrit.",
        datum_short="Deux voix trop hautes, une heure de silence, un relais réécrit",
        stake="il s'agit que la crise serve à réparer le travail, pas à créer un héros et un traître",
        hearer="Dieudonné Hakizimana",
        doc_a="le compte-rendu de Rose",
        doc_b="les notes de Karim",
        ce_doc="Pas de roman de crise",
        w1="conflit", d1="désaccord de travail, à rapporter",
        w2="crise", d2="moment trop tendu, pas une légende",
        w3="relais", d3="partage des heures, souvent l'enjeu",
        w4="compte-rendu", d4="texte factuel, sans héros",
        sv=("rapporter", "rapporte"), nom="conflit", nom2="crise",
        decoy1="Que Rose a renvoyé Joël",
        decoy2="Que Dieudonné a crié",
        decoy3="Que le relais n'a jamais existé comme enjeu",
        beats="On aurait dit que la table allait se fendre ; elle n'a fait que refroidir. | Rose a dit qu'elle garderait les propos, pas les insultes. | Joël a demandé si l'on parlait encore du relais. | Karim a chiffré, trop tôt. | Aline : le style indirect libre peut montrer la fièvre, il ne doit pas l'inventer. | Lila n'enregistrera pas la crise comme un spectacle. | Patrick propose une heure calme avant de décider. | Marc : une crise du travail se répare au relais, pas au roman.",
    ),
    D(
        title="Là-bas n'est pas une morale",
        lang="concession ; hypothèse ; habitudes professionnelles ailleurs",
        lang_type="nom_conc",
        obj="Présenter des départs et des ailleurs inventés, sans mirage.",
        theme="les ailleurs trop brillants",
        slogan="là-bas c'est mieux",
        promise="efface le Seuil d'un revers de valise",
        obstacle="une promesse d'heures plus douces jamais datée",
        who="Karim Bamba",
        concede="partir peut être juste",
        cond="l'on n'humilie pas ceux qui restent, ni ceux qui reviennent",
        implicit="là-bas c'est mieux sert trop souvent à ne plus améliorer ici",
        implicit_short="Ne plus améliorer ici",
        reform="encore que l'ailleurs attire, le Seuil a des heures à réparer",
        proposal="recueillir trois témoignages : parti, resté, revenu, sans podium",
        datum="Trois lettres ; une valise trop légère ; zéro contrat lu jusqu'au bout dans le récit trop brillant.",
        datum_short="Trois lettres, une valise légère, zéro contrat lu au bout",
        stake="il s'agit de parler d'ailleurs sans faire du Seuil une honte",
        hearer="Hawa Diallo",
        doc_a="les lettres d'ailleurs inventées",
        doc_b="les voix du banc",
        ce_doc="Là-bas n'est pas une morale",
        w1="ailleurs", d1="lieu projeté, parfois un mirage",
        w2="contrat", d2="texte à lire, plus que la valise",
        w3="témoignage", d3="voix d'un parcours, sans podium",
        w4="habitude", d4="pratique professionnelle, variable selon les rives",
        sv=("partir", "parte"), nom="ailleurs", nom2="contrat",
        decoy1="Que Karim a vendu des valises",
        decoy2="Que Hawa méprise ceux qui partent",
        decoy3="Que le Seuil interdit tout départ",
        beats="Karim : encore que l'on promette des heures plus douces, le contrat n'était pas dans la lettre. | Hawa est partie, revenue, sans devoir choisir un camp. | Joël reste, et ce n'est pas un échec. | Aline refuse le mot eldorado collé comme une insulte. | Rose a cousu pour un départ, puis pour un retour. | Lila recueillera les trois voix. | Yvette : là-bas c'est mieux n'est pas une analyse. | Marc : intégrer des témoignages, c'est refuser le podium.",
    ),
    D(
        title="Témoignages croisés",
        lang="intégrer des citations ; il a déclaré que ; nuance",
        lang_type="disc_ind",
        obj="Intégrer des témoignages dans une analyse du travail au Seuil.",
        theme="les voix croisées de l'atelier et de la radio",
        slogan="on a tous le même avis",
        promise="lisse les citations jusqu'au consensus faux",
        obstacle="une analyse sans aspérités",
        who="Marc Nkurunziza",
        concede="trouver un point commun aide",
        cond="l'on garde les phrases qui gênent",
        implicit="on a tous le même avis est le contraire d'une enquête",
        implicit_short="Le contraire d'une enquête",
        reform="intégrer, c'est citer, attribuer, commenter, pas fondre",
        proposal="une analyse : trois citations, deux frictions, une proposition de relais",
        datum="Marc a cité Rose, Joël, Lila ; gardé deux frictions ; refusé un tous d'accord final.",
        datum_short="Trois citations, deux frictions, zéro tous d'accord",
        stake="il s'agit que l'analyse ressemble au travail réel, pas à une brochure",
        hearer="Rose Iradukunda",
        doc_a="les témoignages bruts",
        doc_b="l'analyse de Marc",
        ce_doc="Garder ce qui gêne",
        w1="citation", d1="parole attribuée, non fondue",
        w2="analyse", d2="texte qui commente les voix",
        w3="friction", d3="désaccord conservé",
        w4="enquête", d4="écoute structurée, pas un avis unique",
        sv=("citer", "cite"), nom="citation", nom2="analyse",
        decoy1="Que Marc a lissé Rose",
        decoy2="Que Joël a refusé d'être cité",
        decoy3="Que Lila a exigé un consensus",
        beats="Rose a déclaré que les mains manquaient dans les unes. | Joël a dit qu'il reviendrait si le relais tenait. | Lila a demandé si l'on pouvait garder le doute à l'antenne. | Aline : intégrer n'est pas fondre. | Karim ajoute un chiffre, pas un verdict. | Patrick relit les aspérités. | Dieudonné signe le relais proposé. | Marc : une analyse du travail au Seuil se juge à ce qu'elle n'a pas gommé.",
    ),
    D(
        title="Analyse du travail au Seuil",
        lang="synthèse argumentée ; encore que ; il s'agit de",
        lang_type="reco",
        obj="Conclure le module par une analyse : organisation, recrutement, crise, ailleurs.",
        theme="le travail au Seuil comme horizon commun",
        slogan="on verra plus tard",
        promise="reporte le relais à une saison trop vague",
        obstacle="une analyse sans calendrier",
        who="Aline Uwase",
        concede="tout ne se répare pas en un jeudi",
        cond="l'on date ce qui peut l'être : relais, accroche, rampe de l'atelier",
        implicit="on verra plus tard est la phrase préférée de ce qui n'a pas à porter les lanternes",
        implicit_short="Phrase de ceux qui ne portent pas les lanternes",
        reform="il s'agit de tenir ensemble les voix, les heures et la date",
        proposal="un texte final : quatre constats, deux gestes datés, une revue dans un mois",
        datum="Quatre constats écrits ; deux dates ; une revue promise sous le figuier dans un mois.",
        datum_short="Quatre constats, deux dates, une revue dans un mois",
        stake="il s'agit que C1-6 ne reste pas une suite de récits, mais une cour qui décide",
        hearer="Joël Mugisha",
        doc_a="les quatre séquences précédentes",
        doc_b="la motion d'Aline",
        ce_doc="Deux dates, pas plus tard",
        w1="constat", d1="fait établi, distinct d'un slogan",
        w2="calendrier", d2="dates, plus précis que plus tard",
        w3="relais", d3="partage des heures, geste central",
        w4="motion", d4="décision de cour, relisible",
        sv=("dater", "date"), nom="constat", nom2="calendrier",
        decoy1="Que Aline a tout remis à l'année suivante",
        decoy2="Que Joël a refusé les dates",
        decoy3="Que le relais est un luxe",
        beats="Aline : il convient que l'on date le relais, encore que tout ne se répare pas jeudi. | Joël entend enfin son nom dans une motion. | Rose exige que l'accroche reste juste. | Karim veut la revue dans un mois, pas un nuage. | Lila ouvrira l'antenne pour la revue. | Patrick relie C1-6 aux heures de la colline. | Dieudonné peut commencer le fer. | Marc : une analyse qui n'agit pas n'était qu'un exercice.",
    ),
]
