"""36 kernels C1 compact (dossiers 1–6 Cosmopolite 5 → objectifs génériques)."""
from __future__ import annotations

from complete import build


def D(**k):
    return k


ROWS = [
    # ----- C1-1 dossier 1 urbanisme / logement / mobilité / fantastique -----
    D(
        title="La colline future",
        lang="nominalisation ; encore que / pour autant que + subjonctif",
        lang_type="nom_conc",
        obj="Rendre compte de deux regards sur la colline future sans les fusionner.",
        theme="la colline de demain",
        slogan="colline de demain",
        promise="promette des lanternes plus hautes",
        obstacle="le parking projeté à la racine du figuier",
        who="Léa Niyonzima",
        concede="la densification peut protéger les jardins",
        cond="l'on en discute avant les camions",
        implicit="l'effacement possible du mot figuier n'est pas un accident de vocabulaire",
        implicit_short="L'effacement possible du mot figuier",
        reform="la densification n'est un abri que si elle cesse d'être un parking habillé de mots",
        proposal="garder deux voix dans le compte-rendu et une rampe avant les lanternes nouvelles",
        datum="Karim compte trois files de camions, zéro banc nouveau, une ombre de moins à midi.",
        datum_short="Trois files de camions, zéro banc, une ombre de moins",
        stake="il s'agit de garder une colline habitable, non une affiche lumineuse",
        hearer="Hawa Diallo",
        doc_a="le calque de Nina Kayitesi",
        doc_b="la tribune de Marc Nkurunziza",
        ce_doc="Ce que le plan ne dit pas",
        w1="urbanisme", d1="organisation raisonnée de l'espace habité",
        w2="densification", d2="processus qui resserre l'habitat",
        w3="mixité", d3="cohabitation d'usages et de voix",
        w4="friche", d4="terrain en attente, non un vide",
        sv=("promettre", "promette"), nom="densification", nom2="mixité",
        decoy1="Que les lanternes seront plus basses dès demain",
        decoy2="Que Nina refuse tout calque par principe",
        decoy3="Que Félicie fermera le Marché des Herbes",
        beats="Nina Kayitesi déroule un calque : la friche n'est pas un vide, c'est une mémoire en attente de verbe. | Patrick refuse qu'on accélère la pente au nom d'un urbanisme qui n'aurait d'urbain que la vitesse. | Joël rappelle que porter les lanternes n'est pas habiter : l'une éclaire, l'autre reste. | Rose coupe un tissu ocre et dit que le plan, s'il n'habille personne, n'est qu'une affiche. | Solange demande qui paiera la rampe, car une colline sans rampe n'accueille que ceux qui montent vite. | Félicie pose le bol : on ne mange pas un plan, on mange ce que la pente laisse pousser. | Dieudonné réparera l'escalier une fois que l'on aura nommé s'il reste un escalier. | Marc Nkurunziza : un compte-rendu n'est pas une victoire, c'est une hospitalité faite aux désaccords.",
    ),
    D(
        title="Habiter autrement",
        lang="synthèse ; ce dont / ce à quoi ; relatives complexes",
        lang_type="rel_synthese",
        obj="Dégager l'essentiel de deux documents sur l'habitat partagé et en rédiger la synthèse.",
        theme="l'habitat partagé du Pavillon du Saule",
        slogan="toit commun",
        promise="garantisse une serrure pour chacun",
        obstacle="la cour fermée à clé dès dix-neuf heures",
        who="Hawa Diallo",
        concede="partager le toit peut alléger les loyers inventés du Pavillon",
        cond="l'on nomme les heures de silence autant que les heures de soupe",
        implicit="ceux qui disent famille élargie veulent parfois dire plus de témoins et moins de portes",
        implicit_short="Plus de témoins, moins de portes",
        reform="un toit commun n'est pas une famille : c'est un contrat de souffle et d'ombre",
        proposal="écrire une synthèse qui retienne loyers, heures calmes et ce dont personne ne veut parler : la clé",
        datum="Yvette note quatre lits, deux clés, une soupe à vingt heures, zéro banc pour écrire.",
        datum_short="Quatre lits, deux clés, une soupe, zéro banc d'écriture",
        stake="il s'agit de pouvoir rentrer sans demander pardon d'exister",
        hearer="Rose Iradukunda",
        doc_a="la chronique de Lila Sow",
        doc_b="l'entretien écrit de Dieudonné Hakizimana",
        ce_doc="La clé et la soupe",
        w1="synthèse", d1="texte qui retient l'essentiel de plusieurs sources",
        w2="habitat", d2="manière d'habiter, plus large que le toit",
        w3="silence", d3="heure nommée pour ne pas s'écraser",
        w4="clé", d4="droit de fermer, pas seulement d'ouvrir",
        sv=("nommer", "nomme"), nom="synthèse", nom2="habitat",
        decoy1="Que Lila interdira la soupe",
        decoy2="Que Dieudonné veut vendre le Pavillon",
        decoy3="Que le silence est une punition inventée par Karim",
        beats="Dieudonné habite le Pavillon : il répare, il n'écoute pas les conversations comme un loyer. | Lila a enregistré une chronique où le mot famille revient trop souvent pour ne pas cacher une peur. | Patrick demande ce à quoi l'on s'engage quand on pose son sac : la vaisselle, ou le silence ? | Aline insiste : la relative ce dont nous avons besoin n'est pas un ornement, c'est le noyau. | Karim refuse qu'on appelle solidarité le fait de tout entendre à travers la planche. | Félicie apporte la soupe et sort : elle n'est pas une preuve que le toit suffit. | Sami dit qu'il aime le bruit ; Yvette répond qu'aimer le bruit n'est pas une loi. | Marc : synthétiser, ce n'est pas couper les aspérités jusqu'à ce que tout le monde ait l'air d'accord.",
    ),
    D(
        title="Circuler à Rukiri-Nord",
        lang="il convient que / il s'agit de ; recommandations",
        lang_type="reco",
        obj="Faire des recommandations pour une mobilité qui n'écrase pas la pente.",
        theme="la mobilité sur la pente de Rukiri-Nord",
        slogan="fluidifier la colline",
        promise="élargisse la route des camions",
        obstacle="le trottoir trop étroit pour Joël et les lanternes",
        who="Patrick Habimana",
        concede="un relais de lanternes peut aider le soir",
        cond="l'on n'y voie pas le droit de rouler plus vite",
        implicit="fluidifier veut souvent dire faire passer les camions avant les genoux",
        implicit_short="Les camions avant les genoux",
        reform="recommander, ce n'est pas crier : c'est dire ce qu'il convient de faire, et pour qui",
        proposal="un relais humain, un trottoir nommé, un camion plus rare à l'heure de la soupe",
        datum="Joël a compté dix-huit lanternes, deux pauses, zéro place pour croiser un enfant.",
        datum_short="Dix-huit lanternes, deux pauses, zéro croisement d'enfant",
        stake="il s'agit de descendre vivant, pas seulement plus vite",
        hearer="Joël Mugisha",
        doc_a="l'émission de Radio Figuier",
        doc_b="la note de Nina Kayitesi sur la pente",
        ce_doc="La pente n'est pas une piste",
        w1="mobilité", d1="façon de se déplacer, pas seulement de rouler",
        w2="trottoir", d2="bande où l'on peut croiser sans supplier",
        w3="relais", d3="pause humaine pour les lanternes",
        w4="recommandation", d4="avis argumenté, distinct d'un ordre",
        sv=("ralentir", "ralentisse"), nom="recommandation", nom2="mobilité",
        decoy1="Que Joël vendra les lanternes",
        decoy2="Que Nina veut interdire toute marche",
        decoy3="Que le figuier sera déplacé en bas",
        beats="Nina dessine un trait trop droit : la pente, elle, n'est pas droite. | Joël dit qu'un camion n'a pas d'oreilles pour un « attention ». | Léa propose un relais sous le saule, non un klaxon de plus. | Karim chiffre les minutes gagnées et refuse de les nommer un bonheur. | Solange demande qui portera les jarres si le trottoir disparaît. | Dieudonné réparerait bien la rampe, pour autant qu'on la finance. | Sami court ; Yvette rappelle qu'un enfant n'est pas un obstacle. | Marc : il convient que l'on nomme les genoux dans la motion, pas seulement les roues.",
    ),
    D(
        title="Midi sans ombre",
        lang="conditionnel d'hypotypose ; comme si ; on dirait que",
        lang_type="hypotypose",
        obj="Décrire une Rukiri-Nord imaginaire pour faire entendre une peur vraie.",
        theme="une Rukiri-Nord trop lisse",
        slogan="ville parfaite",
        promise="efface toute ombre sous le figuier",
        obstacle="une tour qui avalerait midi",
        who="Mado",
        concede="inventer peut aider à voir ce que le plan cache",
        cond="l'on n'oublie pas que le cauchemar parle du présent",
        implicit="la ville trop nette est souvent une ville où l'on n'a plus le droit de s'asseoir",
        implicit_short="Plus le droit de s'asseoir",
        reform="le fantastique ici n'est pas une évasion : c'est une loupe",
        proposal="écrire la colline comme si les racines parlaient, puis revenir au banc réel",
        datum="Dans le récit de Mado, midi n'a plus d'ombre à compter : zéro, dit-elle, et c'est déjà trop.",
        datum_short="Midi sans ombre, zéro abri",
        stake="il s'agit de reconnaître la peur avant qu'elle ne s'appelle progrès",
        hearer="Sami",
        doc_a="l'extrait inventé de Mado",
        doc_b="la photo de la pente prise par Léa",
        ce_doc="Midi sans ombre",
        w1="hypotypose", d1="description qui donne à voir, souvent au conditionnel",
        w2="ombre", d2="abri de midi, pas un défaut du plan",
        w3="tour", d3="verticale trop sûre d'elle",
        w4="racine", d4="mémoire du sol, plus ancienne que l'affiche",
        sv=("inventer", "invente"), nom="hypotypose", nom2="ombre",
        decoy1="Que Mado veut construire la tour",
        decoy2="Que Léa refuse toute fiction",
        decoy3="Que Sami a mesuré midi avec une règle",
        beats="Mado écrit : la rivière prendrait une voix pour demander où l'on a mis ses roseaux. | On dirait que les lanternes marcheraient toutes seules, fatiguées d'être portées. | Si le figuier pouvait tousser, il tousserait la poussière des camions. | Aline : le conditionnel ici n'est pas une politesse, c'est une peinture. | Patrick a peur des récits trop beaux : ils habillent souvent une coupe. | Rose coud une ombre trop large, exprès, pour le texte. | Joël n'aime pas les tours : elles n'ont pas de relais. | Lila lira l'extrait à voix basse, comme si la colline écoutait.",
    ),
    D(
        title="Recommandations pour la colline",
        lang="connecteurs de recommandation ; il convient que ; en vue de",
        lang_type="reco",
        obj="Transformer l'analyse en motion claire pour l'assemblée sous le figuier.",
        theme="la motion de la colline",
        slogan="passer à l'action",
        promise="signe trop vite une motion trop lisse",
        obstacle="une action sans destinataires nommés",
        who="Solange Mukamana",
        concede="il faut parfois voter avant la saison des pluies",
        cond="l'on ait entendu la rampe, le trottoir et la clé",
        implicit="passer à l'action peut servir à ne plus entendre ceux qui marchent lentement",
        implicit_short="Ne plus entendre ceux qui marchent lentement",
        reform="une recommandation nomme qui fait, qui paie, qui peut refuser",
        proposal="trois gestes datés : rampe, relais, heures de camions, signés par le Bureau des Escales",
        datum="Le banc a recensé onze voix pour la rampe, quatre abstentions, zéro pour le parking du figuier.",
        datum_short="Onze voix pour la rampe, zéro pour le parking",
        stake="il s'agit que la motion puisse se relire dans un an sans honte",
        hearer="Karim Bamba",
        doc_a="les notes d'assemblée d'Aline",
        doc_b="le brouillon de Solange",
        ce_doc="Trois gestes, pas un slogan",
        w1="motion", d1="texte voté, plus précis qu'un cri",
        w2="destinataire", d2="personne nommée pour un geste",
        w3="rampe", d3="pente habitable pour qui ne court pas",
        w4="assemblée", d4="lieu où l'on vote après avoir entendu",
        sv=("signer", "signe"), nom="motion", nom2="rampe",
        decoy1="Que Karim a déjà bétonné le figuier",
        decoy2="Que Solange refuse tout vote",
        decoy3="Que le Bureau des Escales n'existe plus",
        beats="Solange lit trop vite ; Aline lui demande de nommer qui portera la rampe. | Karim veut un calendrier, non une émotion. | Léa rappelle la clé du Pavillon : la colline n'est pas qu'une route. | Joël demande un relais écrit, pas promis. | Nina accepte de corriger le calque si la motion le force. | Dieudonné dit qu'il peut commencer jeudi, pour autant qu'on paie le fer. | Yvette : une motion sans date est un oubli poli. | Marc clôt : en vue de l'hivernage, il convient que l'on vote les trois gestes, pas l'affiche.",
    ),
    D(
        title="Compte-rendu 2040",
        lang="selon / d'après / il ressort que ; attribution des sources",
        lang_type="compte_rendu",
        obj="Rendre compte oralement de deux documents sur la colline, horizon inventé 2040.",
        theme="un horizon 2040 sous le figuier",
        slogan="Rukiri-Nord 2040",
        promise="annonce une colline sans files",
        obstacle="un horizon qui n'a plus de bancs",
        who="Marc Nkurunziza",
        concede="se projeter peut aider à choisir un geste dès cette saison",
        cond="l'on n'efface pas les noms de 2026 dans la projection",
        implicit="2040 sert parfois à ne plus devoir répondre des camions d'aujourd'hui",
        implicit_short="Ne plus répondre des camions d'aujourd'hui",
        reform="le compte-rendu attribue : selon Nina ceci, d'après Marc cela, il ressort que la rampe précède la tour",
        proposal="un oral de quatre minutes : deux sources, un désaccord, un geste 2026 qui rend 2040 habitable",
        datum="Léa a chronométré : quatre minutes, deux noms de sources, zéro slogan « ville parfaite ».",
        datum_short="Quatre minutes, deux sources, zéro slogan",
        stake="il s'agit que 2040 n'efface pas Joël sous les lanternes de 2026",
        hearer="Nina Kayitesi",
        doc_a="le calque annoté « 2040 »",
        doc_b="la chronique de Marc pour Radio Figuier",
        ce_doc="2040 sans effacer 2026",
        w1="horizon", d1="projection, pas une excuse",
        w2="attribution", d2="selon / d'après, pour ne pas fusionner",
        w3="geste", d3="action datée, plus courte qu'un rêve",
        w4="source", d4="document nommé dans le compte-rendu",
        sv=("attribuer", "attribue"), nom="attribution", nom2="horizon",
        decoy1="Que Nina a déjà vécu 2040",
        decoy2="Que Marc interdit toute projection",
        decoy3="Que Lila n'enregistre plus après 2026",
        beats="Selon Nina, 2040 n'est qu'un calque pour forcer la rampe dès cette saison. | D'après Marc, un horizon sans bancs n'est pas un avenir, c'est un oubli. | Il ressort que les deux documents s'opposent sur la tour, pas sur la soif d'ombre. | Aline : on n'écrit pas « tout le monde pense », on écrit selon qui. | Hawa refuse qu'on date 2040 pour ne plus dater les camions. | Joël demande si, en 2040, quelqu'un portera encore les lanternes. | Mado glisse une phrase au conditionnel, puis rature : ce n'est plus le moment du fantastique. | Lila : le compte-rendu se clôt sur un geste, pas sur un nuage.",
    ),
]

from rows_c1_rest import REST
from rows_c1_m3m6 import REST2

ROWS += REST + REST2


def module_rows(i: int) -> list[dict]:
    start = i * 6
    return [build(d) for d in ROWS[start : start + 6]]
