"""Séquences C2 modules 4–6 (mémoire, interculturel, rive)."""


def D(**k):
    return k


C = [
    # ----- C2-4 mémoire -----
    D(
        title="Le tableau de la cour",
        lang="raisonnement déductif ; intérêt d'un support pédagogique",
        lang_type="compte_rendu",
        obj="Démontrer l'intérêt d'un support inventé pour enseigner une mémoire de cour.",
        theme="un support trop controversé d'Aline",
        slogan="au tableau on ne discute pas",
        promise="tienne le craie pour une vérité sans source",
        obstacle="une pédagogie qui n'avoue pas ses angles",
        who="Aline Uwase",
        concede="un tableau fixe l'attention",
        cond="l'on y lise aussi ce qu'il éclaire trop, ce qu'il laisse dans l'ombre",
        implicit="on ne discute pas veut dire la craie a déjà choisi pour vous",
        implicit_short="La craie a déjà choisi",
        reform="il ressort qu'un support se juge à ce qu'il permet de déduire, et à ce qu'il empêche de voir",
        proposal="un essai : intérêt, angle mort, usage sous le figuier",
        datum="Aline a montré deux supports ; six déductions ; deux angles morts nommés.",
        datum_short="Deux supports, six déductions, deux angles morts",
        stake="il s'agit d'enseigner une mémoire, pas une obéissance",
        hearer="Patrick Habimana",
        doc_a="le support d'Aline",
        doc_b="la critique de Patrick",
        ce_doc="La craie a un angle",
        w1="support", d1="outil pédagogique, avec un angle",
        w2="déduction", d2="enchaînement justifié à partir du tableau",
        w3="angle", d3="part d'ombre d'un outil",
        w4="essai", d4="texte argumenté sur un intérêt pédagogique",
        sv=("démontrer", "démontre"), nom="support", nom2="déduction",
        decoy1="Que Aline interdit la discussion",
        decoy2="Que Patrick a brûlé le tableau",
        decoy3="Que les angles morts n'ont pas été nommés",
        c2_aside="Au tableau on ne discute pas : on reconnaît la sérénité des vérités qui n'ont pas à se sourcer.",
        beats="Selon Aline, le tableau aide à déduire ; d'après Patrick, il aide trop. | Il ressort que l'intérêt existe, et l'angle mort aussi. | Yvette se souvient autrement. | Lila n'enregistrera pas une leçon trop sûre. | Solange demande les sources de la craie. | Sami déduit trop vite ; on le ralentit. | Mado glisse une ironie sur la craie. | Marc : un essai pédagogique avoue ses angles.",
    ),
    D(
        title="Éditorial des pactes",
        lang="plan chronologique ; éditorial ; accords de rive inventés",
        lang_type="compte_rendu",
        obj="Rédiger un éditorial sur des pactes de cour, sans copier un traité réel.",
        theme="les pactes de la rive",
        slogan="l'union fait la force",
        promise="efface les désaccords datés",
        obstacle="un éditorial trop lyrique pour être historique",
        who="Marc Nkurunziza",
        concede="un pacte peut protéger",
        cond="l'on raconte dans quel ordre, qui a cédé, qui a gagné une rampe",
        implicit="l'union fait la force dispense trop souvent de dire qui a porté",
        implicit_short="Qui a porté",
        reform="un éditorial C2 a un plan chronologique, des noms, une ironie contre le lyrique trop facile",
        proposal="un éditorial : trois dates inventées de cour, un pacte, une rampe",
        datum="Marc a daté trois jeudis ; nommé Solange et Joël ; raturé l'union trop large.",
        datum_short="Trois jeudis, deux noms, union raturée",
        stake="il s'agit d'accords de cour, pas d'une carte d'États",
        hearer="Solange Mukamana",
        doc_a="les minutes trop lyriques",
        doc_b="l'éditorial de Marc",
        ce_doc="Des dates, pas un hymne",
        w1="pacte", d1="accord daté de cour, avec cessions",
        w2="éditorial", d2="texte d'opinion sourcé",
        w3="chronologie", d3="ordre des faits, plus qu'un hymne",
        w4="cession", d4="ce que l'on a lâché pour signer",
        sv=("dater", "date"), nom="pacte", nom2="éditorial",
        decoy1="Que Marc a écrit un hymne sans dates",
        decoy2="Que Solange a disparu du texte",
        decoy3="Que Joël n'a pas de rampe dans le pacte",
        c2_aside="L'union fait la force : on aimerait connaître le nom de ceux qui, dans l'union, portent.",
        beats="Marc : selon les minutes, le premier jeudi a cédé une heure ; le deuxième une rampe ; le troisième un silence. | D'après Solange, l'hymne arrivait trop tôt. | Il ressort qu'un pacte se raconte, il ne se chante pas. | Aline veut la chronologie. | Lila lira l'éditorial sans fanfare. | Patrick refuse la carte trop grande. | Yvette se souvient du troisième jeudi. | Nina : un accord de rive n'est pas un empire.",
    ),
    D(
        title="Les noms avant la formule",
        lang="analyse d'un discours ; chronique de veillée ; mémoire",
        lang_type="ironie",
        obj="Analyser un discours de veillée et enregistrer une chronique.",
        theme="la veillée sous le figuier",
        slogan="plus jamais ça",
        promise="tienne lieu de travail de mémoire",
        obstacle="une formule trop lisse pour les noms trop précis",
        who="Yvette",
        concede="une formule peut rassembler",
        cond="l'on dise ensuite qui, quand, comment l'on veille",
        implicit="plus jamais ça trop seul permet de ne plus nommer",
        implicit_short="Ne plus nommer",
        reform="une chronique C2 ralentit le slogan, rend les noms, refuse l'oubli poli",
        proposal="un discours lu, une chronique : noms, silence, ce que le slogan évitait",
        datum="Yvette a nommé sept personnes ; Lila a gardé un silence ; le slogan trop lisse a été reculé.",
        datum_short="Sept noms, un silence, slogan reculé",
        stake="il s'agit de se souvenir, pas de se donner le change",
        hearer="Patrick Habimana",
        doc_a="le discours trop lisse",
        doc_b="la chronique d'Yvette",
        ce_doc="Les noms avant la formule",
        w1="veillée", d1="temps de mémoire, avec des noms",
        w2="discours", d2="parole publique à analyser",
        w3="chronique", d3="texte parlé, plus lent qu'un slogan",
        w4="oubli", d4="politesse trop commode",
        sv=("nommer", "nomme"), nom="veillée", nom2="discours",
        decoy1="Que Yvette a refusé les noms",
        decoy2="Que Patrick a crié le slogan",
        decoy3="Que Lila a coupé tous les silences",
        c2_aside="Plus jamais ça : on notera la commodité d'un ça qui n'a plus à porter de prénom.",
        beats="Yvette : loin de rassembler, le slogan trop tôt dispersait les noms. | Patrick refuse l'oubli poli. | Aline analyse le discours : qui parle, pour qui, ce qu'il évite. | Lila ralentit. | Solange pose une lanterne, pas une formule. | Sami se tait, pour une fois juste. | Mado écrit les sept prénoms. | Marc : une chronique de mémoire se juge à ce qu'elle n'a pas lissé.",
    ),
    D(
        title="Plaidoirie sous le figuier",
        lang="plan d'une plaidoirie ; contexte et opinion ; justice de cour",
        lang_type="reco",
        obj="Analyser et rédiger le plan d'une plaidoirie inventée, sans procès d'État.",
        theme="une plaidoirie au Bureau des Escales",
        slogan="l'opinion a déjà jugé",
        promise="remplace le plan par la rumeur",
        obstacle="un contexte trop bruyant pour une introduction nette",
        who="Solange Mukamana",
        concede="l'opinion pèse",
        cond="l'on commence pourtant par les faits, les textes de cour, la demande",
        implicit="l'opinion a déjà jugé invite à n'avoir plus de plan",
        implicit_short="N'avoir plus de plan",
        reform="il convient que l'introduction nomme le contexte sans s'y noyer",
        proposal="un plan : faits, textes, contexte, demande ; puis l'introduction lue",
        datum="Solange a tenu quatre parties ; reculé la rumeur en note ; lu l'introduction en trois minutes.",
        datum_short="Quatre parties, rumeur en note, trois minutes",
        stake="il s'agit d'une justice de cour, pas d'un spectacle",
        hearer="Marc Nkurunziza",
        doc_a="le bruit du fil",
        doc_b="le plan de Solange",
        ce_doc="La rumeur en note, pas en tête",
        w1="plaidoirie", d1="discours de demande, avec un plan",
        w2="contexte", d2="bruit autour, à nommer sans s'y noyer",
        w3="introduction", d3="ouverture, trois minutes ici",
        w4="demande", d4="ce que l'on exige du Bureau",
        sv=("introduire", "introduise"), nom="plaidoirie", nom2="contexte",
        decoy1="Que Solange a commencé par la rumeur",
        decoy2="Que Marc a jugé avant le plan",
        decoy3="Que le Bureau est un État",
        c2_aside="L'opinion a déjà jugé : on appréciera la modestie de ceux qui n'ont pas à ouvrir un dossier.",
        beats="Solange : il convient que l'on introduise les faits, encore que le fil ait déjà crié. | Marc place la rumeur en note. | Aline veut les textes de cour. | Lila n'enregistrera pas un spectacle. | Patrick chronomètre l'introduction. | Yvette écoute comme si les noms étaient là. | Dieudonné tient la porte. | Léa : une plaidoirie C2 a un plan, ou n'est qu'un bruit.",
    ),
    D(
        title="Essai du support",
        lang="essai argumenté ; déduction ; pédagogie de mémoire",
        lang_type="compte_rendu",
        obj="Rédiger l'essai promis : intérêt d'un support pour une mémoire de cour.",
        theme="l'essai d'Aline relu par la cour",
        slogan="c'est pédagogique donc c'est bien",
        promise="dispense de l'angle mort",
        obstacle="un donc trop généreux",
        who="Patrick Habimana",
        concede="pédagogique peut être une qualité",
        cond="l'on examine encore ce que le support fait aux noms",
        implicit="donc c'est bien évite l'essai véritable",
        implicit_short="Éviter l'essai véritable",
        reform="selon le support, on déduit ; d'après les noms, on doute ; il ressort qu'il faut les deux",
        proposal="un essai de vingt lignes : intérêt, angle, usage, limite",
        datum="Patrick a gardé l'intérêt ; nommé l'angle ; proposé un usage ; refusé le donc.",
        datum_short="Intérêt, angle, usage, donc refusé",
        stake="il s'agit d'un essai, pas d'un tampon",
        hearer="Aline Uwase",
        doc_a="le brouillon trop sûr",
        doc_b="l'essai de Patrick",
        ce_doc="Le donc n'est pas un essai",
        w1="intérêt", d1="ce que le support permet, à démontrer",
        w2="limite", d2="ce qu'il empêche de voir",
        w3="usage", d3="manière de s'en servir sous le figuier",
        w4="tampon", d4="approbation trop vite donnée",
        sv=("examiner", "examine"), nom="intérêt", nom2="limite",
        decoy1="Que Patrick a refusé tout support",
        decoy2="Que Aline a exigé le donc",
        decoy3="Que les noms n'apparaissent pas dans l'essai",
        c2_aside="C'est pédagogique donc c'est bien : syllogisme dont on aimerait voir la mineure.",
        beats="Patrick : selon le tableau, l'on déduit plus vite ; d'après Yvette, l'on nomme moins. | Il ressort qu'un essai tient les deux. | Aline accepte l'angle. | Lila lira lentement. | Solange veut l'usage concret. | Sami s'ennuie d'un tampon. | Mado glisse une phrase sur le donc. | Marc : un essai C2 se relit, il ne se tamponne pas.",
    ),
    D(
        title="Chronique de veillée",
        lang="voix de chronique ; noms ; silence",
        lang_type="ironie",
        obj="Enregistrer la chronique finale de mémoire, C2.",
        theme="la chronique que Lila n'adoucira pas",
        slogan="une belle cérémonie",
        promise="transforme la veillée en décor",
        obstacle="un bel qui n'a plus de prénoms",
        who="Lila Sow",
        concede="une forme soignée aide l'oreille",
        cond="l'on n'y lise pas une fête",
        implicit="belle cérémonie est déjà un oubli poli",
        implicit_short="Un oubli poli",
        reform="loin d'être belle, la veillée fut juste, ce qui est autre chose, et plus difficile",
        proposal="une chronique de quatre minutes : noms, un silence, un refus du bel",
        datum="Lila a lu sept noms ; gardé huit secondes ; coupé belle cérémonie.",
        datum_short="Sept noms, huit secondes, bel coupé",
        stake="il s'agit d'une voix de radio qui ne se donne pas le change",
        hearer="Yvette",
        doc_a="le rush trop soigné",
        doc_b="la chronique retenue",
        ce_doc="Juste, pas belle",
        w1="cérémonie", d1="forme, trop vite dite belle",
        w2="prénom", d2="nom propre, travail de mémoire",
        w3="rush", d3="enregistrement brut, à raturer",
        w4="justesse", d4="qualité distincte de la beauté d'affiche",
        sv=("adoucir", "adoucisse"), nom="cérémonie", nom2="prénom",
        decoy1="Que Lila a gardé belle cérémonie",
        decoy2="Que Yvette a exigé une fête",
        decoy3="Que les sept noms ont disparu",
        c2_aside="Une belle cérémonie : on reconnaît le compliment de ceux qui n'avaient personne à nommer.",
        beats="Lila : loin d'adoucir, j'ai coupé le bel. | Yvette entend les prénoms. | Aline accepte le silence. | Patrick refuse la fête. | Sami se tait encore. | Mado écrit juste. | Solange pose la lanterne. | Marc : une chronique C2 se juge à ce qu'elle n'a pas trop poli.",
    ),
    # ----- C2-5 interculturel -----
    D(
        title="Culture partagée",
        lang="implicite ; accessibilité ; position non criée",
        lang_type="ironie",
        obj="Rédiger un article qui exprime implicitement une position sur l'accès à la Salle.",
        theme="l'accès trop cher à la Salle des Herbes",
        slogan="la culture est à tout le monde",
        promise="dispense d'ouvrir vraiment la porte",
        obstacle="un billet trop haut pour Hawa, un mot trop généreux",
        who="Hawa Diallo",
        concede="un mot généreux peut précéder un geste",
        cond="l'on baisse ensuite le billet, ou l'on cesse le mot",
        implicit="à tout le monde, sans rampe ni tarif, est une invitation à se taire",
        implicit_short="Une invitation à se taire",
        reform="l'article ne criera pas : il décrira la porte, le tarif, le mot, et l'écart fera le travail",
        proposal="un article implicite : faits, écart, zéro slogan retourné",
        datum="Hawa a cité le tarif ; la rampe absente ; le mot généreux ; zéro cri.",
        datum_short="Tarif, rampe absente, mot généreux, zéro cri",
        stake="il s'agit d'une position, pas d'une affiche contraire",
        hearer="Rose Iradukunda",
        doc_a="l'affiche trop généreuse",
        doc_b="l'article d'Hawa",
        ce_doc="Le mot, la porte, l'écart",
        w1="accessibilité", d1="possibilité réelle d'entrer",
        w2="tarif", d2="prix du billet, trop parfois haut",
        w3="implicite", d3="position non criée, lisible",
        w4="écart", d4="distance entre le mot et la porte",
        sv=("ouvrir", "ouvre"), nom="accessibilité", nom2="tarif",
        decoy1="Que Hawa a crié dans l'article",
        decoy2="Que Rose a fermé la Salle",
        decoy3="Que le tarif n'est pas cité",
        c2_aside="La culture est à tout le monde : on vérifiera, par politesse, le tarif et la rampe.",
        beats="Hawa : il ne s'agirait que d'un détail, le tarif, à entendre l'affiche. | Loin d'ouvrir, le mot généreux fermait plus net. | Rose coud trop près de la porte. | Aline : l'implicite se justifie par l'écart. | Joël n'entre pas sous la pluie. | Lila lira sans coller un slogan contraire. | Patrick veut les faits. | Marc : une position C2 peut ne pas crier, elle doit se lire.",
    ),
    D(
        title="Qui paie le rire",
        lang="ressorts comiques ; humour ; succès trop facile",
        lang_type="ironie",
        obj="Expliquer une scène comique de cour sans en faire une recette, ni un procès.",
        theme="un sketch trop sûr de ses cibles",
        slogan="c'est de l'humour",
        promise="tienne lieu de droit de blesser",
        obstacle="un rire qui n'a plus d'oreille pour Hawa",
        who="Sami",
        concede="un sketch peut dénoncer",
        cond="l'on n'y visse pas toujours le même visage",
        implicit="c'est de l'humour arrive trop souvent après le geste qui a déjà fait mal",
        implicit_short="Après le geste qui a déjà fait mal",
        reform="expliquer un ressort, c'est dire qui paie le rire, et si le succès n'est qu'un confort",
        proposal="une explication : quiproquo, cible, limite, version raturée",
        datum="Sami a raturé une cible ; gardé un quiproquo ; Yvette a ri ; Hawa non, et c'est noté.",
        datum_short="Une cible raturée, un quiproquo, un rire, un non",
        stake="il s'agit de rire avec une cour, pas contre une bouche trop seule",
        hearer="Hawa Diallo",
        doc_a="le sketch trop dur",
        doc_b="la version raturée",
        ce_doc="Qui paie le rire",
        w1="ressort", d1="mécanisme comique, à expliquer",
        w2="cible", d2="personne visée, trop souvent la même",
        w3="quiproquo", d3="malentendu comique, parfois juste",
        w4="succès", d4="rire facile, pas une preuve morale",
        sv=("raturer", "rature"), nom="ressort", nom2="cible",
        decoy1="Que Sami a humilié Hawa à l'antenne",
        decoy2="Que Yvette a interdit le rire",
        decoy3="Que le quiproquo a disparu",
        c2_aside="C'est de l'humour : on reconnaît le sauf-conduit de ceux qui n'ont pas à essuyer.",
        beats="Sami : loin de tout permettre, l'humour se juge à la cible. | Hawa n'a pas ri, et le non compte. | Aline explique le quiproquo sans recette. | Lila n'enregistrera pas la version trop dure. | Yvette rit du quiproquo, pas de la bouche trop seule. | Patrick refuse le succès comme preuve. | Mado note le ressort. | Marc : une scène comique C2 a une limite, ou n'est qu'un confort.",
    ),
    D(
        title="Le lin trop vite porté",
        lang="débat ; appropriation ; tendance trop vite portée",
        lang_type="cause",
        obj="Débattre d'un lin trop vite porté comme décor, sans procès d'intention plat.",
        theme="un lin de Rose trop vite copié",
        slogan="c'est un hommage",
        promise="dispense de demander à Rose",
        obstacle="une tendance qui vide un signe",
        who="Rose Iradukunda",
        concede="s'inspirer peut être juste",
        cond="l'on nomme, l'on demande, l'on ne vide pas",
        implicit="hommage trop vite dit évite le prix, la source, la permission",
        implicit_short="Éviter le prix, la source, la permission",
        reform="du fait que le lin circule, il ne s'ensuit pas qu'il soit un décor libre",
        proposal="un débat : inspiration, vide, demande, geste (créditer, payer, parfois ne pas porter)",
        datum="Rose a vu six copies trop nettes ; zéro demande ; un hommage trop tardif.",
        datum_short="Six copies, zéro demande, hommage trop tardif",
        stake="il s'agit d'un signe, pas d'une mode d'affiche",
        hearer="Léa Niyonzima",
        doc_a="les copies trop nettes",
        doc_b="la prise de parole de Rose",
        ce_doc="Un signe n'est pas un décor",
        w1="signe", d1="motif chargé, distinct d'un décor",
        w2="inspiration", d2="emprunt avoué, parfois juste",
        w3="permission", d3="demande à Rose, trop souvent sautée",
        w4="tendance", d4="mode qui peut vider un motif",
        sv=("demander", "demande"), nom="signe", nom2="inspiration",
        decoy1="Que Rose interdit toute inspiration",
        decoy2="Que Léa a vendu les copies",
        decoy3="Que l'hommage était daté avant les copies",
        c2_aside="C'est un hommage : on vérifiera s'il a traversé, par hasard, une caisse.",
        beats="Rose : du fait que le lin plaît, si bien que l'on copie, il ne s'ensuit pas un droit. | Léa ouvre le débat, pas le procès plat. | Aline exige la permission comme mot. | Karim parle de prix. | Sami avait porté trop vite ; il retire. | Lila n'adoucira pas. | Patrick refuse hommage comme sauf-conduit. | Marc : un débat C2 nomme le vide, pas seulement l'intention.",
    ),
    D(
        title="Récit interculturel",
        lang="récit détaillé au passé ; différences ; sans ethnologiser",
        lang_type="compte_rendu",
        obj="Raconter une expérience interculturelle au Seuil, détaillée, sans figer l'autre.",
        theme="les premiers mois d'Hawa au Pavillon",
        slogan="chez eux c'est comme ça",
        promise="fige Hawa en exemple",
        obstacle="un récit trop typique pour rester une vie",
        who="Hawa Diallo",
        concede="nommer des différences aide",
        cond="l'on n'en fasse pas une essence, ni une leçon de cour",
        implicit="chez eux c'est comme ça évite de dire chez nous aussi, et moi",
        implicit_short="Éviter le moi, figer le eux",
        reform="selon Hawa, la clé manquait ; d'après Dieudonné, le thé était trop tôt ; il ressort une vie, pas un type",
        proposal="un récit : dates, gestes, malentendus, corrections, zéro chez eux trop large",
        datum="Hawa a daté onze semaines ; trois malentendus ; deux corrections ; zéro essence.",
        datum_short="Onze semaines, trois malentendus, deux corrections",
        stake="il s'agit d'une personne, pas d'une vitrine culturelle",
        hearer="Dieudonné Hakizimana",
        doc_a="les notes trop typiques d'un voisin",
        doc_b="le récit d'Hawa",
        ce_doc="Une vie, pas un type",
        w1="malentendu", d1="écart de lecture, corrigeable",
        w2="essence", d2="figement, à refuser",
        w3="récit", d3="suite datée, détaillée",
        w4="correction", d4="geste qui défait le type",
        sv=("raconter", "raconte"), nom="malentendu", nom2="essence",
        decoy1="Que Hawa a figé Dieudonné",
        decoy2="Que le récit n'a pas de dates",
        decoy3="Que chez eux a été gardé comme titre",
        c2_aside="Chez eux c'est comme ça : on admirera la géographie, si commode, du eux.",
        beats="Hawa avait déjà posé la valise quand on lui a dit chez eux. | Dieudonné avait cru bien faire avec le thé trop tôt. | Il ressort deux corrections, pas une leçon. | Aline refuse l'ethnologie de banc. | Lila n'adoucira pas le eux. | Rose coud un ourlet trop large encore. | Patrick veut les onze semaines. | Marc : un récit C2 se juge à ce qu'il n'a pas figé.",
    ),
    D(
        title="Article implicite",
        lang="écrire en sous-entendu ; faits ; écart",
        lang_type="ironie",
        obj="Tenir l'article implicite jusqu'au bout, sans retomber dans le cri.",
        theme="la seconde version de l'article d'Hawa",
        slogan="il faut le dire clairement",
        promise="force le cri au nom de la clarté",
        obstacle="une clarté qui n'est qu'un slogan contraire",
        who="Aline Uwase",
        concede="la clarté est souvent juste",
        cond="l'on n'y perde l'écart qui faisait le travail",
        implicit="clairement veut parfois dire criez comme nous",
        implicit_short="Criez comme nous",
        reform="l'implicite C2 n'est pas un flou : c'est une composition de faits dont la conclusion se lit",
        proposal="garder l'article d'Hawa, justifier l'implicite, refuser le slogan contraire",
        datum="Aline a justifié l'écart ; Hawa a gardé le tarif ; zéro cri ajouté.",
        datum_short="Écart justifié, tarif gardé, zéro cri",
        stake="il s'agit d'une maîtrise de registre, pas d'un manque de courage",
        hearer="Hawa Diallo",
        doc_a="la demande de crier",
        doc_b="l'article gardé",
        ce_doc="La conclusion se lit",
        w1="composition", d1="arrangement des faits, lisible",
        w2="conclusion", d2="sens qui se lit, non crié",
        w3="clarté", d3="qualité, parfois un prétexte à crier",
        w4="courage", d4="distinct du volume de la voix",
        sv=("justifier", "justifie"), nom="composition", nom2="conclusion",
        decoy1="Que Aline a exigé le cri",
        decoy2="Que Hawa a ajouté un slogan contraire",
        decoy3="Que l'écart n'a pas été justifié",
        c2_aside="Il faut le dire clairement : on notera que clairement, ici, signifie souvent plus fort que moi.",
        beats="Aline : loin de manquer de courage, l'article se lisait. | Hawa garde le tarif. | Lila n'ajoute pas un cri. | Patrick relit l'écart. | Rose entend la porte. | Sami voulait plus net ; il relit, il cède. | Mado aime la composition. | Marc : un implicite C2 se justifie, il ne se dilue pas.",
    ),
    D(
        title="Débat de la cour",
        lang="débat contradictoire ; polémique ; synthèse",
        lang_type="reco",
        obj="Tenir un débat sur un sujet polémique de cour, avec règles C2.",
        theme="le débat sous le figuier, après les copies et le rire",
        slogan="que le meilleur gagne",
        promise="transforme le débat en combat",
        obstacle="une synthèse trop lisse après trop de bruit",
        who="Patrick Habimana",
        concede="un désaccord vif éclaire",
        cond="l'on impose concession, temps, zéro humiliation",
        implicit="le meilleur gagne est déjà une politique du micro",
        implicit_short="Une politique du micro",
        reform="il convient que l'on débatte, encore que l'on synthétise sans vainqueur",
        proposal="un débat : Rose, Sami, Hawa ; une synthèse de Patrick ; zéro roi",
        datum="Trois tours ; trois concessions ; une synthèse sans vainqueur.",
        datum_short="Trois tours, trois concessions, zéro vainqueur",
        stake="il s'agit d'une cour qui pense, pas d'une arène",
        hearer="Rose Iradukunda",
        doc_a="les prises de parole",
        doc_b="la synthèse de Patrick",
        ce_doc="Zéro roi au banc",
        w1="débat", d1="échange réglé, distinct d'un combat",
        w2="polémique", d2="sujet vif, à tenir",
        w3="règle", d3="temps, concession, non-humiliation",
        w4="arène", d4="forme à refuser sous le figuier",
        sv=("débattre", "débatte"), nom="débat", nom2="polémique",
        decoy1="Que Patrick a désigné un roi",
        decoy2="Que Rose a quitté sans concession",
        decoy3="Que Hawa a été humiliée",
        c2_aside="Que le meilleur gagne : on aimerait, par curiosité, le critère du meilleur.",
        beats="Patrick : il convient que l'on débatte, encore que l'on refuse l'arène. | Rose concède l'inspiration, pas le vide. | Sami concède la cible. | Hawa concède le mot généreux, pas le tarif. | Aline chronomètre. | Lila n'annonce pas de vainqueur. | Yvette écoute. | Marc : une synthèse C2 se juge à ce qu'elle n'a pas couronné.",
    ),
    # ----- C2-6 écologie rive -----
    D(
        title="La crue trop tôt",
        lang="hypothèses ; conséquences ; biodiversité de rive",
        lang_type="stats",
        obj="Faire des hypothèses sur une crue inventée et exposer des conséquences.",
        theme="la crue trop tôt de la rive",
        slogan="on verra bien",
        promise="reporte l'hypothèse à plus tard",
        obstacle="un plus tard qui n'a pas d'ombre à midi déjà trop blanc",
        who="Oscar Niyitegeka",
        concede="l'incertitude existe",
        cond="l'on n'en fasse pas une excuse pour ne pas exposer",
        implicit="on verra bien est la phrase de ceux dont le jardin n'est pas le premier mouillé",
        implicit_short="Le jardin n'est pas le premier mouillé",
        reform="s'il montait encore, le saule perdrait ; il se peut que l'on ait encore un relais",
        proposal="un compte-rendu oral : hypothèses, conséquences, un geste de rive",
        datum="Oscar a mesuré deux crues trop tôt ; trois jardins plus bas ; une ombre de moins.",
        datum_short="Deux crues trop tôt, trois jardins plus bas",
        stake="il s'agit d'une rive, pas d'un spectacle de fin du monde",
        hearer="Nina Kayitesi",
        doc_a="les mesures d'Oscar",
        doc_b="l'émission trop calme",
        ce_doc="Le jardin mouillé d'abord",
        w1="crue", d1="montée d'eau trop tôt, mesurée",
        w2="hypothèse", d2="si…, à exposer sans excuse",
        w3="biodiversité", d3="vies de la rive, pas un décor",
        w4="conséquence", d4="effet nommé, distinct d'un spectacle",
        sv=("exposer", "expose"), nom="crue", nom2="hypothèse",
        decoy1="Que Oscar a inventé les mesures",
        decoy2="Que Nina refuse toute hypothèse",
        decoy3="Que le saule a déjà disparu dans le rapport",
        c2_aside="On verra bien : futur d'une sérénité qui n'habite pas le premier jardin.",
        beats="Oscar : la part de terre trop tôt mouillée s'établit à ce que le saule sait déjà. | Nina dessine la conséquence. | Aline : l'hypothèse n'est pas une panique. | Félicie entend la terre. | Lila n'adoucira pas. | Karim chiffre sans sentence. | Joël demande le relais. | Marc : un compte-rendu climat de cour nomme le jardin, pas la planète abstraite.",
    ),
    D(
        title="Consensus trop commode",
        lang="stratégie argumentative ; répondre au déni poli",
        lang_type="ironie",
        obj="Rédiger un article qui répond aux doutes trop commodes, sans mépris.",
        theme="le déni poli sous le figuier",
        slogan="ce n'est pas si grave",
        promise="transforme la mesure en caprice d'Oscar",
        obstacle="un doute qui n'a pas visité la rive",
        who="Nina Kayitesi",
        concede="douter peut être une méthode",
        cond="l'on doute après la rive, pas à la place de la rive",
        implicit="pas si grave veut dire pas chez moi d'abord",
        implicit_short="Pas chez moi d'abord",
        reform="loin de convaincre par le cri, l'article aligne mesures, visite, conséquence",
        proposal="un article : doute légitime vs déni poli, preuves de cour, geste",
        datum="Nina a emmené trois sceptiques à la rive ; deux ont changé de phrase ; un a gardé pas si grave.",
        datum_short="Trois visites, deux phrases changées, un déni gardé",
        stake="il s'agit d'argumenter, pas d'humilier un doute",
        hearer="Karim Bamba",
        doc_a="les phrases trop calmes du banc",
        doc_b="l'article de Nina",
        ce_doc="Douter après la rive",
        w1="déni", d1="refus poli de voir, distinct du doute",
        w2="preuve", d2="mesure, visite, pas un cri",
        w3="sceptique", d3="personne à emmener, pas à humilier",
        w4="visite", d4="geste argumentatif, aller à la rive",
        sv=("répondre", "réponde"), nom="déni", nom2="preuve",
        decoy1="Que Nina a humilié Karim",
        decoy2="Que Oscar a refusé les visites",
        decoy3="Que les trois sceptiques n'ont pas vu la rive",
        c2_aside="Ce n'est pas si grave : on aimerait connaître l'adresse du pas si.",
        beats="Nina : loin de crier, j'aligne. | Karim avait dit pas si grave ; il a vu le jardin. | Oscar n'humilie pas. | Aline distingue doute et déni. | Lila lira l'article. | Félicie pose le bol après la visite. | Patrick veut la stratégie, pas l'insulte. | Marc : répondre au déni poli, c'est une rhétorique, pas une guerre.",
    ),
    D(
        title="Mesures pour la rive",
        lang="programme ; mesures politiques de cour ; il convient que",
        lang_type="reco",
        obj="Proposer des mesures écologiques de cour, datées, finançables.",
        theme="un programme trop lyrique de la rive",
        slogan="sauvons la planète",
        promise="efface le jardin d'Oscar sous un mot trop grand",
        obstacle="un programme sans destinataire ni fer",
        who="Solange Mukamana",
        concede="un mot large peut rassembler",
        cond="l'on date ensuite relais, compost, heures de camion, rampe de crue",
        implicit="sauvons la planète permet de ne pas nommer le jeudi et le fer",
        implicit_short="Ne pas nommer le jeudi et le fer",
        reform="il convient que l'on vote trois mesures, encore que l'on n'ait pas de planète à mettre dans une motion",
        proposal="un programme de cour : trois mesures, deux dates, un financement inventé du Bureau",
        datum="Solange a raturé planète ; gardé compost, relais, heures ; daté deux jeudis.",
        datum_short="Planète raturée, trois gestes, deux jeudis",
        stake="il s'agit d'une politique de rive, pas d'un hymne",
        hearer="Oscar Niyitegeka",
        doc_a="le brouillon trop lyrique",
        doc_b="le programme retenu",
        ce_doc="Trois mesures, pas un hymne",
        w1="mesure", d1="geste politique daté, finançable",
        w2="programme", d2="ensemble de mesures, relisible",
        w3="financement", d3="qui paie le fer, nommé",
        w4="compost", d4="geste de cour, trop concret pour l'hymne",
        sv=("voter", "vote"), nom="mesure", nom2="programme",
        decoy1="Que Solange a gardé sauvons la planète",
        decoy2="Que Oscar a refusé le compost",
        decoy3="Que le Bureau n'a pas de jeudi",
        c2_aside="Sauvons la planète : on vérifiera si le jeudi, plus modeste, a survécu à la phrase.",
        beats="Solange : il convient que l'on vote le compost, encore que l'hymne plaise. | Oscar entend son jardin. | Karim chiffre le fer. | Nina dessine la rampe de crue. | Aline rature planète. | Lila lira le programme. | Joël peut porter. | Marc : des mesures C2 ont un destinataire, ou ne sont qu'un nuage.",
    ),
    D(
        title="Un personnage de rive",
        lang="gestes quotidiens ; personnage de roman ; mode et éthique inventées",
        lang_type="hypotypose",
        obj="Encourager des gestes et étudier un personnage de roman qui défend une rive.",
        theme="un personnage trop exemplaire de Mado",
        slogan="soyez écolos",
        promise="transforme le geste en consigne de vitrine",
        obstacle="un personnage qui n'aurait plus de contradiction",
        who="Mado",
        concede="un exemple peut entraîner",
        cond="l'on laisse au personnage une fatigue, un doute, un bol trop vite",
        implicit="soyez écolos est une affiche, pas une fonction romanesque",
        implicit_short="Une affiche, pas une fonction romanesque",
        reform="on dirait qu'elle porterait encore, tout en doutant, et ce doute la rendrait croyable",
        proposal="un personnage : un geste, une contradiction, une rive, zéro sainteté",
        datum="Mado a laissé le bol trop vite ; gardé le compost ; refusé la sainte.",
        datum_short="Bol trop vite, compost gardé, sainte refusée",
        stake="il s'agit d'une fonction dans un roman, pas d'une mascotte",
        hearer="Félicie Ndayishimiye",
        doc_a="le brouillon trop saint",
        doc_b="le personnage retenu",
        ce_doc="Une contradiction, pas une sainte",
        w1="personnage", d1="être de roman, avec une fonction",
        w2="geste", d2="action quotidienne, distincte d'une affiche",
        w3="contradiction", d3="doute qui rend croyable",
        w4="éthique", d4="choix, pas une vitrine de mode",
        sv=("laisser", "laisse"), nom="personnage", nom2="geste",
        decoy1="Que Mado a écrit une sainte",
        decoy2="Que Félicie est réduite à une mascotte",
        decoy3="Que le compost a disparu",
        c2_aside="Soyez écolos : impératif d'une vitrine, rarement d'un roman.",
        beats="Mado : on dirait qu'elle douterait encore, et l'on la croirait. | Félicie refuse d'être une sainte. | Aline : la fonction d'un personnage n'est pas l'affiche. | Oscar veut de la terre sous l'ongle. | Lila n'adoucira pas. | Sami aime trop l'exemple ; on le complique. | Patrick relit la contradiction. | Marc : encourager un geste, au C2, ce n'est pas ordonner une vitrine.",
    ),
    D(
        title="Compte-rendu climat",
        lang="oral de synthèse ; conséquences ; sans spectacle",
        lang_type="compte_rendu",
        obj="Faire le compte-rendu oral des conséquences, à partir des séquences précédentes.",
        theme="ce que la cour peut déjà dire de la rive",
        slogan="il faut tout dire",
        promise="noye l'oreille sous trop de fin du monde",
        obstacle="un oral trop vaste pour une cour",
        who="Nina Kayitesi",
        concede="l'ampleur existe",
        cond="l'on tienne quatre minutes : crue, déni, mesures, geste",
        implicit="tout dire est souvent le contraire d'un compte-rendu",
        implicit_short="Le contraire d'un compte-rendu",
        reform="selon Oscar la crue ; d'après Nina le déni ; il ressort trois mesures et un jardin",
        proposal="un oral : quatre minutes, deux sources, une conséquence, un geste",
        datum="Nina a parlé 3 min 50 ; cité Oscar et Solange ; zéro fin du monde.",
        datum_short="Presque quatre minutes, deux sources, zéro fin du monde",
        stake="il s'agit d'informer une cour, pas de la sidérer",
        hearer="Oscar Niyitegeka",
        doc_a="les rapports de la rive",
        doc_b="l'oral de Nina",
        ce_doc="Quatre minutes, pas le monde entier",
        w1="ampleur", d1="échelle, à borner pour l'oreille",
        w2="sidération", d2="effet à refuser dans l'oral",
        w3="source", d3="Oscar, Solange, nommés",
        w4="geste", d4="suite concrète du compte-rendu",
        sv=("borner", "borne"), nom="ampleur", nom2="sidération",
        decoy1="Que Nina a parlé d'une fin du monde",
        decoy2="Que Oscar n'a pas été cité",
        decoy3="Que l'oral a duré une heure",
        c2_aside="Il faut tout dire : programme d'une honnêteté qui n'a pas d'oreille en face.",
        beats="Nina : selon Oscar, la crue trop tôt ; d'après Solange, trois mesures. | Il ressort un jardin, pas un spectacle. | Aline chronomètre. | Lila n'ajoute pas de musique. | Karim veut un chiffre, le reçoit. | Félicie écoute. | Joël entend le relais. | Marc : un compte-rendu C2 se juge à ce qu'il a su borner.",
    ),
    D(
        title="Programme et personnage",
        lang="synthèse finale ; programme ; roman",
        lang_type="reco",
        obj="Tenir ensemble un programme de rive et un personnage de roman, tâche finale C2-6.",
        theme="ce que le module laisse à la cour",
        slogan="on a fait le job",
        promise="clôt trop tôt ce qui n'a pas encore de jeudi",
        obstacle="une fierté d'avoir parlé, sans fer",
        who="Aline Uwase",
        concede="parler était nécessaire",
        cond="l'on date encore compost, relais, visite des sceptiques, rature de la sainte",
        implicit="on a fait le job est la phrase de ceux qui n'auront pas à essuyer la prochaine crue",
        implicit_short="Pas à essuyer la prochaine crue",
        reform="il s'agit de laisser un programme et un personnage, relisibles, imparfaits, datés",
        proposal="un texte final : quatre mesures, un personnage contradictoire, une revue sous le figuier",
        datum="Aline a daté la revue ; Mado a gardé le doute du personnage ; Oscar a le compost.",
        datum_short="Revue datée, doute gardé, compost nommé",
        stake="il s'agit que C2-6 n'ait pas été seulement un exercice de style",
        hearer="Mado",
        doc_a="le programme et le roman",
        doc_b="la clôture d'Aline",
        ce_doc="Daté, imparfait, relisible",
        w1="clôture", d1="fin de module, pas un job trop vite dit",
        w2="revue", d2="rendez-vous daté sous le figuier",
        w3="imparfait", d3="qualité d'un programme réel",
        w4="style", d4="exercice, insuffisant sans fer",
        sv=("laisser", "laisse"), nom="clôture", nom2="revue",
        decoy1="Que Aline a dit on a fait le job",
        decoy2="Que Mado a écrit une sainte à la fin",
        decoy3="Que Oscar n'a plus de compost",
        c2_aside="On a fait le job : on aimerait savoir qui, au juste, essuiera encore.",
        beats="Aline : il convient que l'on laisse une date, encore que l'on ait parlé longtemps. | Mado refuse la sainte. | Oscar tient le compost. | Nina tient la rampe de crue. | Solange tient les jeudis. | Lila ouvrira la revue. | Félicie pose le bol. | Marc : une tâche finale C2 se juge au fer qu'elle n'a pas oublié.",
    ),
]
