"""18 premières séquences C2 (modules 1–3)."""


def D(**k):
    return k


A = [
    D(
        title="Scène sous le figuier",
        lang="interprétation théâtrale ; sous-entendu ; point de vue critique",
        lang_type="ironie",
        obj="Analyser un extrait inventé et formuler un point de vue critique sans résumé plat.",
        theme="une scène trop calme à la Salle des Herbes",
        slogan="quelle émotion",
        promise="tienne lieu d'analyse",
        obstacle="un adjectif trop large pour une scène trop retenue",
        who="Mado",
        concede="l'émotion a sa place après le spectacle",
        cond="l'on dise d'abord ce que les silences ont fait",
        implicit="quelle émotion dispense souvent de voir que personne n'a osé bouger",
        implicit_short="Personne n'a osé bouger",
        reform="interpréter, c'est lire le non-jeu autant que le jeu",
        proposal="un échange d'impressions : deux lectures, une ironie, zéro adjectif orphelin",
        datum="Trois silences de huit secondes ; un rire trop tardif ; zéro larme, malgré l'adjectif trop large.",
        datum_short="Trois silences, un rire trop tardif, zéro larme",
        stake="il s'agit de juger une scène, pas de se juger ému",
        hearer="Sami",
        doc_a="l'extrait joué par Léa et Marc",
        doc_b="l'émission trop rapide de Lila",
        ce_doc="Le silence a joué aussi",
        w1="sous-entendu", d1="sens non dit, à justifier",
        w2="réplique", d2="parole de scène, parfois un piège",
        w3="critique", d3="point de vue argumenté, pas un adjectif",
        w4="silence", d4="matériau de la scène, pas un trou",
        sv=("interpréter", "interprète"), nom="sous-entendu", nom2="réplique",
        decoy1="Que Mado a trouvé la scène nulle",
        decoy2="Que Sami a pleuré pour la radio",
        decoy3="Que Léa a oublié son texte",
        c2_aside="Il ne s'agirait que d'un détail, bien sûr : personne n'a bougé, et l'on appelle cela du recueillement.",
        beats="Mado : loin d'emporter la salle, la scène a figé, ce qui n'est pas rien. | Fût-ce à voix basse, Léa a dit le contraire de son sourire. | Sami a ri trop tard : on aurait dit une consigne. | Aline : l'ironie n'est pas un rire, c'est un écart. | Patrick refuse le mot chef-d'œuvre. | Lila a trop vite conclu. | Rose a cousu dans le noir, mieux que le plateau. | Marc : un point de vue critique nomme le silence, pas seulement l'acteur.",
    ),
    D(
        title="Bonheur en série",
        lang="antiphrase ; industrialisation d'un sentiment ; prise de position",
        lang_type="ironie",
        obj="Prendre position sur un bonheur trop mesuré, trop vendu.",
        theme="le bonheur à l'heure dite sous le figuier",
        slogan="soyez heureux",
        promise="usine un sourire à dix-huit heures",
        obstacle="une joie qui ressemble à un planning",
        who="Sami",
        concede="un rituel de soirée peut apaiser",
        cond="l'on n'y lise pas une obligation de rayonner",
        implicit="soyez heureux arrive souvent quand on n'a plus le droit d'être las",
        implicit_short="Plus le droit d'être las",
        reform="si tant est que le bonheur s'industrialise, il se vendrait déjà au Marché des Lampions",
        proposal="une tribune : contre la joie obligatoire, pour les soirs sans score",
        datum="Sami a compté sept soirs « heureux » ; trois bâillements cachés ; zéro droit déclaré à la fatigue.",
        datum_short="Sept soirs heureux, trois bâillements, zéro droit à la fatigue",
        stake="il s'agit de pouvoir être las sans être coupable",
        hearer="Mado",
        doc_a="l'interview trop lisse d'un animateur inventé",
        doc_b="l'extrait de roman de Mado",
        ce_doc="La joie n'est pas un planning",
        w1="bonheur", d1="sentiment, pas une consigne",
        w2="rituel", d2="geste répété, parfois une cage",
        w3="fatigue", d3="droit, trop souvent une honte",
        w4="tribune", d4="texte de position, ironique s'il le faut",
        sv=("refuser", "refuse"), nom="bonheur", nom2="rituel",
        decoy1="Que Sami interdit les soirs",
        decoy2="Que Mado vend des sourires",
        decoy3="Que le figuier impose dix-huit heures",
        c2_aside="On nous dit que tout va bien, ce qui, en soi, devrait rassurer — et n'y parvient pas.",
        beats="Sami : il ne s'agirait que d'un détail, la fatigue, à entendre les animateurs trop nets. | Loin de rassurer, le sourire de dix-huit heures lasse. | Mado écrit la suite d'un extrait où le personnage rayonne trop pour être cru. | Aline : l'antiphrase se signale par un trop. | Félicie pose le bol sans « savoure ! ». | Lila n'ouvrira pas une émission de bonheur. | Yvette a le droit d'être lasse. | Marc : prendre position, c'est refuser l'usine à joie.",
    ),
    D(
        title="La bête et le banc",
        lang="argumentation juridique inventée ; encore que ; fût-ce",
        lang_type="reco",
        obj="Argumenter en faveur d'une médiation animale au Seuil, sans mièvrerie.",
        theme="le chien de Basile Habiyaremye",
        slogan="les bêtes n'ont pas leur place",
        promise="chasse le chien au nom de la dignité trop abstraite",
        obstacle="un banc trop raide pour qui tremble",
        who="Basile Habiyaremye",
        concede="un animal n'est pas un soignant",
        cond="l'on n'en fasse pas moins un médiateur possible, encadré",
        implicit="pas leur place veut souvent dire notre malaise d'abord",
        implicit_short="Notre malaise d'abord",
        reform="fût-ce un chien trop calme, la médiation peut ouvrir une parole que le jargon ferme",
        proposal="une lettre au Bureau des Escales : horaires, responsabilité, droit de dire non",
        datum="Basile a tenu trois heures de présence ; deux personnes ont parlé ; une a refusé, et c'est noté.",
        datum_short="Trois heures, deux paroles, un refus respecté",
        stake="il s'agit d'une justice douce, pas d'une mascotte",
        hearer="Inès Mukama",
        doc_a="la lettre de Basile",
        doc_b="la réserve d'Inès",
        ce_doc="Un chien n'est pas une mascotte",
        w1="médiation", d1="présence encadrée, distincte d'un soin miracle",
        w2="responsabilité", d2="qui répond du chien, des heures, du non",
        w3="refus", d3="droit, à noter, pas à contourner",
        w4="lettre", d4="demande argumentée au Bureau",
        sv=("autoriser", "autorise"), nom="médiation", nom2="responsabilité",
        decoy1="Que Basile promet une guérison",
        decoy2="Que Inès a chassé le chien",
        decoy3="Que le Bureau a déjà voté contre",
        c2_aside="On objectera que ce n'est pas sérieux. C'est souvent ainsi que l'on nomme ce qui dérange un protocole trop sûr.",
        beats="Basile : il convient que l'on autorise des heures, non un culte. | Inès objecte le risque, et c'est une objection digne. | Hawa a parlé au chien, puis à Inès, dans cet ordre. | Aline : encore que l'on discute le sérieux, le refus a été respecté. | Dieudonné peut tenir la laisse. | Lila n'en fera pas une émission trop tendre. | Patrick veut la responsabilité écrite. | Marc : une lettre de médiation n'est pas une fable.",
    ),
    D(
        title="Ailleurs possibles",
        lang="utopie / contrainte ; conditionnel ; rêve et réalité",
        lang_type="hypotypose",
        obj="Comprendre les enjeux d'une utopie de rive et en décrire une, sans naïveté.",
        theme="une utopie trop propre de Rukiri-Nord",
        slogan="demain on sera libres",
        promise="efface toute contrainte comme une honte",
        obstacle="une liberté qui n'aurait plus de relais ni de rampe",
        who="Nina Kayitesi",
        concede="rêver un ailleurs aide à juger l'ici",
        cond="l'on n'oublie pas qui porterait encore les lanternes",
        implicit="on sera libres dispense trop souvent de dire qui restera chargé",
        implicit_short="Qui restera chargé",
        reform="une utopie se juge à ses contraintes avouées, pas à ses nuages",
        proposal="décrire une rive possible : libertés, charges, refus du trop propre",
        datum="Nina a dessiné zéro tour ; trois relais ; une rampe ; un chien ; pas de midi sans ombre.",
        datum_short="Zéro tour, trois relais, une rampe, pas de midi sans ombre",
        stake="il s'agit de rêver sans renvoyer Joël dans l'angle mort",
        hearer="Joël Mugisha",
        doc_a="le calque utopique de Nina",
        doc_b="le conte philosophique de Mado",
        ce_doc="L'utopie avoue ses charges",
        w1="utopie", d1="ailleurs pensé, avec contraintes avouées",
        w2="contrainte", d2="limite nécessaire, pas seulement un mal",
        w3="liberté", d3="pouvoir, distinct d'un slogan",
        w4="charge", d4="travail qui reste, même demain",
        sv=("rêver", "rêve"), nom="utopie", nom2="contrainte",
        decoy1="Que Nina a dessiné une tour",
        decoy2="Que Joël est absent du calque",
        decoy3="Que Mado interdit les rêves",
        c2_aside="Demain on sera libres, répète-t-on, avec cette générosité particulière qui n'a pas à porter les lanternes.",
        beats="On dirait que la rivière n'aurait plus de crue, et Joël demande qui essuierait quand même. | Nina : une utopie trop propre est une oubliette. | Mado écrit un conte où la liberté a un relais, ou n'est pas. | Aline : le conditionnel peint, il n'absout pas. | Sami veut trop d'air ; Yvette trop d'ombre ; le calque les tient. | Lila lira l'utopie sans musique triomphale. | Basile y met le chien, encadré. | Marc : décrire une utopie, c'est avouer ses charges.",
    ),
    D(
        title="Lettre pour Basile",
        lang="lettre formelle ; concession ; hypotaxe longue",
        lang_type="reco",
        obj="Rédiger une lettre de médiation claire, relisible, sans mièvrerie.",
        theme="la lettre au Bureau des Escales",
        slogan="suivez votre cœur",
        promise="remplace le droit par l'émotion",
        obstacle="une lettre trop tendre pour être opposable",
        who="Inès Mukama",
        concede="le ton peut rester humain",
        cond="l'on y trouve horaires, responsabilités, droit de refus",
        implicit="suivez votre cœur évite d'écrire qui répond du chien s'il gronde",
        implicit_short="Qui répond du chien s'il gronde",
        reform="une lettre de C2 tient l'hypotaxe et le concret : fût-ce pour un chien",
        proposal="trois paragraphes : constat, cadre, demande datée",
        datum="Inès a raturé suivez votre cœur ; gardé le refus ; daté le jeudi.",
        datum_short="Cœur raturé, refus gardé, jeudi daté",
        stake="il s'agit qu'une lettre puisse se relire en cas de malentendu",
        hearer="Basile Habiyaremye",
        doc_a="le brouillon trop tendre",
        doc_b="la lettre retenue",
        ce_doc="Opposable, pas trop tendre",
        w1="cadre", d1="règles écrites de la médiation",
        w2="horaire", d2="heures nommées, pas un nuage",
        w3="opposable", d3="texte dont on peut se prévaloir",
        w4="paragraphe", d4="unité de la lettre formelle",
        sv=("dater", "date"), nom="cadre", nom2="horaire",
        decoy1="Que Inès a écrit suivez votre cœur",
        decoy2="Que Basile a refusé tout cadre",
        decoy3="Que le jeudi a disparu",
        c2_aside="Le cœur, en ces matières, a cet avantage : on ne peut pas le citer dans un compte-rendu.",
        beats="Inès : il convient que l'on date, encore que le ton reste humain. | Basile accepte le refus noté. | Aline allonge une phrase pour tenir concession et demande. | Karim veut un responsable nommé. | Lila ne lira pas la lettre à l'antenne sans accord. | Dieudonné peut tenir la laisse aux heures dites. | Patrick relit l'hypotaxe. | Marc : une lettre formelle n'est pas une froideur, c'est une hospitalité faite au malentendu futur.",
    ),
    D(
        title="Une utopie de rive",
        lang="écriture d'utopie ; charges avouées ; ironie douce",
        lang_type="hypotypose",
        obj="Décrire une utopie personnelle ancrée à Rukiri-Nord, C2, sans carte postale.",
        theme="la rive que l'on ose encore rêver",
        slogan="un monde parfait",
        promise="gommenait Joël, la rampe, la crue",
        obstacle="une perfection qui n'a plus besoin de personne",
        who="Mado",
        concede="le rêve a le droit d'être beau",
        cond="l'on y laisse sale un peu de terre sous l'ongle",
        implicit="parfait veut souvent dire sans visages trop réels",
        implicit_short="Sans visages trop réels",
        reform="on dirait une rive où l'on porterait encore, mais à plusieurs, et midi aurait une ombre",
        proposal="deux pages : ailleurs, charges, une ironie contre le trop propre",
        datum="Mado a laissé la terre ; Nina la rampe ; Joël un relais ; zéro monde parfait.",
        datum_short="Terre, rampe, relais, zéro monde parfait",
        stake="il s'agit de rêver une cour, pas une vitrine",
        hearer="Nina Kayitesi",
        doc_a="l'utopie de Mado",
        doc_b="les ratures de Nina",
        ce_doc="Un peu de terre sous l'ongle",
        w1="rive", d1="bord d'eau et de travail",
        w2="perfection", d2="idéal trop net, souvent une oubliette",
        w3="terre", d3="matière qui salit le rêve juste assez",
        w4="vitrine", d4="ailleurs trop exposé",
        sv=("salir", "salisse"), nom="rive", nom2="perfection",
        decoy1="Que Mado a écrit un monde parfait",
        decoy2="Que Nina a gommé Joël",
        decoy3="Que la terre est interdite au rêve",
        c2_aside="Un monde parfait, au Seuil, aurait cet inconvénient majeur : on n'y verrait plus qui essuie.",
        beats="Mado : on dirait que la crue viendrait encore, et que l'on saurait ensemble. | Nina refuse le trop propre. | Joël apparaît au troisième paragraphe, pas en note. | Aline : le conditionnel ici est une éthique. | Sami veut trop d'air ; on lui laisse, avec un relais. | Lila lira sans triomphe. | Félicie glisse un bol. | Marc : une utopie de rive se juge à ses ongles.",
    ),
]
