"""Séquences C2 modules 2–3 (langues, fil)."""


def D(**k):
    return k


B = [
    # ----- C2-2 langues -----
    D(
        title="Mots voyageurs",
        lang="emprunts ; représentation d'une langue ; sans purisme de boutique",
        lang_type="registre",
        obj="Réagir aux emprunts et définir notre représentation du français au Seuil.",
        theme="les mots voyageurs sous le figuier",
        slogan="il faut parler pur",
        promise="chasse les emprunts comme une honte",
        obstacle="une pureté qui n'a jamais existé sur la pente",
        who="Karim Bamba",
        concede="certains emprunts fatiguent l'oreille",
        cond="l'on n'en fasse pas une police des bouches",
        implicit="parler pur veut souvent dire parler comme ceux qui n'ont pas eu à emprunter pour vivre",
        implicit_short="Parler comme ceux qui n'ont pas eu à emprunter",
        reform="une langue se décrit par ses voyages, pas par une vitrine trop nette",
        proposal="un article : ce que nous empruntons, ce que nous refusons, sans tribunal",
        datum="Karim a listé huit emprunts utiles ; trois vaniteux ; zéro chasse aux bouches.",
        datum_short="Huit utiles, trois vaniteux, zéro chasse",
        stake="il s'agit de parler juste, pas de parler « propre »",
        hearer="Aline Uwase",
        doc_a="l'émission trop sévère",
        doc_b="l'article de Karim",
        ce_doc="Pas de police des bouches",
        w1="emprunt", d1="mot venu d'ailleurs, parfois utile",
        w2="purisme", d2="exigence trop nette, souvent une police",
        w3="représentation", d3="image que l'on se fait d'une langue",
        w4="oreille", d4="juge du trop, distincte d'un tribunal",
        sv=("emprunter", "emprunte"), nom="emprunt", nom2="purisme",
        decoy1="Que Karim chasse tous les emprunts",
        decoy2="Que Aline a interdit le kinyarwanda",
        decoy3="Que Lila ne parle qu'un français de vitrine",
        c2_aside="Il faut parler pur, répète-t-on, avec cette innocence des vitrines qui n'ont jamais eu à négocier un prix.",
        beats="Karim : encore que certains mots fatiguent, la chasse fatigue davantage. | Aline distingue registre et police. | Hawa emprunte, traduit, n'a pas à s'excuser. | Rose coud un mot d'ailleurs sur un lin d'ici. | Lila tend le micro aux bouches réelles. | Sami joue avec un emprunt ; Yvette sourit. | Patrick refuse la boutique du pur. | Marc : décrire une langue, c'est raconter ses voyages.",
    ),
    D(
        title="Politiques des voix",
        lang="lettre ouverte ; politiques linguistiques inventées ; francophonies",
        lang_type="reco",
        obj="Analyser et écrire une lettre ouverte sur les voix de la cour.",
        theme="qui a droit au micro de Radio Figuier",
        slogan="une seule langue officielle de cour",
        promise="réduit les voix à un usage trop étroit",
        obstacle="un micro qui n'ouvre qu'à une musique",
        who="Lila Sow",
        concede="un usage commun aide l'assemblée",
        cond="l'on n'en fasse pas l'effacement des autres souffles",
        implicit="une seule langue officielle veut souvent dire une seule oreille légitime",
        implicit_short="Une seule oreille légitime",
        reform="il convient que l'on ouvre le micro, encore que l'assemblée ait besoin d'un usage commun",
        proposal="une lettre ouverte : heures, langues, droit d'être compris sans être effacé",
        datum="Lila a ouvert trois heures mixtes ; deux refus poliment notés ; une lettre signée par onze voix.",
        datum_short="Trois heures mixtes, deux refus, onze signatures",
        stake="il s'agit de politiques de cour, pas d'un État fantasmé",
        hearer="Aline Uwase",
        doc_a="le projet trop étroit",
        doc_b="la lettre ouverte",
        ce_doc="Plus d'une oreille",
        w1="politique", d1="choix collectif sur les voix",
        w2="micro", d2="accès à Radio Figuier",
        w3="usage", d3="pratique commune, pas une chasse",
        w4="lettre", d4="forme pour dénoncer un étroit",
        sv=("ouvrir", "ouvre"), nom="politique", nom2="micro",
        decoy1="Que Lila a fermé le français",
        decoy2="Que Aline exige une seule bouche",
        decoy3="Que les onze signatures sont fausses",
        c2_aside="Une seule langue officielle de cour : formule propre, comme le sont souvent les exclusions.",
        beats="Lila : il convient que l'on ouvre, encore que l'on traduise. | Aline refuse l'effacement poli. | Hawa écrit une phrase de la lettre en deux souffles. | Karim veut être compris, pas réduit. | Solange signe. | Patrick relit le ton. | Sami lit trop vite ; on le ralentit. | Marc : une lettre ouverte nomme le micro, pas un empire.",
    ),
    D(
        title="Deux extraits deux oreilles",
        lang="registres sociaux ; comparer deux extraits ; choix d'écriture",
        lang_type="registre",
        obj="Comparer deux extraits de Mado et commenter les choix d'écriture.",
        theme="deux extraits trop éloignés pour n'être pas une politique",
        slogan="il faut écrire simple",
        promise="écrase l'hypotaxe au nom du peuple",
        obstacle="un simple qui n'est que du mépris déguisé",
        who="Mado",
        concede="la clarté est une politesse",
        cond="l'on n'interdise pas la phrase longue à celles qui la tiennent",
        implicit="écrire simple veut parfois dire n'embêtez pas ceux qui pourraient comprendre plus loin",
        implicit_short="N'embêtez pas ceux qui pourraient aller plus loin",
        reform="deux extraits : l'un coupe court, l'autre noue ; ni l'un ni l'autre n'est le peuple",
        proposal="un commentaire : destinataires, rythme, ce que chaque choix exclut",
        datum="Mado a posé deux pages ; Aline a noté six relatives ; Sami a préféré la courte, Yvette la nouée.",
        datum_short="Deux pages, six relatives, deux préférences",
        stake="il s'agit de voir le registre comme un choix, pas comme une nature",
        hearer="Aline Uwase",
        doc_a="l'extrait court",
        doc_b="l'extrait noué",
        ce_doc="Ni l'un ni l'autre n'est le peuple",
        w1="extrait", d1="morceau comparé, avec un rythme",
        w2="hypotaxe", d2="phrase nouée, légitime au C2",
        w3="clarté", d3="politesse, distincte d'un écrasement",
        w4="destinataire", d4="oreille visée par le choix",
        sv=("comparer", "compare"), nom="extrait", nom2="hypotaxe",
        decoy1="Que Mado méprise le peuple",
        decoy2="Que Aline interdit les phrases courtes",
        decoy3="Que Yvette n'a rien compris",
        c2_aside="Il faut écrire simple, dit-on, souvent de très loin des bouches que l'on prétend servir.",
        beats="Mado : loin de s'opposer, les deux extraits se jugent à ce qu'ils excluent. | Aline commente dont et auquel dans le noué. | Sami aime la coupe. | Yvette la noue. | Lila lira les deux, lentement. | Karim refuse le mot peuple collé. | Patrick : un choix d'écriture est une politique de l'oreille. | Marc : commenter, c'est dire pour qui l'on coupe, pour qui l'on noue.",
    ),
    D(
        title="Le souffle sous le figuier",
        lang="art oratoire ; rapport à l'oral ; souffle et hypotaxe",
        lang_type="registre",
        obj="Parler de notre rapport à l'oral et préparer un discours d'éloquence de cour.",
        theme="le concours d'éloquence sous le figuier",
        slogan="parlez avec le ventre",
        promise="remplace l'argument par le souffle trop sûr",
        obstacle="une éloquence qui n'écoute plus",
        who="Aline Uwase",
        concede="le souffle porte",
        cond="l'on n'y voie pas le droit de n'avoir rien à dire",
        implicit="parlez avec le ventre dispense trop souvent d'avoir un plan",
        implicit_short="Dispenser d'un plan",
        reform="l'art oratoire au Seuil, c'est un plan, un souffle, un silence, un destinataire",
        proposal="un discours de quatre minutes : thèse, concession, implicite, geste",
        datum="Aline a chronométré quatre minutes ; un silence ; zéro ventre sans plan.",
        datum_short="Quatre minutes, un silence, zéro ventre sans plan",
        stake="il s'agit de convaincre une cour, pas de la submerger",
        hearer="Lila Sow",
        doc_a="l'essai d'Aline sur l'oral",
        doc_b="le discours de Léa",
        ce_doc="Un plan, puis le souffle",
        w1="éloquence", d1="art de dire, avec un plan",
        w2="souffle", d2="rythme oral, pas un remplacement d'idée",
        w3="discours", d3="texte dit, destiné à une oreille",
        w4="destinataire", d4="cour visée, pas une foule abstraite",
        sv=("convaincre", "convainque"), nom="éloquence", nom2="souffle",
        decoy1="Que Aline a parlé sans plan",
        decoy2="Que Léa a crié",
        decoy3="Que Lila a coupé tous les silences",
        c2_aside="Parlez avec le ventre : conseil généreux, surtout quand le ventre n'a pas eu à lire le dossier.",
        beats="Aline : il convient que l'on convainque, encore que l'on respire. | Léa pose la concession avant le geste. | Sami a trop de souffle, pas assez de selon. | Yvette parle bas, et l'on entend. | Lila tend le micro sans le pousser. | Patrick refuse le ventre comme méthode. | Rose écoute les mains de l'orateur. | Marc : un concours d'éloquence au Seuil se juge à ce qu'il n'a pas écrasé.",
    ),
    D(
        title="Lettre ouverte aux voix",
        lang="dénoncer sans insulter ; hypotaxe ; nous demandons que",
        lang_type="reco",
        obj="Écrire une lettre ouverte qui dénonce un étroit linguistique de cour.",
        theme="la lettre sur le micro trop étroit",
        slogan="ce n'est pas le moment",
        promise="reporte l'ouverture des voix",
        obstacle="un plus tard qui n'arrive jamais pour certaines bouches",
        who="Hawa Diallo",
        concede="traduire prend du temps",
        cond="l'on date des heures mixtes, pas un nuage",
        implicit="ce n'est pas le moment veut dire votre bouche peut attendre",
        implicit_short="Votre bouche peut attendre",
        reform="nous demandons que le micro s'ouvre : le subjonctif ici est une politique",
        proposal="une lettre : constat, exemples, heures datées, signatures",
        datum="Hawa a cité deux émissions trop étroites ; proposé un jeudi mixte ; obtenu neuf signatures.",
        datum_short="Deux émissions citées, un jeudi mixte, neuf signatures",
        stake="il s'agit d'ouvrir des oreilles, pas de fermer le français",
        hearer="Lila Sow",
        doc_a="les deux émissions",
        doc_b="la lettre d'Hawa",
        ce_doc="Dater le jeudi mixte",
        w1="ouverture", d1="accès daté au micro",
        w2="traduction", d2="geste de cour, pas une excuse éternelle",
        w3="signature", d3="nom posé sous une demande",
        w4="émission", d4="heure d'antenne, trop parfois étroite",
        sv=("demander", "demande"), nom="ouverture", nom2="traduction",
        decoy1="Que Hawa a fermé Radio Figuier",
        decoy2="Que Lila a refusé toute mixité",
        decoy3="Que les neuf signatures sont un chœur unique",
        c2_aside="Ce n'est pas le moment : phrase de salon, d'une étonnante longévité.",
        beats="Hawa : nous demandons que le jeudi s'ouvre, encore que l'on traduise. | Lila entend, rature ce n'est pas le moment. | Aline corrige le subjonctif, garde la colère. | Karim signe. | Solange aussi. | Patrick veut des exemples, les obtient. | Sami lit trop vite la lettre ; on le reprend. | Marc : dénoncer un étroit, c'est dater une heure, pas crier une essence.",
    ),
    D(
        title="Concours d'éloquence",
        lang="prononcer un discours ; concession oratoire ; implicite assumé",
        lang_type="ironie",
        obj="Organiser et tenir un concours d'éloquence de cour, C2.",
        theme="le concours sous le figuier",
        slogan="le meilleur gagne",
        promise="transforme la parole en trophée",
        obstacle="un vainqueur trop sûr d'avoir eu raison tout seul",
        who="Léa Niyonzima",
        concede="un classement peut s'amuser",
        cond="l'on n'en fasse pas une humiliation",
        implicit="le meilleur gagne oublie trop vite qui n'a pas eu le micro assez tôt",
        implicit_short="Qui n'a pas eu le micro assez tôt",
        reform="loin de désigner un roi, le concours entraîne l'oreille à la concession",
        proposal="trois discours, un prix de la concession, zéro trophée trop lourd",
        datum="Trois discours ; un prix de la concession à Yvette ; zéro roi.",
        datum_short="Trois discours, un prix de concession, zéro roi",
        stake="il s'agit d'entraîner une cour, pas de couronner une bouche",
        hearer="Yvette",
        doc_a="les trois discours",
        doc_b="le palmarès d'Aline",
        ce_doc="Le prix de la concession",
        w1="concours", d1="exercice oratoire, pas un trône",
        w2="concession", d2="mouvement valorisé, plus qu'un trophée",
        w3="palmarès", d3="liste légère, sans humiliation",
        w4="oreille", d4="juge véritable du concours",
        sv=("entraîner", "entraîne"), nom="concours", nom2="concession",
        decoy1="Que Léa s'est couronnée",
        decoy2="Que Yvette a été humiliée",
        decoy3="Que Aline a interdit les concessions",
        c2_aside="Le meilleur gagne : on appréciera la modestie du critère.",
        beats="Léa : loin de gagner, j'ai concédé, et l'oreille a mieux tenu. | Yvette parle bas, emporte le prix de la concession. | Sami trop brillant, trop peu selon. | Aline refuse le roi. | Lila n'annonce pas un vainqueur, elle annonce trois écoutes. | Patrick sourit. | Rose écoute les mains. | Marc : un concours C2 se juge à ce qu'il a su ne pas écraser.",
    ),
    # ----- C2-3 fil / numérique -----
    D(
        title="Le fil et le Cahier",
        lang="accord, concession, désaccord ; fil et livres",
        lang_type="nom_conc",
        obj="Débattre de l'impact du fil sur la lecture, sans nostalgie de boutique.",
        theme="le fil et le Cahier du chemin",
        slogan="plus personne ne lit",
        promise="enterre le Cahier d'un tweet inventé trop court",
        obstacle="un résumé qui se prend pour le livre",
        who="Mado",
        concede="un fil peut porter un vers jusqu'à une oreille nouvelle",
        cond="l'on n'y voie pas le droit de ne plus ouvrir la page",
        implicit="plus personne ne lit est souvent le cri de ceux qui n'aiment qu'une façon de lire",
        implicit_short="N'aimer qu'une façon de lire",
        reform="certes le fil accélère, mais il n'a pas à remplacer la librairie immense du Cahier",
        proposal="un débat : trois positions, une concession obligatoire, un geste pour le Cahier",
        datum="Mado a vu vingt résumés trop courts ; trois lecteurs nouveaux ; zéro enterrement du Cahier.",
        datum_short="Vingt résumés trop courts, trois lecteurs nouveaux",
        stake="il s'agit de lire plus loin, pas de gagner contre un écran",
        hearer="Léa Niyonzima",
        doc_a="les résumés trop courts du fil",
        doc_b="la tribune de Mado",
        ce_doc="Le résumé n'est pas le livre",
        w1="fil", d1="flux inventé de la cour, trop rapide parfois",
        w2="résumé", d2="raccourci, distinct de l'œuvre",
        w3="lecture", d3="pratique longue, pas un score",
        w4="débat", d4="échange avec concession",
        sv=("lire", "lise"), nom="fil", nom2="résumé",
        decoy1="Que Mado a interdit le fil",
        decoy2="Que Léa n'ouvre plus le Cahier",
        decoy3="Que les trois lecteurs n'existent pas",
        c2_aside="Plus personne ne lit : constat commode, surtout à l'heure où l'on n'a pas ouvert le Cahier soi-même.",
        beats="Mado : encore que le fil porte un vers, il n'a pas à se prendre pour la page. | Léa refuse l'enterrement. | Sami résume trop court ; Aline allonge. | Karim cite un lecteur nouveau, sans triomphe. | Lila ouvrira un débat, pas un procès. | Patrick aime le papier et le fil, à deux vitesses. | Rose coud un signet. | Marc : débattre, c'est concéder, pas gagner contre un écran.",
    ),
    D(
        title="Deux tons un même soin",
        lang="adapter un discours ; conseils ; public visé",
        lang_type="conseil",
        obj="Adapter une campagne de prévention à un public de cour, sans panique.",
        theme="une campagne trop criée contre le fil",
        slogan="ouvrez l'œil",
        promise="remplace l'argument par la peur",
        obstacle="une affiche qui parle à tout le monde, donc à personne",
        who="Léa Niyonzima",
        concede="alerter peut être juste",
        cond="l'on nomme un public, un risque, un geste, pas une panique",
        implicit="une affiche pour tous évite souvent de parler aux plus exposés",
        implicit_short="Éviter les plus exposés",
        reform="on ferait mieux d'écrire deux versions : banc des jeunes, banc des anciens, même soin",
        proposal="une campagne : deux tons, un même fait, zéro slogan orphelin",
        datum="Léa a écrit deux versions ; Sami a corrigé la sienne ; Yvette la sienne ; zéro panique retenue.",
        datum_short="Deux versions, deux corrections, zéro panique",
        stake="il s'agit de prévenir, pas d'humilier l'usage",
        hearer="Sami",
        doc_a="l'affiche trop criée",
        doc_b="les deux versions de Léa",
        ce_doc="Deux tons, un même soin",
        w1="campagne", d1="discours préventif adapté",
        w2="public", d2="oreille visée, nommée",
        w3="risque", d3="danger précis, pas une panique",
        w4="version", d4="adaptation de ton, même fait",
        sv=("adapter", "adapte"), nom="campagne", nom2="public",
        decoy1="Que Léa a humilié Sami",
        decoy2="Que Yvette a refusé toute alerte",
        decoy3="Que la panique a été retenue",
        c2_aside="Ouvrez l'œil : on reconnaît la pédagogie de ceux qui n'ont pas le temps de nommer le risque.",
        beats="Léa : on ferait mieux d'écrire pour une oreille, non pour une foule. | Il vaudrait mieux que tu lises la version d'Yvette avant de crier. | Sami corrige le trop jeune trop faux. | Aline refuse le slogan orphelin. | Lila lira les deux tons. | Patrick veut le fait, pas la peur. | Rose affiche sans rouge trop violent. | Marc : adapter un discours, c'est respecter l'interlocuteur.",
    ),
    D(
        title="Le bruit sans source",
        lang="paradoxe ; bruit sans source ; loin de / bel et bien",
        lang_type="ironie",
        obj="Comprendre le processus d'un bruit sans source et écrire un paradoxe.",
        theme="un bruit trop vite vrai sous le figuier",
        slogan="c'est partout donc c'est vrai",
        promise="prend le torrent pour une preuve",
        obstacle="une rumeur qui n'a plus d'auteur",
        who="Marc Nkurunziza",
        concede="la répétition peut alerter",
        cond="l'on cherche encore qui a parlé d'abord",
        implicit="partout donc vrai est la grammaire du torrent, pas celle d'une enquête",
        implicit_short="La grammaire du torrent, pas de l'enquête",
        reform="loin de s'informer, on s'inonde ; bel et bien une source manquait",
        proposal="un article-paradoxe : plus l'on répète, moins l'on sait, sauf si l'on nomme",
        datum="Marc a retracé zéro source ; sept répétitions ; une démenti tardif de Lila.",
        datum_short="Zéro source, sept répétitions, un démenti tardif",
        stake="il s'agit de ralentir le bruit, pas d'interdire le fil",
        hearer="Lila Sow",
        doc_a="le torrent du fil",
        doc_b="l'article de Marc",
        ce_doc="Partout n'est pas une source",
        w1="rumeur", d1="bruit sans auteur, trop vite vrai",
        w2="source", d2="origine nommée d'une info",
        w3="paradoxe", d3="formule qui tient deux vérités contraires",
        w4="torrent", d4="flux trop fort pour une enquête",
        sv=("nommer", "nomme"), nom="rumeur", nom2="source",
        decoy1="Que Marc a inventé la rumeur",
        decoy2="Que Lila a refusé le démenti",
        decoy3="Que sept répétitions valent une enquête",
        c2_aside="C'est partout donc c'est vrai : on admirera la rigueur du donc.",
        beats="Marc : loin de s'informer, la cour s'inondait, et bel et bien personne n'avait de source. | Lila dément trop tard, ce qui est déjà une leçon. | Aline : le paradoxe n'est pas un jeu, c'est une alarme. | Léa retrace, échoue, le dit. | Karim refuse le partout. | Sami avait partagé trop vite ; il le dit aussi. | Patrick veut un article, pas une chasse. | Mado glisse une ironie, puis une méthode.",
    ),
    D(
        title="Demain trop net",
        lang="dystopie ; dérives ; point de vue d'un intervenant",
        lang_type="hypotypose",
        obj="Envisager des dérives technologiques inventées et écrire un extrait dystopique.",
        theme="une Rukiri-Nord trop écoutée",
        slogan="la machine nous aide",
        promise="remplace les relais humains par une voix trop sûre",
        obstacle="un demain où Joël n'aurait plus à porter, ni à décider",
        who="Léa Niyonzima",
        concede="un outil peut alléger",
        cond="l'on n'y lise pas la fin du relais",
        implicit="la machine nous aide cache trop souvent qui n'a plus le droit de dire non",
        implicit_short="Plus le droit de dire non",
        reform="on dirait que les lanternes marcheraient toutes seules, et l'on n'entendrait plus Joël",
        proposal="un extrait : demain trop net, une voix, un refus, une ombre",
        datum="Léa a écrit trois pages ; coupé le mot miracle ; gardé le refus de Joël.",
        datum_short="Trois pages, zéro miracle, un refus gardé",
        stake="il s'agit d'imaginer pour juger l'ici, pas pour se faire peur en vain",
        hearer="Joël Mugisha",
        doc_a="le podcast trop enthousiaste",
        doc_b="l'extrait de Léa",
        ce_doc="Les lanternes trop seules",
        w1="dystopie", d1="ailleurs sombre pour juger l'ici",
        w2="machine", d2="voix trop sûre, inventée",
        w3="refus", d3="droit qui doit rester humain",
        w4="extrait", d4="morceau d'écriture d'anticipation",
        sv=("imaginer", "imagine"), nom="dystopie", nom2="machine",
        decoy1="Que Léa promet la machine",
        decoy2="Que Joël a disparu de l'extrait",
        decoy3="Que le podcast était déjà une dystopie assumée",
        c2_aside="La machine nous aide : on notera le nous, d'une générosité qui n'a pas à porter.",
        beats="Léa : on dirait que midi n'aurait plus d'ombre, seulement un score. | Joël demande qui dirait non. | Aline : le conditionnel ici est une éthique. | Marc entend une antenne trop sûre. | Mado rature miracle. | Lila n'adoucira pas l'extrait. | Nina voit une tour. | Patrick : déduire un point de vue, c'est lire qui parle trop bien de l'aide.",
    ),
    D(
        title="Article-paradoxe",
        lang="exprimer un paradoxe ; concession ; reformulation",
        lang_type="ironie",
        obj="Rédiger un article qui tienne un paradoxe sans se perdre en effets.",
        theme="plus l'on sait, moins l'on vérifie",
        slogan="on est informés comme jamais",
        promise="prend le volume pour la connaissance",
        obstacle="une fierté d'être au courant qui n'a plus de source",
        who="Marc Nkurunziza",
        concede="l'accès aux voix s'est élargi",
        cond="l'on n'en conclue pas que l'on sait",
        implicit="informés comme jamais flatte pour ne plus avoir à vérifier",
        implicit_short="Ne plus avoir à vérifier",
        reform="plus le torrent grossit, plus la source se dérobe — sauf à la nommer",
        proposal="un article : paradoxe, exemple du Seuil, geste (nommer, ralentir)",
        datum="Marc a cité le torrent de la veille ; zéro source ; un geste : attendre Lila.",
        datum_short="Torrent de la veille, zéro source, attendre Lila",
        stake="il s'agit d'écrire juste, pas d'épater par le paradoxe",
        hearer="Lila Sow",
        doc_a="les bruits de la veille",
        doc_b="l'article de Marc",
        ce_doc="Le volume n'est pas le savoir",
        w1="paradoxe", d1="tension tenue entre deux vérités",
        w2="volume", d2="quantité d'infos, pas une preuve",
        w3="vérification", d3="geste, trop souvent sauté",
        w4="article", d4="texte argumenté, avec exemple de cour",
        sv=("vérifier", "vérifie"), nom="paradoxe", nom2="volume",
        decoy1="Que Marc se vante d'être au courant",
        decoy2="Que Lila a refusé d'être attendue",
        decoy3="Que le paradoxe est un jeu gratuit",
        c2_aside="On est informés comme jamais : la formule a cet avantage qu'elle n'exige aucune source.",
        beats="Marc : loin de savoir davantage, l'on vérifie moins, et c'est bel et bien un paradoxe de cour. | Lila accepte d'être le geste : attendre. | Aline refuse l'effet gratuit. | Léa fournit l'exemple. | Sami avait partagé ; il relit. | Patrick veut un titre sans cri. | Mado glisse une ironie, puis la rature trop facile. | Karim : un article C2 se juge à l'exemple, pas à la pirouette.",
    ),
    D(
        title="Extrait dystopique",
        lang="écriture d'anticipation ; voix ; ombre",
        lang_type="hypotypose",
        obj="Écrire un extrait de dystopie ancré à Rukiri-Nord, original, sans catalogue de gadgets.",
        theme="la cour trop écoutée de demain",
        slogan="tout sera plus simple",
        promise="efface les relais, les ratures, les non",
        obstacle="une simplicité où l'on n'aurait plus à se parler",
        who="Léa Niyonzima",
        concede="simplifier une corvée peut être juste",
        cond="l'on n'y perde la possibilité du refus",
        implicit="plus simple veut souvent dire plus seul, plus écouté, moins consulté",
        implicit_short="Plus seul, plus écouté, moins consulté",
        reform="midi n'aurait plus d'ombre ; Joël n'aurait plus de relais ; Lila n'aurait plus de rature",
        proposal="un extrait de quarante lignes : un midi, une voix trop sûre, un non",
        datum="Léa a gardé le non de Joël ; coupé trois gadgets ; laissé l'ombre.",
        datum_short="Un non, zéro gadget, une ombre",
        stake="il s'agit d'une écriture, pas d'un inventaire d'objets",
        hearer="Mado",
        doc_a="les ratures de Léa",
        doc_b="la lecture de Mado",
        ce_doc="Garder le non",
        w1="anticipation", d1="écriture du demain pour juger l'aujourd'hui",
        w2="gadget", d2="objet trop nommé, à éviter ici",
        w3="ombre", d3="abri, trop simple à effacer",
        w4="non", d4="refus humain, à garder dans l'extrait",
        sv=("écrire", "écrive"), nom="anticipation", nom2="ombre",
        decoy1="Que Léa a fait un catalogue d'objets",
        decoy2="Que Joël n'a pas de non dans l'extrait",
        decoy3="Que Mado a exigé plus simple comme consigne",
        c2_aside="Tout sera plus simple : promesse d'une voix qui n'a pas à demander la permission de couper l'ombre.",
        beats="Léa : on dirait que les lanternes avanceraient sans Joël, et que cela s'appellerait simple. | Mado exige le non. | Aline : pas de catalogue. | Marc entend trop de tout sera. | Lila n'adoucit pas. | Nina voit midi trop blanc. | Sami veut un objet ; on le refuse. | Patrick : un extrait se juge à l'ombre qu'il a gardée.",
    ),
]
