"""Séquences C1 7–36 (modules 2–6)."""


def D(**k):
    return k

REST = [
    # ----- C1-2 dossier 2 alimentation -----
    D(
        title="Le creux a un nom",
        lang="définir une notion ; cause émotionnelle ; nominalisation des sensations",
        lang_type="nom_conc",
        obj="Définir une faim qui n'est pas seulement le ventre et relier goûts et émotions.",
        theme="la faim qui n'est pas seulement le ventre",
        slogan="juste un creux",
        promise="réduise la faim à un oubli de bol",
        obstacle="une tristesse qui se déguise en appétit",
        who="Félicie Ndayishimiye",
        concede="un bol peut consoler un instant",
        cond="l'on n'appelle pas consolation ce qui empêche de parler",
        implicit="dire juste un creux permet souvent de ne pas nommer la solitude de midi",
        implicit_short="Ne pas nommer la solitude de midi",
        reform="la sensation n'est pas une faiblesse : c'est une information que le Seuil refuse trop vite",
        proposal="un recueil de plaisirs minuscules qui nomme l'émotion sans la moraliser",
        datum="Félicie a noté sept midis sans parole, trois bols trop vite, une infusion trop chaude pour cacher les yeux.",
        datum_short="Sept midis sans parole, trois bols trop vite",
        stake="il s'agit de pouvoir dire j'ai faim de présence, non seulement de sel",
        hearer="Aline Uwase",
        doc_a="l'article du Cahier du chemin",
        doc_b="le livre lu à voix haute par Mado",
        ce_doc="Le creux a un nom",
        w1="sensation", d1="information du corps, plus large que la faim",
        w2="appétit", d2="élan vers le bol, parfois vers autre chose",
        w3="solitude", d3="midi sans parole sous le figuier",
        w4="recueil", d4="ensemble de plaisirs minuscules, non une leçon",
        sv=("nommer", "nomme"), nom="sensation", nom2="appétit",
        decoy1="Que Félicie interdit les bols",
        decoy2="Que Mado refuse toute émotion à table",
        decoy3="Que le sel guérit la solitude",
        beats="Félicie pose le bol et attend : le creux n'est pas toujours le ventre. | Patrick croit qu'un proverbe suffit ; Aline demande une définition. | Hawa dit qu'elle mange plus vite quand Radio Figuier parle trop fort. | Karim refuse de chiffrer la tristesse, mais il note les midis silencieux. | Rose coud en goûtant : les mains savent ce que la bouche nie. | Sami rit trop fort ; Yvette entend la faim derrière le rire. | Oscar Niyitegeka apporte des feuilles : la terre aussi a des creux. | Lila : définir, ce n'est pas accuser, c'est donner un nom qui ne fasse pas honte.",
    ),
    D(
        title="Un tiers n'est pas une morale",
        lang="commenter des chiffres ; s'établir à ; alors que",
        lang_type="stats",
        obj="Restituer des données inventées du Filtre des Herbes sans en faire une sentence.",
        theme="les rations inventées du Filtre des Herbes",
        slogan="les chiffres parlent d'eux-mêmes",
        promise="close le débat par un pourcentage",
        obstacle="un rapport qui n'a pas goûté le bol",
        who="Karim Bamba",
        concede="un graphique peut alerter",
        cond="l'on dise qui a pesé, quand, et ce que le chiffre ne voit pas",
        implicit="les chiffres parlent d'eux-mêmes veut souvent dire ne me posez plus de questions",
        implicit_short="Ne plus poser de questions au rapport",
        reform="s'établir à un tiers n'est pas prouver une morale : c'est ouvrir une lecture",
        proposal="un article qui cite le Filtre, oppose alors que, et refuse la sentence",
        datum="Le Filtre annonce : près d'un bol sur trois trop salé, deux jardins moins arrosés, une file plus longue le jeudi.",
        datum_short="Un bol sur trois trop salé, file plus longue le jeudi",
        stake="il s'agit que la santé du Seuil ne soit pas un slogan chiffré",
        hearer="Inès Mukama",
        doc_a="le graphique du Filtre des Herbes",
        doc_b="l'entretien d'Oscar au Marché des Herbes",
        ce_doc="Un tiers n'est pas une morale",
        w1="statistique", d1="donnée chiffrée, pas une sentence",
        w2="ration", d2="part pesée, parfois injuste",
        w3="graphique", d3="image de nombres, muette sur le goût",
        w4="rapport", d4="texte d'enquête, à relire, non à adorer",
        sv=("peser", "pèse"), nom="statistique", nom2="ration",
        decoy1="Que le Filtre a menti pour vendre du sel",
        decoy2="Que Oscar refuse tout chiffre",
        decoy3="Que Inès a fermé l'infirmerie",
        beats="Karim lit le graphique sans sourire : un tiers n'est pas une foule, c'est une alerte. | Oscar dit que le jeudi, la terre a soif avant les étiquettes. | Inès objecte : le sel excessif n'explique pas tous les maux, il en éclaire certains. | Aline : alors que le pourcentage monte, le bol de Félicie, lui, se vide trop vite. | Léa demande qui a pesé, et à quelle heure d'ombre. | Marc refuse la formule les chiffres parlent : quelqu'un les a fait parler. | Lila cittera le Filtre et l'entretien, pas l'un contre l'autre comme une guerre. | Hawa : restituer, c'est garder le doute là où le rapport trop lisse le cache.",
    ),
    D(
        title="La terre n'est pas un caprice",
        lang="cause et conséquence avancées ; du fait que ; si bien que",
        lang_type="cause",
        obj="Analyser et commenter un fait de société : la colère de ceux qui font pousser.",
        theme="la colère des jardiniers de la rive",
        slogan="ils exagèrent",
        promise="réduise la colère à un caprice de saison",
        obstacle="un prix de la terre qui flambe sans que les mains soient payées",
        who="Oscar Niyitegeka",
        concede="le Marché des Lampions attire des regards",
        cond="l'on n'y voie pas le droit d'oublier qui a planté",
        implicit="ils exagèrent signifie souvent nous ne voulons pas entendre le prix réel",
        implicit_short="Refus d'entendre le prix réel",
        reform="un fait de société se commente : causes, conséquences, visages, pas un cri contre un cri",
        proposal="un exposé qui nomme Oscar, la file, le prix, et ce que la cour peut décider dès jeudi",
        datum="Oscar a perdu deux aides cette lune ; la file des Herbes s'allonge d'une heure ; le Lampions vend plus brillant.",
        datum_short="Deux aides de moins, file plus longue, Lampions plus brillant",
        stake="il s'agit que la rive reste une rive nourricière, non un décor",
        hearer="Karim Bamba",
        doc_a="le récit d'Oscar au Cahier des racines",
        doc_b="le reportage inventé de Lila au marché",
        ce_doc="La terre n'est pas un caprice",
        w1="colère", d1="signal politique, pas un caprice",
        w2="terre", d2="sol travaillé, plus cher que l'étiquette",
        w3="file", d3="attente visible d'une injustice",
        w4="exposé", d4="parole structurée sur un fait de société",
        sv=("écouter", "écoute"), nom="colère", nom2="terre",
        decoy1="Que Oscar veut fermer le figuier",
        decoy2="Que Lila a inventé la file",
        decoy3="Que le sel est la seule cause",
        beats="Oscar parle bas : la colère trop criée sert ceux qui n'écoutent que le volume. | Du fait que le prix flambe, les aides s'en vont, si bien que la rive maigrit. | Félicie entend la terre avant d'entendre le slogan. | Patrick veut un exposé, pas une bagarre de bancs. | Solange demande qui profite du brillant des Lampions. | Dieudonné réparerait les clôtures, pour autant qu'on cesse de les voler pour le décor. | Yvette : un fait de société a des visages, pas seulement des causes. | Marc : commenter, c'est refuser ils exagèrent comme seule analyse.",
    ),
    D(
        title="Choisir au marché",
        lang="conseil atténué ; on ferait mieux de ; il vaudrait mieux que",
        lang_type="conseil",
        obj="Conseiller des achats sans ordonner, et peser une application inventée.",
        theme="l'application inventée Fil-des-Herbes",
        slogan="mieux choisir",
        promise="remplace le goût par un score",
        obstacle="une étiquette qui parle plus fort que Félicie",
        who="Léa Niyonzima",
        concede="un avis chiffré peut alerter sur le sel",
        cond="l'on n'achète pas un score comme on achète un bol",
        implicit="mieux choisir veut souvent dire mieux obéir à un écran qu'à une file",
        implicit_short="Obéir à un écran plutôt qu'à une file",
        reform="l'outil peut être un avis ; il ne doit pas devenir une loi de marché",
        proposal="échanger avantages et limites du Fil-des-Herbes, puis garder l'étiquette lue deux fois",
        datum="Léa a comparé : trois scores verts, un bol trop cher, zéro mention des mains d'Oscar.",
        datum_short="Trois scores verts, zéro mention des mains",
        stake="il s'agit de choisir sans se laisser choisir par un slogan doux",
        hearer="Félicie Ndayishimiye",
        doc_a="la notice du Fil-des-Herbes",
        doc_b="l'émission de Lila au Marché des Herbes",
        ce_doc="Le score n'est pas le goût",
        w1="étiquette", d1="texte sur le bol, à lire deux fois",
        w2="score", d2="avis chiffré, pas une loi",
        w3="application", d3="outil inventé Fil-des-Herbes",
        w4="conseil", d4="recommandation atténuée, distincte d'un ordre",
        sv=("lire", "lises"), nom="étiquette", nom2="score",
        decoy1="Que Léa a écrit l'application",
        decoy2="Que Félicie refuse toute étiquette",
        decoy3="Que le score vert garantit Oscar",
        beats="Léa ouvre Fil-des-Herbes et rit : le bol d'Oscar n'a pas de page. | On ferait mieux de lire l'étiquette deux fois, dit Inès, non l'écran une fois. | Karim voit l'avantage : le sel apparaît. Il voit le piège : les mains disparaissent. | Rose : un conseil n'élève pas la voix. | Joël achète trop vite quand le score est vert ; Aline le ralentit. | Sami aime l'outil ; Yvette demande qui l'a payé. | Lila : présenter avantages et limites, ce n'est pas condamner l'outil, c'est refuser l'obéissance. | Marc : il vaudrait mieux que tu lises le bol avant le slogan.",
    ),
    D(
        title="Débat marketing",
        lang="certes… mais ; encore que ; avantages et inconvénients",
        lang_type="nom_conc",
        obj="Débattre du marketing du Marché des Lampions sans slogan contre slogan.",
        theme="le marketing du Marché des Lampions",
        slogan="le brillant rend heureux",
        promise="habille le sel d'un mot doux",
        obstacle="une affiche qui cache le prix des mains",
        who="Karim Bamba",
        concede="une belle enseigne peut aider à trouver le stand",
        cond="l'on n'y lise pas une promesse de santé",
        implicit="le brillant rend heureux sert à ne plus demander qui a planté",
        implicit_short="Ne plus demander qui a planté",
        reform="certes l'affiche attire, mais elle n'a pas le droit de se faire passer pour un soin",
        proposal="un débat : avantages d'une enseigne claire, inconvénients d'un bonheur collé au sel",
        datum="Lila a relevé cinq mots doux sur l'affiche, zéro nom de jardinier, un prix en petits caractères.",
        datum_short="Cinq mots doux, zéro jardinier, prix minuscule",
        stake="il s'agit que la publicité inventée n'emprunte pas la voix de l'infirmerie",
        hearer="Inès Mukama",
        doc_a="l'affiche du Marché des Lampions",
        doc_b="la chronique de Karim",
        ce_doc="Le mot doux n'est pas un soin",
        w1="affiche", d1="enseigne argumentée ou menteuse selon les mots",
        w2="marketing", d2="stratégie pour attirer, à discuter",
        w3="promesse", d3="engagement, trop souvent un éclat",
        w4="publicité", d4="discours d'attraction, distinct d'un soin",
        sv=("discuter", "discute"), nom="affiche", nom2="promesse",
        decoy1="Que Karim a dessiné l'affiche",
        decoy2="Que Inès vend du brillant",
        decoy3="Que le figuier sera une enseigne",
        beats="Karim : certes l'enseigne guide, mais elle n'a pas à guérir. | Inès refuse que le mot santé soit collé au sel brillant. | Félicie n'a pas besoin d'un mot doux pour savoir si le bol nourrit. | Oscar n'apparaît pas sur l'affiche : c'est déjà un argument. | Aline : encore que l'on discute le graphisme, le prix minuscule est une politique. | Léa propose un débat pour / contre, avec concession obligatoire. | Sami aime le brillant ; Yvette demande le coût. | Lila : Radio Figuier n'est pas une affiche, même quand elle parle des Lampions.",
    ),
    D(
        title="Huit notices sous le figuier",
        lang="écriture créative encadrée ; nominalisation des sensations",
        lang_type="hypotypose",
        obj="Composer un recueil de plaisirs minuscules ancré dans le Seuil, sans morale lourde.",
        theme="les plaisirs minuscules du figuier",
        slogan="il faut jouir",
        promise="transforme le plaisir en consigne",
        obstacle="une joie ordonnée comme un score",
        who="Mado",
        concede="écrire le plaisir peut le rendre partageable",
        cond="l'on n'en fasse pas une leçon de bien manger",
        implicit="il faut jouir ressemble trop à une affiche pour n'être pas un ordre déguisé",
        implicit_short="Un ordre déguisé en joie",
        reform="le minuscule ici, c'est ce qui n'a pas besoin d'affiche : l'ombre, le bol, la feuille",
        proposal="huit notices de plaisir, au conditionnel parfois, sans injonction",
        datum="Mado a écrit huit notices ; Lila n'en lira que cinq, les trois trop morales restent dans le tiroir.",
        datum_short="Huit notices, cinq lues, trois trop morales",
        stake="il s'agit de goûter sans se faire discipliner par un slogan de table",
        hearer="Félicie Ndayishimiye",
        doc_a="le recueil de Mado",
        doc_b="les notes de Félicie au bas des pages",
        ce_doc="Huit notices, pas une leçon",
        w1="plaisir", d1="expérience minuscule, non une consigne",
        w2="notice", d2="court texte de recueil",
        w3="ombre", d3="abri de midi, plaisir sans score",
        w4="feuille", d4="goût de la rive, plus discret que l'affiche",
        sv=("écrire", "écrive"), nom="plaisir", nom2="notice",
        decoy1="Que Mado a copié l'affiche des Lampions",
        decoy2="Que Félicie refuse tout plaisir",
        decoy3="Que Lila n'accepte que les leçons",
        beats="Mado : on dirait que l'ombre du figuier aurait un goût de thé trop infusé, et ce serait assez. | Félicie ajoute une notice : le bol chaud quand personne n'interroge. | Aline refuse l'impératif jouissez. | Patrick sourit d'une feuille croquée sans discours. | Rose coud un signet trop simple, exprès. | Sami veut une notice drôle ; Yvette en veut une lente. | Oscar glisse une terre sous l'ongle : cela aussi est un plaisir, dit-il, sans le vendre. | Lila lira sans musique : le minuscule n'a pas besoin d'orchestre.",
    ),
]
