export type Province = keyof typeof RWANDA_GEO;

export const PROVINCES = [
  'Kigali City',
  'Eastern Province',
  'Northern Province',
  'Southern Province',
  'Western Province',
] as const;

export const RWANDA_GEO = {
  'Kigali City': {
    Gasabo: {
      Bumbogo: ['Cyayi', 'Gacurabwenge', 'Gatebe', 'Gatonde', 'Kabuga', 'Kibaya', 'Kinyinya', 'Murambi'],
      Gatsata: ['Bibare', 'Gahanga', 'Gatsata', 'Kibagabaga', 'Nyarutarama'],
      Gikomero: ['Gikomero', 'Kabuga', 'Kagugu', 'Karuruma', 'Nyagasambu'],
      Gisozi: ['Bukure', 'Gisozi', 'Kacyiru', 'Karuruma', 'Kibagabaga', 'Kimihurura', 'Kinyinya', 'Nyarutarama'],
      Jabana: ['Gacuba', 'Jabana', 'Kagugu', 'Kanombe', 'Kibagabaga', 'Nyacyonga'],
      Jali: ['Gahengeri', 'Jali', 'Kabuga', 'Kabuye', 'Rusororo'],
      Kacyiru: ['Kamatamu', 'Kabibutare', 'Kibaza', 'Kigabiro', 'Nyarutarama'],
      Kimihurura: ['Gisimenti', 'Kamatamu', 'Kibaza', 'Kibagabaga', 'Kiyovu'],
      Kimironko: ['Bibare', 'Gikondo', 'Kibagabaga', 'Kimironko', 'Nyamirambo', 'Rugenge'],
      Kinyinya: ['Gahanga', 'Giticyinyoni', 'Kabuga', 'Kinyinya', 'Murama', 'Nyarutarama'],
      Ndera: ['Gahengeri', 'Kabuga', 'Karuruma', 'Ndera', 'Nyarutarama'],
      Nduba: ['Gasharu', 'Gatonde', 'Kabuga', 'Nduba', 'Rusororo'],
      Remera: ['Gisimenti', 'Kabeza', 'Kibagabaga', 'Nyarutarama', 'Remera'],
      Rusororo: ['Gahengeri', 'Jali', 'Kabuye', 'Rusororo', 'Rukiri'],
      Rutunga: ['Gacuba', 'Kabuga', 'Kiyovu', 'Rutunga'],
    },
    Kicukiro: {
      Gahanga: ['Bugesera', 'Gahanga', 'Kabuye', 'Kanombe', 'Nyagasambu'],
      Gatenga: ['Gatenga', 'Gikondo', 'Kagarama', 'Kanombe', 'Niboye'],
      Gikondo: ['Biryogo', 'Gikondo', 'Kicukiro', 'Niboye', 'Rwezamenyo'],
      Kagarama: ['Gahanga', 'Kagarama', 'Kanombe', 'Kicukiro', 'Kibiraro'],
      Kanombe: ['Gahanga', 'Kabuye', 'Kanombe', 'Kibiraro', 'Rusororo'],
      Kicukiro: ['Biryogo', 'Gikondo', 'Kicukiro', 'Niboye', 'Rugenge'],
      Kigarama: ['Gahanga', 'Kabuye', 'Kigarama', 'Niboye', 'Nyamirambo'],
      Masaka: ['Gahanga', 'Kanombe', 'Masaka', 'Nyagasambu', 'Nyamirambo'],
      Niboye: ['Gikondo', 'Kicukiro', 'Niboye', 'Rugenge', 'Rusororo'],
      Nyarugunga: ['Gahanga', 'Kabuye', 'Kanombe', 'Nyarugunga', 'Rusororo'],
    },
    Nyarugenge: {
      Gitega: ['Akabahizi', 'Gisozi', 'Gitega', 'Kamatamu', 'Kiyovu', 'Rugenge'],
      Kanyinya: ['Gikondo', 'Kanyinya', 'Kibagabaga', 'Kimisagara', 'Rugenge'],
      Kigali: ['Biryogo', 'Industrial', 'Kigali', 'Kimisagara', 'Nyabugogo'],
      Kimisagara: ['Biryogo', 'Industrial', 'Kimisagara', 'Nyabugogo', 'Rugenge'],
      Mageragere: ['Gikondo', 'Mageragere', 'Nyamirambo', 'Rugenge', 'Rwezamenyo'],
      Muhima: ['Biryogo', 'Industrial', 'Muhima', 'Nyabugogo', 'Rugenge'],
      Nyakabanda: ['Biryogo', 'Kimisagara', 'Nyabugogo', 'Nyakabanda', 'Rugenge'],
      Nyamirambo: ['Gikondo', 'Kimisagara', 'Nyamirambo', 'Rugenge', 'Rwezamenyo'],
      Nyarugenge: ['Biryogo', 'Industrial', 'Nyabugogo', 'Nyarugenge', 'Rugenge'],
      Rwezamenyo: ['Biryogo', 'Gikondo', 'Kimisagara', 'Rugenge', 'Rwezamenyo'],
    },
  },
  'Eastern Province': {
    Bugesera: {
      Gashora: ['Bihari', 'Gashora', 'Kamabuye', 'Mwendo', 'Nyamata'],
      Juru: ['Juru', 'Kabukuba', 'Kamabuye', 'Mwendo', 'Nyamata'],
      Kamabuye: ['Gashora', 'Kamabuye', 'Kibungo', 'Mwendo', 'Nyamata'],
      Mareba: ['Gashora', 'Mareba', 'Mwendo', 'Ntarama', 'Nyamata'],
      Mayange: ['Gashora', 'Juru', 'Mayange', 'Mwendo', 'Nyamata'],
      Musenyi: ['Bihari', 'Kamabuye', 'Kibungo', 'Musenyi', 'Nyamata'],
      Mwogo: ['Gashora', 'Mwogo', 'Ntarama', 'Nyamata', 'Ruhuha'],
      Ngeruka: ['Gashora', 'Mwendo', 'Ngeruka', 'Ntarama', 'Nyamata'],
      Ntarama: ['Gashora', 'Mwendo', 'Ntarama', 'Nyamata', 'Ruhuha'],
      Nyamata: ['Gashora', 'Mwendo', 'Ntarama', 'Nyamata', 'Ruhuha'],
      Nyarugenge: ['Gashora', 'Nyamata', 'Nyarugenge', 'Ruhuha', 'Shyara'],
      Rilima: ['Bihari', 'Juru', 'Mwendo', 'Ntarama', 'Rilima'],
      Ruhuha: ['Gashora', 'Mwendo', 'Ntarama', 'Nyamata', 'Ruhuha'],
      Rweru: ['Gashora', 'Mareba', 'Mwendo', 'Ntarama', 'Rweru'],
      Shyara: ['Gashora', 'Mwendo', 'Nyamata', 'Shyara', 'Ruhuha'],
    },
    Gatsibo: {
      Gasange: ['Gasange', 'Kabarore', 'Kiziguro', 'Murambi', 'Rugarama'],
      Gatsibo: ['Gatsibo', 'Kabarore', 'Kiziguro', 'Murambi', 'Rugarama'],
      Gitoki: ['Gitoki', 'Kabarore', 'Murambi', 'Rugarama', 'Rwimiyaga'],
      Kabarore: ['Gasange', 'Kabarore', 'Kiziguro', 'Murambi', 'Rugarama'],
      Kageyo: ['Kageyo', 'Kabarore', 'Kiziguro', 'Murambi', 'Rugarama'],
      Kiziguro: ['Kiziguro', 'Kabarore', 'Murambi', 'Rugarama', 'Rwimiyaga'],
      Muhura: ['Kabarore', 'Kiziguro', 'Muhura', 'Murambi', 'Rugarama'],
      Murambi: ['Kabarore', 'Kiziguro', 'Murambi', 'Rugarama', 'Rwimiyaga'],
      Ngarama: ['Kabarore', 'Kiziguro', 'Murambi', 'Ngarama', 'Rugarama'],
      Nyagihanga: ['Kabarore', 'Murambi', 'Nyagihanga', 'Rugarama', 'Rwimiyaga'],
      Remera: ['Kabarore', 'Kiziguro', 'Murambi', 'Remera', 'Rugarama'],
      Rugarama: ['Kabarore', 'Kiziguro', 'Murambi', 'Rugarama', 'Rwimiyaga'],
      Rwimbogo: ['Kabarore', 'Murambi', 'Rugarama', 'Rwimiyaga', 'Rwimbogo'],
    },
    Kayonza: {
      Gahini: ['Gahini', 'Kabare', 'Mukarange', 'Ndego', 'Ruramira'],
      Kabare: ['Gahini', 'Kabare', 'Mukarange', 'Ndego', 'Ruramira'],
      Kabarondo: ['Gahini', 'Kabarondo', 'Mukarange', 'Ndego', 'Ruramira'],
      Mukarange: ['Gahini', 'Kabare', 'Mukarange', 'Ndego', 'Ruramira'],
      Murama: ['Gahini', 'Kabare', 'Mukarange', 'Murama', 'Ruramira'],
      Murundi: ['Gahini', 'Kabare', 'Mukarange', 'Murundi', 'Ruramira'],
      Mwiri: ['Gahini', 'Kabare', 'Mukarange', 'Mwiri', 'Ruramira'],
      Ndego: ['Gahini', 'Kabare', 'Mukarange', 'Ndego', 'Ruramira'],
      Nyamirama: ['Gahini', 'Kabare', 'Mukarange', 'Nyamirama', 'Ruramira'],
      Rukara: ['Gahini', 'Kabare', 'Mukarange', 'Rukara', 'Ruramira'],
      Ruramira: ['Gahini', 'Kabare', 'Mukarange', 'Ndego', 'Ruramira'],
      Rwinkwavu: ['Gahini', 'Kabare', 'Mukarange', 'Ruramira', 'Rwinkwavu'],
    },
    Kirehe: {
      Gahara: ['Gahara', 'Kibungo', 'Kirehe', 'Mpanga', 'Nasho'],
      Gatore: ['Gahara', 'Gatore', 'Kirehe', 'Mpanga', 'Nasho'],
      Kigarama: ['Gahara', 'Kigarama', 'Kirehe', 'Mpanga', 'Nasho'],
      Kigina: ['Gahara', 'Kigina', 'Kirehe', 'Mpanga', 'Nasho'],
      Kirehe: ['Gahara', 'Kibungo', 'Kirehe', 'Mpanga', 'Nasho'],
      Mahama: ['Gahara', 'Kirehe', 'Mahama', 'Mpanga', 'Nasho'],
      Mpanga: ['Gahara', 'Kibungo', 'Kirehe', 'Mpanga', 'Nasho'],
      Musaza: ['Gahara', 'Kirehe', 'Mpanga', 'Musaza', 'Nasho'],
      Mushikiri: ['Gahara', 'Kirehe', 'Mpanga', 'Mushikiri', 'Nasho'],
      Nasho: ['Gahara', 'Kirehe', 'Mpanga', 'Nasho', 'Nyamugali'],
      Nyamugali: ['Gahara', 'Kirehe', 'Mpanga', 'Nasho', 'Nyamugali'],
      Nyarubuye: ['Gahara', 'Kirehe', 'Mpanga', 'Nasho', 'Nyarubuye'],
    },
    Ngoma: {
      Gashanda: ['Gashanda', 'Kibungo', 'Mugesera', 'Murama', 'Zaza'],
      Jarama: ['Gashanda', 'Jarama', 'Kibungo', 'Mugesera', 'Zaza'],
      Karembo: ['Gashanda', 'Karembo', 'Kibungo', 'Mugesera', 'Zaza'],
      Kazo: ['Gashanda', 'Kazo', 'Kibungo', 'Mugesera', 'Zaza'],
      Kibungo: ['Gashanda', 'Kibungo', 'Mugesera', 'Murama', 'Zaza'],
      Mugesera: ['Gashanda', 'Kibungo', 'Mugesera', 'Murama', 'Zaza'],
      Murama: ['Gashanda', 'Kibungo', 'Mugesera', 'Murama', 'Zaza'],
      Mutenderi: ['Gashanda', 'Kibungo', 'Mugesera', 'Mutenderi', 'Zaza'],
      Remera: ['Gashanda', 'Kibungo', 'Mugesera', 'Remera', 'Zaza'],
      Rukira: ['Gashanda', 'Kibungo', 'Mugesera', 'Rukira', 'Zaza'],
      Rukumberi: ['Gashanda', 'Kibungo', 'Mugesera', 'Rukumberi', 'Zaza'],
      Sake: ['Gashanda', 'Kibungo', 'Mugesera', 'Sake', 'Zaza'],
      Zaza: ['Gashanda', 'Kibungo', 'Mugesera', 'Murama', 'Zaza'],
    },
    Nyagatare: {
      Gatunda: ['Gatunda', 'Karama', 'Matimba', 'Nyagatare', 'Rwempasha'],
      Gyumba: ['Gatunda', 'Gyumba', 'Matimba', 'Nyagatare', 'Rwempasha'],
      Karama: ['Gatunda', 'Karama', 'Matimba', 'Nyagatare', 'Rwempasha'],
      Karangazi: ['Gatunda', 'Karangazi', 'Matimba', 'Nyagatare', 'Rwempasha'],
      Katabagemu: ['Gatunda', 'Katabagemu', 'Matimba', 'Nyagatare', 'Rwempasha'],
      Kiyombe: ['Gatunda', 'Karama', 'Kiyombe', 'Nyagatare', 'Rwempasha'],
      Matimba: ['Gatunda', 'Karama', 'Matimba', 'Nyagatare', 'Rwempasha'],
      Mimuli: ['Gatunda', 'Karama', 'Matimba', 'Mimuli', 'Rwempasha'],
      Mukama: ['Gatunda', 'Karama', 'Matimba', 'Mukama', 'Rwempasha'],
      Musheli: ['Gatunda', 'Karama', 'Matimba', 'Musheli', 'Rwempasha'],
      Nyagatare: ['Gatunda', 'Karama', 'Matimba', 'Nyagatare', 'Rwempasha'],
      Rukomo: ['Gatunda', 'Karama', 'Matimba', 'Rukomo', 'Rwempasha'],
      Rwempasha: ['Gatunda', 'Karama', 'Matimba', 'Nyagatare', 'Rwempasha'],
      Rwimiyaga: ['Gatunda', 'Karama', 'Matimba', 'Rwempasha', 'Rwimiyaga'],
      Tabagwe: ['Gatunda', 'Karama', 'Matimba', 'Rwempasha', 'Tabagwe'],
    },
    Rwamagana: {
      Fumbwe: ['Fumbwe', 'Karenge', 'Kigabiro', 'Munyaga', 'Rwamagana'],
      Gahengeri: ['Fumbwe', 'Gahengeri', 'Kigabiro', 'Munyaga', 'Rwamagana'],
      Gishari: ['Fumbwe', 'Gishari', 'Kigabiro', 'Munyaga', 'Rwamagana'],
      Karenge: ['Fumbwe', 'Karenge', 'Kigabiro', 'Munyaga', 'Rwamagana'],
      Kigabiro: ['Fumbwe', 'Karenge', 'Kigabiro', 'Munyaga', 'Rwamagana'],
      Muhazi: ['Fumbwe', 'Karenge', 'Kigabiro', 'Muhazi', 'Rwamagana'],
      Munyaga: ['Fumbwe', 'Karenge', 'Kigabiro', 'Munyaga', 'Rwamagana'],
      Munyiginya: ['Fumbwe', 'Karenge', 'Kigabiro', 'Munyiginya', 'Rwamagana'],
      Musha: ['Fumbwe', 'Karenge', 'Kigabiro', 'Musha', 'Rwamagana'],
      Muyumbu: ['Fumbwe', 'Karenge', 'Kigabiro', 'Muyumbu', 'Rwamagana'],
      Mwulire: ['Fumbwe', 'Karenge', 'Kigabiro', 'Mwulire', 'Rwamagana'],
      Nyakariro: ['Fumbwe', 'Karenge', 'Kigabiro', 'Nyakariro', 'Rwamagana'],
      Nzige: ['Fumbwe', 'Karenge', 'Kigabiro', 'Nzige', 'Rwamagana'],
      Rubona: ['Fumbwe', 'Karenge', 'Kigabiro', 'Rubona', 'Rwamagana'],
    },
  },
  'Northern Province': {
    Burera: {
      Bungwe: ['Bungwe', 'Cyanika', 'Gahunga', 'Gatebe', 'Ruhunde'],
      Butaro: ['Butaro', 'Cyanika', 'Gahunga', 'Gatebe', 'Ruhunde'],
      Cyanika: ['Bungwe', 'Cyanika', 'Gahunga', 'Gatebe', 'Ruhunde'],
      Cyeru: ['Bungwe', 'Cyeru', 'Gahunga', 'Gatebe', 'Ruhunde'],
      Gahunga: ['Bungwe', 'Cyanika', 'Gahunga', 'Gatebe', 'Ruhunde'],
      Gatebe: ['Bungwe', 'Cyanika', 'Gahunga', 'Gatebe', 'Ruhunde'],
      Gitovu: ['Bungwe', 'Cyanika', 'Gahunga', 'Gitovu', 'Ruhunde'],
      Kagogo: ['Bungwe', 'Cyanika', 'Gahunga', 'Kagogo', 'Ruhunde'],
      Kinoni: ['Bungwe', 'Cyanika', 'Gahunga', 'Kinoni', 'Ruhunde'],
      Kinyababa: ['Bungwe', 'Cyanika', 'Gahunga', 'Kinyababa', 'Ruhunde'],
      Kivuye: ['Bungwe', 'Cyanika', 'Gahunga', 'Kivuye', 'Ruhunde'],
      Nemba: ['Bungwe', 'Cyanika', 'Gahunga', 'Nemba', 'Ruhunde'],
      Rugarama: ['Bungwe', 'Cyanika', 'Gahunga', 'Ruhunde', 'Rugarama'],
      Ruhunde: ['Bungwe', 'Cyanika', 'Gahunga', 'Gatebe', 'Ruhunde'],
      Rusarabuye: ['Bungwe', 'Cyanika', 'Gahunga', 'Ruhunde', 'Rusarabuye'],
      Rwerere: ['Bungwe', 'Cyanika', 'Gahunga', 'Ruhunde', 'Rwerere'],
    },
    Gakenke: {
      Busengo: ['Busengo', 'Coko', 'Gakenke', 'Janja', 'Kamubuga'],
      Coko: ['Busengo', 'Coko', 'Gakenke', 'Janja', 'Kamubuga'],
      Cyabingo: ['Busengo', 'Coko', 'Cyabingo', 'Janja', 'Kamubuga'],
      Gakenke: ['Busengo', 'Coko', 'Gakenke', 'Janja', 'Kamubuga'],
      Gashenyi: ['Busengo', 'Coko', 'Gashenyi', 'Janja', 'Kamubuga'],
      Janja: ['Busengo', 'Coko', 'Gakenke', 'Janja', 'Kamubuga'],
      Kamubuga: ['Busengo', 'Coko', 'Gakenke', 'Janja', 'Kamubuga'],
      Karambo: ['Busengo', 'Coko', 'Janja', 'Kamubuga', 'Karambo'],
      Kivuruga: ['Busengo', 'Coko', 'Janja', 'Kamubuga', 'Kivuruga'],
      Mataba: ['Busengo', 'Coko', 'Janja', 'Kamubuga', 'Mataba'],
      Minazi: ['Busengo', 'Coko', 'Janja', 'Kamubuga', 'Minazi'],
      Muhondo: ['Busengo', 'Coko', 'Janja', 'Kamubuga', 'Muhondo'],
      Muyongwe: ['Busengo', 'Coko', 'Janja', 'Kamubuga', 'Muyongwe'],
      Muzo: ['Busengo', 'Coko', 'Janja', 'Kamubuga', 'Muzo'],
      Nkangama: ['Busengo', 'Coko', 'Janja', 'Kamubuga', 'Nkangama'],
      Rushashi: ['Busengo', 'Coko', 'Janja', 'Kamubuga', 'Rushashi'],
    },
    Gicumbi: {
      Bukure: ['Bukure', 'Bwisige', 'Byumba', 'Cyumba', 'Kaniga'],
      Bungwe: ['Bukure', 'Bungwe', 'Byumba', 'Cyumba', 'Kaniga'],
      Bwisige: ['Bukure', 'Bwisige', 'Byumba', 'Cyumba', 'Kaniga'],
      Byumba: ['Bukure', 'Bwisige', 'Byumba', 'Cyumba', 'Kaniga'],
      Cyumba: ['Bukure', 'Bwisige', 'Byumba', 'Cyumba', 'Kaniga'],
      Giti: ['Bukure', 'Bwisige', 'Byumba', 'Giti', 'Kaniga'],
      Kageyo: ['Bukure', 'Bwisige', 'Byumba', 'Kageyo', 'Kaniga'],
      Kaniga: ['Bukure', 'Bwisige', 'Byumba', 'Cyumba', 'Kaniga'],
      Manyagiro: ['Bukure', 'Bwisige', 'Byumba', 'Kaniga', 'Manyagiro'],
      Miyove: ['Bukure', 'Bwisige', 'Byumba', 'Kaniga', 'Miyove'],
      Mukarange: ['Bukure', 'Bwisige', 'Byumba', 'Kaniga', 'Mukarange'],
      Muko: ['Bukure', 'Bwisige', 'Byumba', 'Kaniga', 'Muko'],
      Mutete: ['Bukure', 'Bwisige', 'Byumba', 'Kaniga', 'Mutete'],
      Nyamiyaga: ['Bukure', 'Bwisige', 'Byumba', 'Kaniga', 'Nyamiyaga'],
      Nyaruhengeri: ['Bukure', 'Bwisige', 'Byumba', 'Kaniga', 'Nyaruhengeri'],
      Rubaya: ['Bukure', 'Bwisige', 'Byumba', 'Kaniga', 'Rubaya'],
      Rukomo: ['Bukure', 'Bwisige', 'Byumba', 'Kaniga', 'Rukomo'],
      Rushaki: ['Bukure', 'Bwisige', 'Byumba', 'Kaniga', 'Rushaki'],
      Rutare: ['Bukure', 'Bwisige', 'Byumba', 'Kaniga', 'Rutare'],
      Ruvune: ['Bukure', 'Bwisige', 'Byumba', 'Kaniga', 'Ruvune'],
      Rwamiko: ['Bukure', 'Bwisige', 'Byumba', 'Kaniga', 'Rwamiko'],
      Shinya: ['Bukure', 'Bwisige', 'Byumba', 'Kaniga', 'Shinya'],
    },
    Musanze: {
      Busogo: ['Busogo', 'Cyuve', 'Gacaca', 'Gataraga', 'Kinigi'],
      Cyuve: ['Busogo', 'Cyuve', 'Gacaca', 'Gataraga', 'Kinigi'],
      Gacaca: ['Busogo', 'Cyuve', 'Gacaca', 'Gataraga', 'Kinigi'],
      Gataraga: ['Busogo', 'Cyuve', 'Gacaca', 'Gataraga', 'Kinigi'],
      Kimonyi: ['Busogo', 'Cyuve', 'Gacaca', 'Kimonyi', 'Kinigi'],
      Kinigi: ['Busogo', 'Cyuve', 'Gacaca', 'Gataraga', 'Kinigi'],
      Muhoza: ['Busogo', 'Cyuve', 'Gacaca', 'Kinigi', 'Muhoza'],
      Muko: ['Busogo', 'Cyuve', 'Gacaca', 'Kinigi', 'Muko'],
      Musanze: ['Busogo', 'Cyuve', 'Gacaca', 'Kinigi', 'Musanze'],
      Nkotsi: ['Busogo', 'Cyuve', 'Gacaca', 'Kinigi', 'Nkotsi'],
      Nyange: ['Busogo', 'Cyuve', 'Gacaca', 'Kinigi', 'Nyange'],
      Remera: ['Busogo', 'Cyuve', 'Gacaca', 'Kinigi', 'Remera'],
      Rwaza: ['Busogo', 'Cyuve', 'Gacaca', 'Kinigi', 'Rwaza'],
      Shingiro: ['Busogo', 'Cyuve', 'Gacaca', 'Kinigi', 'Shingiro'],
      Undugu: ['Busogo', 'Cyuve', 'Gacaca', 'Kinigi', 'Undugu'],
    },
    Rulindo: {
      Base: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Cyinzuzi'],
      Burega: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Cyinzuzi'],
      Bushoki: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Cyinzuzi'],
      Buyoga: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Cyinzuzi'],
      Cyinzuzi: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Cyinzuzi'],
      Cyungo: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Cyungo'],
      Kinihira: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Kinihira'],
      Kisaro: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Kisaro'],
      Masoro: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Masoro'],
      Mbogo: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Mbogo'],
      Murambi: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Murambi'],
      Ngoma: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Ngoma'],
      Ntarabana: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Ntarabana'],
      Rukozo: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Rukozo'],
      Rusiga: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Rusiga'],
      Shyorongi: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Shyorongi'],
      Tumba: ['Base', 'Burega', 'Bushoki', 'Buyoga', 'Tumba'],
    },
  },
  'Southern Province': {
    Gisagara: {
      Gikonko: ['Gikonko', 'Gishubi', 'Kansi', 'Kibirizi', 'Mugombwa'],
      Gishubi: ['Gikonko', 'Gishubi', 'Kansi', 'Kibirizi', 'Mugombwa'],
      Kansi: ['Gikonko', 'Gishubi', 'Kansi', 'Kibirizi', 'Mugombwa'],
      Kibirizi: ['Gikonko', 'Gishubi', 'Kansi', 'Kibirizi', 'Mugombwa'],
      Kigembe: ['Gikonko', 'Gishubi', 'Kansi', 'Kigembe', 'Mugombwa'],
      Mamba: ['Gikonko', 'Gishubi', 'Kansi', 'Mamba', 'Mugombwa'],
      Mugombwa: ['Gikonko', 'Gishubi', 'Kansi', 'Kibirizi', 'Mugombwa'],
      Mukindo: ['Gikonko', 'Gishubi', 'Kansi', 'Mugombwa', 'Mukindo'],
      Musha: ['Gikonko', 'Gishubi', 'Kansi', 'Mugombwa', 'Musha'],
      Ndora: ['Gikonko', 'Gishubi', 'Kansi', 'Mugombwa', 'Ndora'],
      Nyanza: ['Gikonko', 'Gishubi', 'Kansi', 'Mugombwa', 'Nyanza'],
      Save: ['Gikonko', 'Gishubi', 'Kansi', 'Mugombwa', 'Save'],
    },
    Huye: {
      Gishamvu: ['Gishamvu', 'Karama', 'Kigoma', 'Kinazi', 'Maraba'],
      Huye: ['Gishamvu', 'Huye', 'Kigoma', 'Kinazi', 'Maraba'],
      Karama: ['Gishamvu', 'Karama', 'Kigoma', 'Kinazi', 'Maraba'],
      Kigoma: ['Gishamvu', 'Karama', 'Kigoma', 'Kinazi', 'Maraba'],
      Kinazi: ['Gishamvu', 'Karama', 'Kigoma', 'Kinazi', 'Maraba'],
      Maraba: ['Gishamvu', 'Karama', 'Kigoma', 'Kinazi', 'Maraba'],
      Mbazi: ['Gishamvu', 'Karama', 'Kigoma', 'Maraba', 'Mbazi'],
      Mukura: ['Gishamvu', 'Karama', 'Kigoma', 'Maraba', 'Mukura'],
      Ngoma: ['Gishamvu', 'Karama', 'Kigoma', 'Maraba', 'Ngoma'],
      Ruhashya: ['Gishamvu', 'Karama', 'Kigoma', 'Maraba', 'Ruhashya'],
      Rwaniro: ['Gishamvu', 'Karama', 'Kigoma', 'Maraba', 'Rwaniro'],
      Simbi: ['Gishamvu', 'Karama', 'Kigoma', 'Maraba', 'Simbi'],
      Tumba: ['Gishamvu', 'Karama', 'Kigoma', 'Maraba', 'Tumba'],
    },
    Kamonyi: {
      Gacurabwenge: ['Gacurabwenge', 'Kamonyi', 'Kayenzi', 'Kayumbu', 'Mugina'],
      Kamonyi: ['Gacurabwenge', 'Kamonyi', 'Kayenzi', 'Kayumbu', 'Mugina'],
      Kayenzi: ['Gacurabwenge', 'Kamonyi', 'Kayenzi', 'Kayumbu', 'Mugina'],
      Kayumbu: ['Gacurabwenge', 'Kamonyi', 'Kayenzi', 'Kayumbu', 'Mugina'],
      Mugina: ['Gacurabwenge', 'Kamonyi', 'Kayenzi', 'Kayumbu', 'Mugina'],
      Musambira: ['Gacurabwenge', 'Kamonyi', 'Kayenzi', 'Mugina', 'Musambira'],
      Ngamba: ['Gacurabwenge', 'Kamonyi', 'Kayenzi', 'Mugina', 'Ngamba'],
      Nyamiyaga: ['Gacurabwenge', 'Kamonyi', 'Kayenzi', 'Mugina', 'Nyamiyaga'],
      Nyarubaka: ['Gacurabwenge', 'Kamonyi', 'Kayenzi', 'Mugina', 'Nyarubaka'],
      Rugarika: ['Gacurabwenge', 'Kamonyi', 'Kayenzi', 'Mugina', 'Rugarika'],
      Rukoma: ['Gacurabwenge', 'Kamonyi', 'Kayenzi', 'Mugina', 'Rukoma'],
      Runda: ['Gacurabwenge', 'Kamonyi', 'Kayenzi', 'Mugina', 'Runda'],
    },
    Muhanga: {
      Cyeza: ['Cyeza', 'Kabacuzi', 'Kibangu', 'Kiyumba', 'Muhanga'],
      Kabacuzi: ['Cyeza', 'Kabacuzi', 'Kibangu', 'Kiyumba', 'Muhanga'],
      Kibangu: ['Cyeza', 'Kabacuzi', 'Kibangu', 'Kiyumba', 'Muhanga'],
      Kiyumba: ['Cyeza', 'Kabacuzi', 'Kibangu', 'Kiyumba', 'Muhanga'],
      Muhanga: ['Cyeza', 'Kabacuzi', 'Kibangu', 'Kiyumba', 'Muhanga'],
      Mushishiro: ['Cyeza', 'Kabacuzi', 'Kibangu', 'Muhanga', 'Mushishiro'],
      Nyabinazi: ['Cyeza', 'Kabacuzi', 'Kibangu', 'Muhanga', 'Nyabinazi'],
      Nyamabuye: ['Cyeza', 'Kabacuzi', 'Kibangu', 'Muhanga', 'Nyamabuye'],
      Nyarusange: ['Cyeza', 'Kabacuzi', 'Kibangu', 'Muhanga', 'Nyarusange'],
      Rongi: ['Cyeza', 'Kabacuzi', 'Kibangu', 'Muhanga', 'Rongi'],
      Rugendabari: ['Cyeza', 'Kabacuzi', 'Kibangu', 'Muhanga', 'Rugendabari'],
      Shyogwe: ['Cyeza', 'Kabacuzi', 'Kibangu', 'Muhanga', 'Shyogwe'],
    },
    Nyamagabe: {
      Buruhukiro: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Kaduha'],
      Cyanika: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Kaduha'],
      Gasaka: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Kaduha'],
      Gatare: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Kaduha'],
      Kaduha: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Kaduha'],
      Kamegeri: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Kamegeri'],
      Kibirizi: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Kibirizi'],
      Kibumbwe: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Kibumbwe'],
      Kitabi: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Kitabi'],
      Mbazi: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Mbazi'],
      Mugano: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Mugano'],
      Musange: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Musange'],
      Musebeya: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Musebeya'],
      Mushubi: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Mushubi'],
      Nkomane: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Nkomane'],
      Tare: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Tare'],
      Uwinkingi: ['Buruhukiro', 'Cyanika', 'Gasaka', 'Gatare', 'Uwinkingi'],
    },
    Nyanza: {
      Busasamana: ['Busasamana', 'Cyabakamyi', 'Kigoma', 'Mukingo', 'Nyagisozi'],
      Cyabakamyi: ['Busasamana', 'Cyabakamyi', 'Kigoma', 'Mukingo', 'Nyagisozi'],
      Kigoma: ['Busasamana', 'Cyabakamyi', 'Kigoma', 'Mukingo', 'Nyagisozi'],
      Mukingo: ['Busasamana', 'Cyabakamyi', 'Kigoma', 'Mukingo', 'Nyagisozi'],
      Muyira: ['Busasamana', 'Cyabakamyi', 'Kigoma', 'Mukingo', 'Muyira'],
      Ntyazo: ['Busasamana', 'Cyabakamyi', 'Kigoma', 'Mukingo', 'Ntyazo'],
      Nyagisozi: ['Busasamana', 'Cyabakamyi', 'Kigoma', 'Mukingo', 'Nyagisozi'],
      Rwabicuma: ['Busasamana', 'Cyabakamyi', 'Kigoma', 'Mukingo', 'Rwabicuma'],
    },
    Nyaruguru: {
      Cyahinda: ['Cyahinda', 'Kibeho', 'Mata', 'Muganza', 'Munini'],
      Kibeho: ['Cyahinda', 'Kibeho', 'Mata', 'Muganza', 'Munini'],
      Kibumbwe: ['Cyahinda', 'Kibeho', 'Kibumbwe', 'Muganza', 'Munini'],
      Mata: ['Cyahinda', 'Kibeho', 'Mata', 'Muganza', 'Munini'],
      Muganza: ['Cyahinda', 'Kibeho', 'Mata', 'Muganza', 'Munini'],
      Munini: ['Cyahinda', 'Kibeho', 'Mata', 'Muganza', 'Munini'],
      Ngera: ['Cyahinda', 'Kibeho', 'Mata', 'Muganza', 'Ngera'],
      Ngoma: ['Cyahinda', 'Kibeho', 'Mata', 'Muganza', 'Ngoma'],
      Nyabimata: ['Cyahinda', 'Kibeho', 'Mata', 'Muganza', 'Nyabimata'],
      Nyagisozi: ['Cyahinda', 'Kibeho', 'Mata', 'Muganza', 'Nyagisozi'],
      Ruheru: ['Cyahinda', 'Kibeho', 'Mata', 'Muganza', 'Ruheru'],
      Rusenge: ['Cyahinda', 'Kibeho', 'Mata', 'Muganza', 'Rusenge'],
      Ruramba: ['Cyahinda', 'Kibeho', 'Mata', 'Muganza', 'Ruramba'],
      Simbi: ['Cyahinda', 'Kibeho', 'Mata', 'Muganza', 'Simbi'],
    },
    Ruhango: {
      Byimana: ['Byimana', 'Kabagali', 'Kinazi', 'Mbuye', 'Ntongwe'],
      Kabagali: ['Byimana', 'Kabagali', 'Kinazi', 'Mbuye', 'Ntongwe'],
      Kinazi: ['Byimana', 'Kabagali', 'Kinazi', 'Mbuye', 'Ntongwe'],
      Mbuye: ['Byimana', 'Kabagali', 'Kinazi', 'Mbuye', 'Ntongwe'],
      Mwendo: ['Byimana', 'Kabagali', 'Kinazi', 'Mbuye', 'Mwendo'],
      Ntongwe: ['Byimana', 'Kabagali', 'Kinazi', 'Mbuye', 'Ntongwe'],
      Ruhango: ['Byimana', 'Kabagali', 'Kinazi', 'Mbuye', 'Ruhango'],
      Ruyenzi: ['Byimana', 'Kabagali', 'Kinazi', 'Mbuye', 'Ruyenzi'],
    },
  },
  'Western Province': {
    Karongi: {
      Bwishyura: ['Bwishyura', 'Gishyita', 'Gitesi', 'Mubuga', 'Murundi'],
      Gashari: ['Bwishyura', 'Gashari', 'Gitesi', 'Mubuga', 'Murundi'],
      Gishyita: ['Bwishyura', 'Gishyita', 'Gitesi', 'Mubuga', 'Murundi'],
      Gitesi: ['Bwishyura', 'Gishyita', 'Gitesi', 'Mubuga', 'Murundi'],
      Mubuga: ['Bwishyura', 'Gishyita', 'Gitesi', 'Mubuga', 'Murundi'],
      Murundi: ['Bwishyura', 'Gishyita', 'Gitesi', 'Mubuga', 'Murundi'],
      Mutuntu: ['Bwishyura', 'Gishyita', 'Gitesi', 'Mubuga', 'Mutuntu'],
      Rugabano: ['Bwishyura', 'Gishyita', 'Gitesi', 'Mubuga', 'Rugabano'],
      Ruganda: ['Bwishyura', 'Gishyita', 'Gitesi', 'Mubuga', 'Ruganda'],
      Rwankuba: ['Bwishyura', 'Gishyita', 'Gitesi', 'Mubuga', 'Rwankuba'],
      Twumba: ['Bwishyura', 'Gishyita', 'Gitesi', 'Mubuga', 'Twumba'],
    },
    Ngororero: {
      Bwira: ['Bwira', 'Gatumba', 'Hindiro', 'Kabaya', 'Kageyo'],
      Gatumba: ['Bwira', 'Gatumba', 'Hindiro', 'Kabaya', 'Kageyo'],
      Hindiro: ['Bwira', 'Gatumba', 'Hindiro', 'Kabaya', 'Kageyo'],
      Kabaya: ['Bwira', 'Gatumba', 'Hindiro', 'Kabaya', 'Kageyo'],
      Kageyo: ['Bwira', 'Gatumba', 'Hindiro', 'Kabaya', 'Kageyo'],
      Kavumu: ['Bwira', 'Gatumba', 'Hindiro', 'Kabaya', 'Kavumu'],
      Matyazo: ['Bwira', 'Gatumba', 'Hindiro', 'Kabaya', 'Matyazo'],
      Muhanda: ['Bwira', 'Gatumba', 'Hindiro', 'Kabaya', 'Muhanda'],
      Muhororo: ['Bwira', 'Gatumba', 'Hindiro', 'Kabaya', 'Muhororo'],
      Ndaro: ['Bwira', 'Gatumba', 'Hindiro', 'Kabaya', 'Ndaro'],
      Ngororero: ['Bwira', 'Gatumba', 'Hindiro', 'Kabaya', 'Ngororero'],
      Nyange: ['Bwira', 'Gatumba', 'Hindiro', 'Kabaya', 'Nyange'],
      Sovu: ['Bwira', 'Gatumba', 'Hindiro', 'Kabaya', 'Sovu'],
    },
    Nyabihu: {
      Bigogwe: ['Bigogwe', 'Jomba', 'Kabatwa', 'Karago', 'Kintobo'],
      Jomba: ['Bigogwe', 'Jomba', 'Kabatwa', 'Karago', 'Kintobo'],
      Kabatwa: ['Bigogwe', 'Jomba', 'Kabatwa', 'Karago', 'Kintobo'],
      Karago: ['Bigogwe', 'Jomba', 'Kabatwa', 'Karago', 'Kintobo'],
      Kintobo: ['Bigogwe', 'Jomba', 'Kabatwa', 'Karago', 'Kintobo'],
      Mukamira: ['Bigogwe', 'Jomba', 'Kabatwa', 'Karago', 'Mukamira'],
      Muringa: ['Bigogwe', 'Jomba', 'Kabatwa', 'Karago', 'Muringa'],
      Rambura: ['Bigogwe', 'Jomba', 'Kabatwa', 'Karago', 'Rambura'],
      Rurembo: ['Bigogwe', 'Jomba', 'Kabatwa', 'Karago', 'Rurembo'],
      Shyira: ['Bigogwe', 'Jomba', 'Kabatwa', 'Karago', 'Shyira'],
    },
    Nyamasheke: {
      Bushekeri: ['Bushekeri', 'Bushenge', 'Cyato', 'Kanjongo', 'Kagano'],
      Bushenge: ['Bushekeri', 'Bushenge', 'Cyato', 'Kanjongo', 'Kagano'],
      Cyato: ['Bushekeri', 'Bushenge', 'Cyato', 'Kanjongo', 'Kagano'],
      Gihombo: ['Bushekeri', 'Bushenge', 'Cyato', 'Gihombo', 'Kagano'],
      Kagano: ['Bushekeri', 'Bushenge', 'Cyato', 'Kanjongo', 'Kagano'],
      Kanjongo: ['Bushekeri', 'Bushenge', 'Cyato', 'Kanjongo', 'Kagano'],
      Karambi: ['Bushekeri', 'Bushenge', 'Cyato', 'Kanjongo', 'Karambi'],
      Karengera: ['Bushekeri', 'Bushenge', 'Cyato', 'Kanjongo', 'Karengera'],
      Kirimbi: ['Bushekeri', 'Bushenge', 'Cyato', 'Kanjongo', 'Kirimbi'],
      Macuba: ['Bushekeri', 'Bushenge', 'Cyato', 'Kanjongo', 'Macuba'],
      Mahembe: ['Bushekeri', 'Bushenge', 'Cyato', 'Kanjongo', 'Mahembe'],
      Nyabitekeri: ['Bushekeri', 'Bushenge', 'Cyato', 'Kanjongo', 'Nyabitekeri'],
      Rangiro: ['Bushekeri', 'Bushenge', 'Cyato', 'Kanjongo', 'Rangiro'],
      Ruharambuga: ['Bushekeri', 'Bushenge', 'Cyato', 'Kanjongo', 'Ruharambuga'],
      Shangi: ['Bushekeri', 'Bushenge', 'Cyato', 'Kanjongo', 'Shangi'],
    },
    Rubavu: {
      Bugeshi: ['Bugeshi', 'Busasamana', 'Cyanzarwe', 'Gisenyi', 'Kanama'],
      Busasamana: ['Bugeshi', 'Busasamana', 'Cyanzarwe', 'Gisenyi', 'Kanama'],
      Cyanzarwe: ['Bugeshi', 'Busasamana', 'Cyanzarwe', 'Gisenyi', 'Kanama'],
      Gisenyi: ['Bugeshi', 'Busasamana', 'Cyanzarwe', 'Gisenyi', 'Kanama'],
      Kanama: ['Bugeshi', 'Busasamana', 'Cyanzarwe', 'Gisenyi', 'Kanama'],
      Kanzenze: ['Bugeshi', 'Busasamana', 'Cyanzarwe', 'Gisenyi', 'Kanzenze'],
      Mudende: ['Bugeshi', 'Busasamana', 'Cyanzarwe', 'Gisenyi', 'Mudende'],
      Nyamyumba: ['Bugeshi', 'Busasamana', 'Cyanzarwe', 'Gisenyi', 'Nyamyumba'],
      Nyundo: ['Bugeshi', 'Busasamana', 'Cyanzarwe', 'Gisenyi', 'Nyundo'],
      Rubavu: ['Bugeshi', 'Busasamana', 'Cyanzarwe', 'Gisenyi', 'Rubavu'],
      Rugerero: ['Bugeshi', 'Busasamana', 'Cyanzarwe', 'Gisenyi', 'Rugerero'],
    },
    Rusizi: {
      Bugarama: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Giheke'],
      Butare: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Giheke'],
      Bweyeye: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Giheke'],
      Gashonga: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Giheke'],
      Giheke: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Giheke'],
      Gihundwe: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Gihundwe'],
      Gitambi: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Gitambi'],
      Kamembe: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Kamembe'],
      Muganza: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Muganza'],
      Mururu: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Mururu'],
      Nkanka: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Nkanka'],
      Nkombo: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Nkombo'],
      Nkungu: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Nkungu'],
      Nyakarenzo: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Nyakarenzo'],
      Nzahaha: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Nzahaha'],
      Rwimbogo: ['Bugarama', 'Butare', 'Bweyeye', 'Gashonga', 'Rwimbogo'],
    },
    Rutsiro: {
      Boneza: ['Boneza', 'Gihango', 'Kigeyo', 'Kivumu', 'Manihira'],
      Gihango: ['Boneza', 'Gihango', 'Kigeyo', 'Kivumu', 'Manihira'],
      Kigeyo: ['Boneza', 'Gihango', 'Kigeyo', 'Kivumu', 'Manihira'],
      Kivumu: ['Boneza', 'Gihango', 'Kigeyo', 'Kivumu', 'Manihira'],
      Manihira: ['Boneza', 'Gihango', 'Kigeyo', 'Kivumu', 'Manihira'],
      Mukura: ['Boneza', 'Gihango', 'Kigeyo', 'Kivumu', 'Mukura'],
      Murunda: ['Boneza', 'Gihango', 'Kigeyo', 'Kivumu', 'Murunda'],
      Musasa: ['Boneza', 'Gihango', 'Kigeyo', 'Kivumu', 'Musasa'],
      Mushonyi: ['Boneza', 'Gihango', 'Kigeyo', 'Kivumu', 'Mushonyi'],
      Mushubati: ['Boneza', 'Gihango', 'Kigeyo', 'Kivumu', 'Mushubati'],
      Nyabirasi: ['Boneza', 'Gihango', 'Kigeyo', 'Kivumu', 'Nyabirasi'],
      Ruhango: ['Boneza', 'Gihango', 'Kigeyo', 'Kivumu', 'Ruhango'],
      Rusebeya: ['Boneza', 'Gihango', 'Kigeyo', 'Kivumu', 'Rusebeya'],
    },
  },
} as const;

export type DistrictsByProvince<P extends Province> = keyof (typeof RWANDA_GEO)[P];
export type SectorsByDistrict<P extends Province, D extends DistrictsByProvince<P>> =
  keyof (typeof RWANDA_GEO)[P][D];

type GeoRecord = Record<string, Record<string, readonly string[]>>;

export function getDistricts(province: string): string[] {
  const p = (RWANDA_GEO as unknown as Record<string, GeoRecord>)[province];
  return p ? Object.keys(p) : [];
}

export function getSectors(province: string, district: string): string[] {
  const p = (RWANDA_GEO as unknown as Record<string, GeoRecord>)[province];
  if (!p) return [];
  const d = p[district];
  return d ? Object.keys(d) : [];
}

export function getCells(province: string, district: string, sector: string): string[] {
  const p = (RWANDA_GEO as unknown as Record<string, GeoRecord>)[province];
  if (!p) return [];
  const d = p[district];
  if (!d) return [];
  return [...(d[sector] ?? [])];
}
