/*
  # Seed : 120 questions Révision — Unité 5 Prépositions et connecteurs

  12 points × 10 questions (QCM format TCF).
  point_id résolu via revision_unites.numero = 5 + revision_points.numero.
  Idempotent : n'insère pas si (point_id, ordre) existe déjà.
*/

WITH questions_seed (
  point_numero,
  ordre,
  niveau,
  question_texte,
  choix_a,
  choix_b,
  choix_c,
  choix_d,
  bonne_reponse
) AS (
  VALUES
  (1::integer, 1::integer, 'A1'::text,
   'Je vais ___ école à pied.'::text,
   'à l'''::text, 'à'::text, 'en'::text, 'dans'::text,
   'a'::text),
  (1::integer, 2::integer, 'A1'::text,
   'Le livre est ___ la table.'::text,
   'sous'::text, 'sur'::text, 'dans'::text, 'à'::text,
   'b'::text),
  (1::integer, 3::integer, 'A2'::text,
   'Elle parle ___ son frère.'::text,
   'de'::text, 'avec'::text, 'à'::text, 'pour'::text,
   'c'::text),
  (1::integer, 4::integer, 'B1'::text,
   'Ce cadeau est ___ toi.'::text,
   'par'::text, 'à'::text, 'de'::text, 'pour'::text,
   'd'::text),
  (1::integer, 5::integer, 'B1'::text,
   'Il est content ___ ses résultats.'::text,
   'de'::text, 'à'::text, 'avec'::text, 'pour'::text,
   'a'::text),
  (1::integer, 6::integer, 'B2'::text,
   'Nous dépendons ___ nos fournisseurs.'::text,
   'à'::text, 'de'::text, 'sur'::text, 'pour'::text,
   'b'::text),
  (1::integer, 7::integer, 'B2'::text,
   'Elle s''intéresse ___ la photographie.'::text,
   'de'::text, 'pour'::text, 'à'::text, 'sur'::text,
   'c'::text),
  (1::integer, 8::integer, 'C1'::text,
   'Il a agi ___ conviction.'::text,
   'pour'::text, 'de'::text, 'avec'::text, 'par'::text,
   'd'::text),
  (1::integer, 9::integer, 'C1'::text,
   'Ce roman a été écrit ___ une auteure rwandaise.'::text,
   'par'::text, 'de'::text, 'à'::text, 'pour'::text,
   'a'::text),
  (1::integer, 10::integer, 'C2'::text,
   '___ ces conditions, le projet ne peut aboutir.'::text,
   'Sous'::text, 'Dans'::text, 'En'::text, 'À'::text,
   'b'::text),
  (2::integer, 1::integer, 'A2'::text,
   'Il habite ___ la gare.'::text,
   'près de'::text, 'près'::text, 'proche'::text, 'à côté'::text,
   'a'::text),
  (2::integer, 2::integer, 'A2'::text,
   'Range tes affaires ___ le lit.'::text,
   'à côté'::text, 'à côté de'::text, 'près'::text, 'contre de'::text,
   'b'::text),
  (2::integer, 3::integer, 'B1'::text,
   'Le chat est caché ___ le canapé.'::text,
   'derrière de'::text, 'après'::text, 'derrière'::text, 'sous de'::text,
   'c'::text),
  (2::integer, 4::integer, 'B1'::text,
   'Nous marchons ___ la rivière.'::text,
   'le long'::text, 'au long'::text, 'sur long de'::text, 'le long de'::text,
   'd'::text),
  (2::integer, 5::integer, 'B1'::text,
   'Elle est partie ___ ses parents.'::text,
   'chez'::text, 'avec chez'::text, 'à'::text, 'vers chez'::text,
   'a'::text),
  (2::integer, 6::integer, 'B2'::text,
   '___ la pluie, le match a été annulé.'::text,
   'Parce de'::text, 'À cause de'::text, 'Grâce de'::text, 'Afin de'::text,
   'b'::text),
  (2::integer, 7::integer, 'B2'::text,
   'Il a réussi ___ son travail régulier.'::text,
   'grâce de'::text, 'à cause de'::text, 'grâce à'::text, 'malgré à'::text,
   'c'::text),
  (2::integer, 8::integer, 'C1'::text,
   '___ l''accord signé, les travaux commenceront lundi.'::text,
   'En vertu à'::text, 'Par vertu de'::text, 'Sous vertu de'::text, 'En vertu de'::text,
   'd'::text),
  (2::integer, 9::integer, 'C1'::text,
   'Ils ont agi ___ les consignes reçues.'::text,
   'conformément à'::text, 'conformément de'::text, 'selon à'::text, 'suivant de'::text,
   'a'::text),
  (2::integer, 10::integer, 'C2'::text,
   '___ de nouveaux éléments, l''enquête est relancée.'::text,
   'Au vue'::text, 'Au vu'::text, 'En vu'::text, 'À vue'::text,
   'b'::text),
  (3::integer, 1::integer, 'A1'::text,
   'J''habite ___ Kigali.'::text,
   'à'::text, 'en'::text, 'dans'::text, 'au'::text,
   'a'::text),
  (3::integer, 2::integer, 'A1'::text,
   'Nous allons ___ France cet été.'::text,
   'à'::text, 'en'::text, 'au'::text, 'dans'::text,
   'b'::text),
  (3::integer, 3::integer, 'A2'::text,
   'Le stylo est ___ mon sac.'::text,
   'sur'::text, 'à'::text, 'dans'::text, 'en'::text,
   'c'::text),
  (3::integer, 4::integer, 'B1'::text,
   'Ils viennent ___ Canada.'::text,
   'de'::text, 'au'::text, 'en'::text, 'du'::text,
   'd'::text),
  (3::integer, 5::integer, 'B1'::text,
   'Le restaurant se trouve ___ centre-ville.'::text,
   'au'::text, 'à'::text, 'en'::text, 'dans'::text,
   'a'::text),
  (3::integer, 6::integer, 'B2'::text,
   'Place-toi ___ moi, s''il te plaît.'::text,
   'devant de'::text, 'devant'::text, 'avant'::text, 'face'::text,
   'b'::text),
  (3::integer, 7::integer, 'B2'::text,
   'L''avion survole ___ l''océan.'::text,
   'au-dessus'::text, 'sur de'::text, 'au-dessus de'::text, 'en haut de'::text,
   'c'::text),
  (3::integer, 8::integer, 'C1'::text,
   'Les clés sont tombées ___ le canapé.'::text,
   'dessous'::text, 'en bas'::text, 'dedans'::text, 'sous'::text,
   'd'::text),
  (3::integer, 9::integer, 'C1'::text,
   'Il s''est installé ___ les tropiques.'::text,
   'sous'::text, 'dans'::text, 'en'::text, 'à'::text,
   'a'::text),
  (3::integer, 10::integer, 'C2'::text,
   'Le village est situé ___ colline et la rivière.'::text,
   'entre'::text, 'entre la'::text, 'parmi la'::text, 'au milieu'::text,
   'b'::text),
  (4::integer, 1::integer, 'A1'::text,
   'Le cours commence ___ 9 heures.'::text,
   'à'::text, 'en'::text, 'dans'::text, 'sur'::text,
   'a'::text),
  (4::integer, 2::integer, 'A1'::text,
   'Je suis né ___ 1998.'::text,
   'à'::text, 'en'::text, 'dans'::text, 'sur'::text,
   'b'::text),
  (4::integer, 3::integer, 'A2'::text,
   'Nous partons ___ août.'::text,
   'à'::text, 'dans'::text, 'en'::text, 'sur'::text,
   'c'::text),
  (4::integer, 4::integer, 'B1'::text,
   'Il faut finir ce travail ___ vendredi.'::text,
   'devant'::text, 'jusque'::text, 'depuis'::text, 'avant'::text,
   'd'::text),
  (4::integer, 5::integer, 'B1'::text,
   'Je t''attends ___ 10 minutes.'::text,
   'dans'::text, 'en'::text, 'pendant'::text, 'depuis'::text,
   'a'::text),
  (4::integer, 6::integer, 'B2'::text,
   'Elle travaille ici ___ trois ans.'::text,
   'pendant'::text, 'depuis'::text, 'pour'::text, 'il y a'::text,
   'b'::text),
  (4::integer, 7::integer, 'B2'::text,
   'Le film dure ___ deux heures.'::text,
   'depuis'::text, 'dans'::text, 'pendant'::text, 'pour'::text,
   'c'::text),
  (4::integer, 8::integer, 'C1'::text,
   '___ mon arrivée, personne n''a téléphoné.'::text,
   'Pendant'::text, 'Durant à'::text, 'Il y a'::text, 'Depuis'::text,
   'd'::text),
  (4::integer, 9::integer, 'C1'::text,
   'Il est resté ___ la nuit entière.'::text,
   'pendant'::text, 'depuis'::text, 'dans'::text, 'pour'::text,
   'a'::text),
  (4::integer, 10::integer, 'C2'::text,
   '___ là, préparez tous les documents.'::text,
   'Jusqu''à'::text, 'D''ici'::text, 'Avant de'::text, 'Depuis'::text,
   'b'::text),
  (5::integer, 1::integer, 'A1'::text,
   'J''aime le thé ___ le café.'::text,
   'et'::text, 'mais'::text, 'ou'::text, 'donc'::text,
   'a'::text),
  (5::integer, 2::integer, 'A1'::text,
   'Il parle français ___ anglais.'::text,
   'mais'::text, 'et'::text, 'car'::text, 'ni'::text,
   'b'::text),
  (5::integer, 3::integer, 'A2'::text,
   'Elle est intelligente ___ sympathique.'::text,
   'mais'::text, 'donc'::text, 'et'::text, 'or'::text,
   'c'::text),
  (5::integer, 4::integer, 'B1'::text,
   'Il a réussi son examen ; ___ , il a trouvé un stage.'::text,
   'pourtant'::text, 'donc'::text, 'car'::text, 'de plus'::text,
   'd'::text),
  (5::integer, 5::integer, 'B1'::text,
   'Ce restaurant est bon ; ___ , il n''est pas cher.'::text,
   'en outre'::text, 'cependant'::text, 'parce que'::text, 'ainsi'::text,
   'a'::text),
  (5::integer, 6::integer, 'B2'::text,
   '___ son expérience, il parle trois langues.'::text,
   'Malgré'::text, 'Outre'::text, 'À cause de'::text, 'Afin de'::text,
   'b'::text),
  (5::integer, 7::integer, 'B2'::text,
   'Le rapport est clair ; ___ , les chiffres sont à jour.'::text,
   'en revanche'::text, 'par conséquent'::text, 'par ailleurs'::text, 'or'::text,
   'c'::text),
  (5::integer, 8::integer, 'C1'::text,
   '___ ces arguments, notons l''urgence climatique.'::text,
   'Malgré'::text, 'À cause de'::text, 'Afin que'::text, 'Outre'::text,
   'd'::text),
  (5::integer, 9::integer, 'C1'::text,
   'Le projet est ambitieux ; ___ , il est réaliste.'::text,
   'qui plus est'::text, 'en revanche'::text, 'pourtant'::text, 'car'::text,
   'a'::text),
  (5::integer, 10::integer, 'C2'::text,
   '___ le budget a été respecté, mais aussi le calendrier.'::text,
   'Seulement'::text, 'Non seulement'::text, 'À peine'::text, 'Même si'::text,
   'b'::text),
  (6::integer, 1::integer, 'A1'::text,
   'Je reste à la maison ___ il pleut.'::text,
   'parce qu'''::text, 'mais'::text, 'donc'::text, 'ou'::text,
   'a'::text),
  (6::integer, 2::integer, 'A2'::text,
   'Il est fatigué ___ il a mal dormi.'::text,
   'alors'::text, 'parce qu'''::text, 'mais'::text, 'ni'::text,
   'b'::text),
  (6::integer, 3::integer, 'A2'::text,
   '___ la pluie, nous annulons la sortie.'::text,
   'Grâce à'::text, 'Afin de'::text, 'À cause de'::text, 'Malgré'::text,
   'c'::text),
  (6::integer, 4::integer, 'B1'::text,
   '___ tu es là, on peut commencer.'::text,
   'Pourtant'::text, 'Alors que'::text, 'Afin que'::text, 'Puisque'::text,
   'd'::text),
  (6::integer, 5::integer, 'B1'::text,
   'Elle a réussi ___ son sérieux.'::text,
   'grâce à'::text, 'à cause de'::text, 'malgré'::text, 'pour que'::text,
   'a'::text),
  (6::integer, 6::integer, 'B2'::text,
   '___ il était malade, il n''est pas venu.'::text,
   'Pourtant'::text, 'Comme'::text, 'Donc'::text, 'Mais'::text,
   'b'::text),
  (6::integer, 7::integer, 'B2'::text,
   'Le vol a été retardé ___ du brouillard.'::text,
   'à cause'::text, 'grâce'::text, 'en raison'::text, 'malgré'::text,
   'c'::text),
  (6::integer, 8::integer, 'C1'::text,
   '___ que les données sont incomplètes, l''analyse reste prudente.'::text,
   'Bien'::text, 'Afin'::text, 'Pourvu'::text, 'Étant donné'::text,
   'd'::text),
  (6::integer, 9::integer, 'C1'::text,
   'Il a démissionné ___ un désaccord profond.'::text,
   'du fait d'''::text, 'grâce à'::text, 'afin d'''::text, 'malgré'::text,
   'a'::text),
  (6::integer, 10::integer, 'C2'::text,
   '___ l''absence de preuves, le dossier a été classé.'::text,
   'Malgré'::text, 'Vu'::text, 'Afin'::text, 'Pour que'::text,
   'b'::text),
  (7::integer, 1::integer, 'A1'::text,
   'Il pleut, ___ je prends mon parapluie.'::text,
   'donc'::text, 'mais'::text, 'car'::text, 'ou'::text,
   'a'::text),
  (7::integer, 2::integer, 'A2'::text,
   'Tu as fini ? ___ tu peux sortir.'::text,
   'Car'::text, 'Alors'::text, 'Pourtant'::text, 'Ni'::text,
   'b'::text),
  (7::integer, 3::integer, 'A2'::text,
   'Le train est parti ; ___ , nous avons raté la correspondance.'::text,
   'pourtant'::text, 'car'::text, 'par conséquent'::text, 'ou'::text,
   'c'::text),
  (7::integer, 4::integer, 'B1'::text,
   'Il a beaucoup travaillé ; ___ il a obtenu une promotion.'::text,
   'pourtant'::text, 'car'::text, 'bien que'::text, 'c''est pourquoi'::text,
   'd'::text),
  (7::integer, 5::integer, 'B1'::text,
   'Les stocks sont épuisés ; ___ , les commandes sont suspendues.'::text,
   'ainsi'::text, 'pourtant'::text, 'parce que'::text, 'ou'::text,
   'a'::text),
  (7::integer, 6::integer, 'B2'::text,
   'Tu n''as pas révisé ; ___ tu as échoué.'::text,
   'bien que'::text, 'si bien que'::text, 'afin que'::text, 'tandis que'::text,
   'b'::text),
  (7::integer, 7::integer, 'B2'::text,
   'Le discours était confus ; ___ , peu de gens ont compris.'::text,
   'en revanche'::text, 'car'::text, 'de ce fait'::text, 'malgré'::text,
   'c'::text),
  (7::integer, 8::integer, 'C1'::text,
   'Les normes ont changé ; ___ une mise à jour s''impose.'::text,
   'dont'::text, 'où'::text, 'd''ailleurs'::text, 'd''où'::text,
   'd'::text),
  (7::integer, 9::integer, 'C1'::text,
   'Il a tant insisté ___ on a fini par accepter.'::text,
   'que'::text, 'dont'::text, 'qui'::text, 'où'::text,
   'a'::text),
  (7::integer, 10::integer, 'C2'::text,
   'Les indicateurs sont au rouge ; ___ une intervention urgente.'::text,
   'malgré'::text, 'd''où la nécessité d'''::text, 'afin d'''::text, 'en dépit d'''::text,
   'b'::text),
  (8::integer, 1::integer, 'A1'::text,
   'Il fait beau, ___ je reste à la maison.'::text,
   'mais'::text, 'et'::text, 'donc'::text, 'car'::text,
   'a'::text),
  (8::integer, 2::integer, 'A2'::text,
   'Je voudrais venir, ___ je suis malade.'::text,
   'donc'::text, 'mais'::text, 'car'::text, 'ou'::text,
   'b'::text),
  (8::integer, 3::integer, 'A2'::text,
   '___ la pluie, le match a eu lieu.'::text,
   'À cause de'::text, 'Grâce à'::text, 'Malgré'::text, 'Afin de'::text,
   'c'::text),
  (8::integer, 4::integer, 'B1'::text,
   '___ il soit fatigué, il continue.'::text,
   'Parce qu'''::text, 'Afin qu'''::text, 'Depuis qu'''::text, 'Bien qu'''::text,
   'd'::text),
  (8::integer, 5::integer, 'B1'::text,
   'Ce téléphone est cher ; ___ , il est fiable.'::text,
   'cependant'::text, 'donc'::text, 'car'::text, 'ainsi'::text,
   'a'::text),
  (8::integer, 6::integer, 'B2'::text,
   'Elle a peu dormi ; ___ , elle est en forme.'::text,
   'donc'::text, 'pourtant'::text, 'car'::text, 'ainsi'::text,
   'b'::text),
  (8::integer, 7::integer, 'B2'::text,
   '___ les difficultés, le projet avance.'::text,
   'À cause de'::text, 'Grâce de'::text, 'En dépit de'::text, 'Afin de'::text,
   'c'::text),
  (8::integer, 8::integer, 'C1'::text,
   '___ on le lui ait interdit, il a persisté.'::text,
   'Parce qu'''::text, 'Afin qu'''::text, 'Sitôt qu'''::text, 'Quoiqu'''::text,
   'd'::text),
  (8::integer, 9::integer, 'C1'::text,
   'Le texte est long ; ___ , il reste passionnant.'::text,
   'néanmoins'::text, 'par conséquent'::text, 'car'::text, 'ainsi'::text,
   'a'::text),
  (8::integer, 10::integer, 'C2'::text,
   '___ ses efforts, le résultat reste insuffisant.'::text,
   'Grâce à'::text, 'Nonobstant'::text, 'Afin de'::text, 'Parce que'::text,
   'b'::text),
  (9::integer, 1::integer, 'A2'::text,
   'Je parle lentement ___ tu comprennes.'::text,
   'pour que'::text, 'parce que'::text, 'bien que'::text, 'alors que'::text,
   'a'::text),
  (9::integer, 2::integer, 'A2'::text,
   'Il économise ___ acheter une voiture.'::text,
   'par'::text, 'pour'::text, 'de'::text, 'à'::text,
   'b'::text),
  (9::integer, 3::integer, 'B1'::text,
   'Fermez la porte ___ il n''y ait pas de courant d''air.'::text,
   'parce que'::text, 'bien que'::text, 'pour que'::text, 'depuis que'::text,
   'c'::text),
  (9::integer, 4::integer, 'B1'::text,
   'Elle s''entraîne ___ réussir le concours.'::text,
   'à cause de'::text, 'malgré'::text, 'grâce à'::text, 'afin de'::text,
   'd'::text),
  (9::integer, 5::integer, 'B1'::text,
   'Prends un plan ___ te perdre.'::text,
   'pour ne pas'::text, 'parce que'::text, 'bien que'::text, 'alors que'::text,
   'a'::text),
  (9::integer, 6::integer, 'B2'::text,
   '___ faciliter la lecture, le texte a été aéré.'::text,
   'À cause de'::text, 'Afin de'::text, 'Malgré'::text, 'Parce que'::text,
   'b'::text),
  (9::integer, 7::integer, 'B2'::text,
   'Il chuchote ___ on ne l''entende pas.'::text,
   'parce que'::text, 'bien que'::text, 'de peur que'::text, 'alors que'::text,
   'c'::text),
  (9::integer, 8::integer, 'C1'::text,
   'Des mesures ont été prises ___ éviter une crise.'::text,
   'à cause d'''::text, 'en dépit d'''::text, 'grâce à'::text, 'en vue d'''::text,
   'd'::text),
  (9::integer, 9::integer, 'C1'::text,
   'Je te préviens ___ tu sois prêt.'::text,
   'afin que'::text, 'parce que'::text, 'bien que'::text, 'alors que'::text,
   'a'::text),
  (9::integer, 10::integer, 'C2'::text,
   'Le dispositif a été conçu ___ garantir la sécurité de tous.'::text,
   'à cause de'::text, 'de manière à'::text, 'en dépit de'::text, 'faute de'::text,
   'b'::text),
  (10::integer, 1::integer, 'A1'::text,
   '___ , je me lève. Ensuite, je prends mon petit-déjeuner.'::text,
   'D''abord'::text, 'Pourtant'::text, 'Donc'::text, 'Car'::text,
   'a'::text),
  (10::integer, 2::integer, 'A2'::text,
   'D''abord je travaille ; ___ je me repose.'::text,
   'pourtant'::text, 'ensuite'::text, 'car'::text, 'ni'::text,
   'b'::text),
  (10::integer, 3::integer, 'A2'::text,
   'Il est rentré ; ___ , il a dîné.'::text,
   'car'::text, 'mais'::text, 'puis'::text, 'ou'::text,
   'c'::text),
  (10::integer, 4::integer, 'B1'::text,
   '___ , présentez le contexte. Ensuite, analysez les données.'::text,
   'Pourtant'::text, 'Parce que'::text, 'Afin que'::text, 'Dans un premier temps'::text,
   'd'::text),
  (10::integer, 5::integer, 'B1'::text,
   'Le discours commence ; ___ , l''orateur salue le public.'::text,
   'tout d''abord'::text, 'pourtant'::text, 'car'::text, 'donc'::text,
   'a'::text),
  (10::integer, 6::integer, 'B2'::text,
   '___ d''entrer, il a éteint son téléphone.'::text,
   'Devant'::text, 'Avant'::text, 'Depuis'::text, 'Pendant'::text,
   'b'::text),
  (10::integer, 7::integer, 'B2'::text,
   '___ la réunion, personne n''a quitté la salle.'::text,
   'Depuis'::text, 'Devant'::text, 'Pendant'::text, 'Avant'::text,
   'c'::text),
  (10::integer, 8::integer, 'C1'::text,
   '___ , les résultats seront publiés en ligne.'::text,
   'Pourtant'::text, 'Car'::text, 'Ni'::text, 'Enfin'::text,
   'd'::text),
  (10::integer, 9::integer, 'C1'::text,
   '___ , passons à la conclusion.'::text,
   'Sur ce'::text, 'Pourtant'::text, 'Car'::text, 'Ni'::text,
   'a'::text),
  (10::integer, 10::integer, 'C2'::text,
   '___ , récapitulons les étapes principales.'::text,
   'Parce que'::text, 'Pour terminer'::text, 'Bien que'::text, 'Afin que'::text,
   'b'::text),
  (11::integer, 1::integer, 'A1'::text,
   'Il est ___ grand ___ son frère.'::text,
   'aussi / que'::text, 'plus / de'::text, 'moins / à'::text, 'si / que'::text,
   'a'::text),
  (11::integer, 2::integer, 'A2'::text,
   'Cette robe est ___ belle ___ l''autre.'::text,
   'plus / de'::text, 'plus / que'::text, 'aussi / de'::text, 'moins / à'::text,
   'b'::text),
  (11::integer, 3::integer, 'A2'::text,
   'Je cours ___ vite ___ toi.'::text,
   'moins / de'::text, 'plus / de'::text, 'moins / que'::text, 'aussi / de'::text,
   'c'::text),
  (11::integer, 4::integer, 'B1'::text,
   '___ son frère, elle est très calme.'::text,
   'Grâce à'::text, 'À cause de'::text, 'Afin de'::text, 'Contrairement à'::text,
   'd'::text),
  (11::integer, 5::integer, 'B1'::text,
   'Il agit ___ un professionnel.'::text,
   'comme'::text, 'que'::text, 'si'::text, 'tel'::text,
   'a'::text),
  (11::integer, 6::integer, 'B2'::text,
   '___ prévu, la réunion a été reportée.'::text,
   'Que'::text, 'Comme'::text, 'Si'::text, 'Tel'::text,
   'b'::text),
  (11::integer, 7::integer, 'B2'::text,
   'Le salaire est ___ élevé ___ on le pensait.'::text,
   'moins / de'::text, 'plus / de'::text, 'moins / que'::text, 'aussi / de'::text,
   'c'::text),
  (11::integer, 8::integer, 'C1'::text,
   '___ les apparences, la situation est stable.'::text,
   'Grâce à'::text, 'Afin de'::text, 'Parce que'::text, 'Contrairement à'::text,
   'd'::text),
  (11::integer, 9::integer, 'C1'::text,
   'Il parle ___ s''il connaissait déjà le dossier.'::text,
   'comme'::text, 'que'::text, 'si'::text, 'tel'::text,
   'a'::text),
  (11::integer, 10::integer, 'C2'::text,
   '___ plus le débat avance, ___ plus les positions se crispent.'::text,
   'Autant / que'::text, 'Plus / plus'::text, 'Tellement / de'::text, 'Si / que'::text,
   'b'::text),
  (12::integer, 1::integer, 'A2'::text,
   '___ , je pense que c''est une bonne idée.'::text,
   'En conclusion'::text, 'Pourtant'::text, 'Car'::text, 'Ni'::text,
   'a'::text),
  (12::integer, 2::integer, 'A2'::text,
   '___ , tout s''est bien passé.'::text,
   'Parce que'::text, 'Finalement'::text, 'Bien que'::text, 'Afin que'::text,
   'b'::text),
  (12::integer, 3::integer, 'B1'::text,
   '___ , les avantages l''emportent sur les inconvénients.'::text,
   'Pourtant'::text, 'Car'::text, 'Pour conclure'::text, 'Ou'::text,
   'c'::text),
  (12::integer, 4::integer, 'B1'::text,
   '___ , il faut retenir trois points essentiels.'::text,
   'En revanche'::text, 'Parce que'::text, 'Afin que'::text, 'En résumé'::text,
   'd'::text),
  (12::integer, 5::integer, 'B1'::text,
   '___ , le projet est viable.'::text,
   'Bref'::text, 'Pourtant'::text, 'Car'::text, 'Ni'::text,
   'a'::text),
  (12::integer, 6::integer, 'B2'::text,
   '___ ce qui précède, une réforme s''impose.'::text,
   'En dépit de'::text, 'Compte tenu de'::text, 'Afin de'::text, 'Faute de'::text,
   'b'::text),
  (12::integer, 7::integer, 'B2'::text,
   '___ , nous recommandons d''accepter l''offre.'::text,
   'Pourtant'::text, 'Car'::text, 'En définitive'::text, 'Ni'::text,
   'c'::text),
  (12::integer, 8::integer, 'C1'::text,
   '___ , les données confirment notre hypothèse initiale.'::text,
   'En revanche'::text, 'Parce que'::text, 'Afin que'::text, 'Au total'::text,
   'd'::text),
  (12::integer, 9::integer, 'C1'::text,
   '___ , retenons que la prudence reste de mise.'::text,
   'Pour finir'::text, 'Pourtant'::text, 'Car'::text, 'Ni'::text,
   'a'::text),
  (12::integer, 10::integer, 'C2'::text,
   '___ , cette analyse invite à une révision du protocole.'::text,
   'En revanche'::text, 'En dernière analyse'::text, 'Parce que'::text, 'Afin que'::text,
   'b'::text)
)
INSERT INTO public.revision_questions (
  point_id,
  ordre,
  niveau,
  question_texte,
  choix_a,
  choix_b,
  choix_c,
  choix_d,
  bonne_reponse
)
SELECT
  p.id,
  s.ordre,
  s.niveau,
  s.question_texte,
  s.choix_a,
  s.choix_b,
  s.choix_c,
  s.choix_d,
  s.bonne_reponse
FROM questions_seed s
JOIN public.revision_unites u ON u.numero = 5
JOIN public.revision_points p
  ON p.unite_id = u.id
 AND p.numero = s.point_numero
WHERE NOT EXISTS (
  SELECT 1
  FROM public.revision_questions q
  WHERE q.point_id = p.id
    AND q.ordre = s.ordre
);

NOTIFY pgrst, 'reload schema';
