/*
  # Seed : 90 questions Révision — Unité 2 Grammaire

  9 points × 10 questions (QCM format TCF).
  point_id résolu via revision_unites.numero = 2 + revision_points.numero.
  Idempotent : n'insère pas si (point_id, ordre) existe déjà.

  Niveaux par point : ~3 A1-A2, ~4 B1-B2, ~3 C1-C2.
*/

WITH questions_seed (
  point_numero,
  ordre,
  niveau,
  question_texte,
  choix_a,
  choix_b,
  choix_c,
  choix_d,
  bonne_reponse
) AS (
  VALUES
  (1::integer, 1::integer, 'A1'::text,
   'C''est ___ livre intéressant.'::text,
   'un'::text, 'une'::text, 'le'::text, 'des'::text,
   'a'::text),
  (1::integer, 2::integer, 'A1'::text,
   'Elle a une ___ (ami) française.'::text,
   'ami'::text, 'amie'::text, 'amis'::text, 'amies'::text,
   'b'::text),
  (1::integer, 3::integer, 'A2'::text,
   'Il y a beaucoup d''___ dans cette école.'::text,
   'élève'::text, 'écolier'::text, 'élèves'::text, 'étudiantes'::text,
   'c'::text),
  (1::integer, 4::integer, 'B1'::text,
   'Le pluriel de « journal » est ___ .'::text,
   'journals'::text, 'journales'::text, 'journaus'::text, 'journaux'::text,
   'd'::text),
  (1::integer, 5::integer, 'B1'::text,
   '« Travail » au pluriel s''écrit ___ .'::text,
   'travaux'::text, 'travails'::text, 'travaus'::text, 'travailles'::text,
   'a'::text),
  (1::integer, 6::integer, 'B2'::text,
   'On dit ___ (un / une) oasis au milieu du désert.'::text,
   'un'::text, 'une'::text, 'le'::text, 'de la'::text,
   'b'::text),
  (1::integer, 7::integer, 'B2'::text,
   'Les ___ (œil) de l''enfant brillaient de joie.'::text,
   'œils'::text, 'œilles'::text, 'yeux'::text, 'yeuxs'::text,
   'c'::text),
  (1::integer, 8::integer, 'C1'::text,
   'Le mot « après-midi » peut être ___ .'::text,
   'seulement masculin'::text, 'seulement féminin'::text, 'toujours pluriel'::text, 'masculin ou féminin'::text,
   'd'::text),
  (1::integer, 9::integer, 'C1'::text,
   'Dans « une espèce de génie », le nom « espèce » est ___ .'::text,
   'féminin'::text, 'masculin'::text, 'neutre'::text, 'invariable'::text,
   'a'::text),
  (1::integer, 10::integer, 'C2'::text,
   'Le pluriel de « monsieur » est ___ .'::text,
   'monsieurs'::text, 'messieurs'::text, 'messieur'::text, 'monsieures'::text,
   'b'::text),
  (2::integer, 1::integer, 'A1'::text,
   'Je mange ___ pomme tous les matins.'::text,
   'une'::text, 'un'::text, 'de la'::text, 'du'::text,
   'a'::text),
  (2::integer, 2::integer, 'A1'::text,
   '___ soleil brille aujourd''hui.'::text,
   'La'::text, 'Le'::text, 'Un'::text, 'Du'::text,
   'b'::text),
  (2::integer, 3::integer, 'A2'::text,
   'Tu veux ___ pain avec ton fromage ?'::text,
   'de la'::text, 'des'::text, 'du'::text, 'le'::text,
   'c'::text),
  (2::integer, 4::integer, 'B1'::text,
   'J''ai oublié ___ clés à la maison.'::text,
   'mon'::text, 'ma'::text, 'leurs'::text, 'mes'::text,
   'd'::text),
  (2::integer, 5::integer, 'B1'::text,
   'Tu as vu ___ film dont je t''ai parlé ?'::text,
   'ce'::text, 'cet'::text, 'cette'::text, 'ces'::text,
   'a'::text),
  (2::integer, 6::integer, 'B2'::text,
   'Il n''y a plus ___ lait dans le frigo.'::text,
   'du'::text, 'de'::text, 'le'::text, 'des'::text,
   'b'::text),
  (2::integer, 7::integer, 'B2'::text,
   '___ amie m''a téléphoné hier soir.'::text,
   'Ma'::text, 'Mes'::text, 'Mon'::text, 'Ton'::text,
   'c'::text),
  (2::integer, 8::integer, 'C1'::text,
   'Nous avons acheté ___ beaux livres.'::text,
   'des'::text, 'du'::text, 'les'::text, 'de'::text,
   'd'::text),
  (2::integer, 9::integer, 'C1'::text,
   'Elle boit ___ eau tous les jours.'::text,
   'de l'''::text, 'de la'::text, 'du'::text, 'une'::text,
   'a'::text),
  (2::integer, 10::integer, 'C2'::text,
   'À ___ époque, les gens voyageaient peu.'::text,
   'cet'::text, 'cette'::text, 'ce'::text, 'ces'::text,
   'b'::text),
  (3::integer, 1::integer, 'A1'::text,
   'C''est une voiture ___ .'::text,
   'rouge'::text, 'rouges'::text, 'rougs'::text, 'rougue'::text,
   'a'::text),
  (3::integer, 2::integer, 'A1'::text,
   'Paul est un ___ garçon.'::text,
   'petite'::text, 'petit'::text, 'petits'::text, 'petites'::text,
   'b'::text),
  (3::integer, 3::integer, 'A2'::text,
   'Ces fleurs sont ___ .'::text,
   'beau'::text, 'belle'::text, 'belles'::text, 'beaux'::text,
   'c'::text),
  (3::integer, 4::integer, 'B1'::text,
   'Elle a les cheveux ___ .'::text,
   'court'::text, 'courtes'::text, 'courte'::text, 'courts'::text,
   'd'::text),
  (3::integer, 5::integer, 'B1'::text,
   'C''est le ___ restaurant de la ville.'::text,
   'meilleur'::text, 'mieux'::text, 'plus bon'::text, 'bonner'::text,
   'a'::text),
  (3::integer, 6::integer, 'B2'::text,
   'Marie est ___ que sa sœur.'::text,
   'plus grand'::text, 'plus grande'::text, 'la plus grande'::text, 'aussi grande'::text,
   'b'::text),
  (3::integer, 7::integer, 'B2'::text,
   'C''est un ___ ami.'::text,
   'vieux'::text, 'vieille'::text, 'vieil'::text, 'vieilles'::text,
   'c'::text),
  (3::integer, 8::integer, 'C1'::text,
   'Parmi ces adjectifs, lequel se place généralement avant le nom ?'::text,
   'italien'::text, 'intéressante'::text, 'en bois'::text, 'grand'::text,
   'd'::text),
  (3::integer, 9::integer, 'C1'::text,
   'C''est la ___ solution possible.'::text,
   'meilleure'::text, 'mieux'::text, 'plus bonne'::text, 'meilleur'::text,
   'a'::text),
  (3::integer, 10::integer, 'C2'::text,
   'Ces informations sont ___ .'::text,
   'confidentiel'::text, 'confidentielles'::text, 'confidentiels'::text, 'confidentielle'::text,
   'b'::text),
  (4::integer, 1::integer, 'A1'::text,
   'Marie ? ___ est française.'::text,
   'Elle'::text, 'Il'::text, 'Lui'::text, 'La'::text,
   'a'::text),
  (4::integer, 2::integer, 'A1'::text,
   'Tu as le livre ? Oui, je ___ ai.'::text,
   'le'::text, 'l'::text, 'la'::text, 'les'::text,
   'b'::text),
  (4::integer, 3::integer, 'A2'::text,
   'Je téléphone à Paul. Je ___ téléphone.'::text,
   'le'::text, 'la'::text, 'lui'::text, 'leur'::text,
   'c'::text),
  (4::integer, 4::integer, 'B1'::text,
   'Tu vas à Paris ? Oui, j''___ vais demain.'::text,
   'en'::text, 'le'::text, 'là'::text, 'y'::text,
   'd'::text),
  (4::integer, 5::integer, 'B1'::text,
   'Tu veux du café ? Oui, j''___ veux bien.'::text,
   'en'::text, 'y'::text, 'le'::text, 'de'::text,
   'a'::text),
  (4::integer, 6::integer, 'B2'::text,
   'Ces fleurs, je ___ ai offertes à ma mère.'::text,
   'leur'::text, 'les'::text, 'la'::text, 'eux'::text,
   'b'::text),
  (4::integer, 7::integer, 'B2'::text,
   'Parle-___ ! Il t''écoute.'::text,
   'le'::text, 'il'::text, 'lui'::text, 'eux'::text,
   'c'::text),
  (4::integer, 8::integer, 'C1'::text,
   'Donne-___-en deux, s''il te plaît.'::text,
   'moi'::text, 'me'::text, 'lui'::text, 'm'''::text,
   'd'::text),
  (4::integer, 9::integer, 'C1'::text,
   'Ils nous ont écrit. Nous ___ avons répondu.'::text,
   'leur'::text, 'les'::text, 'eux'::text, 'y'::text,
   'a'::text),
  (4::integer, 10::integer, 'C2'::text,
   'Penses-y ! / Parles-en ! — À l''impératif affirmatif, le pronom est ___ .'::text,
   'avant le verbe'::text, 'après le verbe'::text, 'omis'::text, 'remplacé par le nom'::text,
   'b'::text),
  (5::integer, 1::integer, 'A1'::text,
   'Voici l''homme ___ parle français.'::text,
   'qui'::text, 'que'::text, 'dont'::text, 'où'::text,
   'a'::text),
  (5::integer, 2::integer, 'A1'::text,
   'C''est le film ___ j''ai vu hier.'::text,
   'qui'::text, 'que'::text, 'dont'::text, 'où'::text,
   'b'::text),
  (5::integer, 3::integer, 'A2'::text,
   'La ville ___ j''habite est petite.'::text,
   'qui'::text, 'que'::text, 'où'::text, 'dont'::text,
   'c'::text),
  (5::integer, 4::integer, 'B1'::text,
   'C''est le livre ___ je t''ai parlé.'::text,
   'que'::text, 'qui'::text, 'où'::text, 'dont'::text,
   'd'::text),
  (5::integer, 5::integer, 'B1'::text,
   'La femme ___ tu as rencontrée est journaliste.'::text,
   'que'::text, 'qui'::text, 'dont'::text, 'laquelle'::text,
   'a'::text),
  (5::integer, 6::integer, 'B2'::text,
   'Voici la table sur ___ j''ai posé mes clés.'::text,
   'qui'::text, 'laquelle'::text, 'que'::text, 'dont'::text,
   'b'::text),
  (5::integer, 7::integer, 'B2'::text,
   'Les enfants avec ___ elle travaille sont charmants.'::text,
   'qui'::text, 'que'::text, 'lesquels'::text, 'dont'::text,
   'c'::text),
  (5::integer, 8::integer, 'C1'::text,
   'C''est une décision ___ dépend notre avenir.'::text,
   'que'::text, 'qui'::text, 'où'::text, 'dont'::text,
   'd'::text),
  (5::integer, 9::integer, 'C1'::text,
   'Le problème ___ tu fais allusion est complexe.'::text,
   'auquel'::text, 'dont'::text, 'que'::text, 'qui'::text,
   'a'::text),
  (5::integer, 10::integer, 'C2'::text,
   'Voici le document grâce ___ nous avons obtenu le financement.'::text,
   'dont'::text, 'auquel'::text, 'à qui'::text, 'que'::text,
   'b'::text),
  (6::integer, 1::integer, 'A1'::text,
   'Tu préfères cette robe ou ___ ?'::text,
   'celle-là'::text, 'celui-là'::text, 'ceux-là'::text, 'celles'::text,
   'a'::text),
  (6::integer, 2::integer, 'A1'::text,
   'Ce stylo est à moi. C''est ___ .'::text,
   'la mienne'::text, 'le mien'::text, 'les miens'::text, 'le tien'::text,
   'b'::text),
  (6::integer, 3::integer, 'A2'::text,
   'Ces chaussures sont à elle. Ce sont ___ .'::text,
   'les siens'::text, 'la sienne'::text, 'les siennes'::text, 'le sien'::text,
   'c'::text),
  (6::integer, 4::integer, 'B1'::text,
   'J''aime ton idée, mais je préfère ___ .'::text,
   'le mien'::text, 'les miennes'::text, 'ma'::text, 'la mienne'::text,
   'd'::text),
  (6::integer, 5::integer, 'B1'::text,
   'Parmi ces deux projets, ___ me plaît le plus.'::text,
   'celui-ci'::text, 'celle-ci'::text, 'ceux-ci'::text, 'ceci'::text,
   'a'::text),
  (6::integer, 6::integer, 'B2'::text,
   '___ qui veulent venir doivent s''inscrire.'::text,
   'Celui'::text, 'Ceux'::text, 'Celles'::text, 'Ce'::text,
   'b'::text),
  (6::integer, 7::integer, 'B2'::text,
   'Ta voiture est plus rapide que ___ .'::text,
   'le nôtre'::text, 'les nôtres'::text, 'la nôtre'::text, 'notre'::text,
   'c'::text),
  (6::integer, 8::integer, 'C1'::text,
   '___ dont tu parles est déjà parti.'::text,
   'Celle'::text, 'Ceux'::text, 'Ce'::text, 'Celui'::text,
   'd'::text),
  (6::integer, 9::integer, 'C1'::text,
   'Ces résultats sont meilleurs que ___ de l''an dernier.'::text,
   'ceux'::text, 'celui'::text, 'celles'::text, 'ce'::text,
   'a'::text),
  (6::integer, 10::integer, 'C2'::text,
   'À chacun ___ : respecte le travail des autres.'::text,
   'la sienne'::text, 'le sien'::text, 'les siens'::text, 'son'::text,
   'b'::text),
  (7::integer, 1::integer, 'A1'::text,
   'Elle parle ___ .'::text,
   'lentement'::text, 'lente'::text, 'lent'::text, 'lentemente'::text,
   'a'::text),
  (7::integer, 2::integer, 'A1'::text,
   'Il travaille ___ .'::text,
   'bon'::text, 'bien'::text, 'bonne'::text, 'bons'::text,
   'b'::text),
  (7::integer, 3::integer, 'A2'::text,
   'Nous arrivons ___ .'::text,
   'souventement'::text, 'souvente'::text, 'souvent'::text, 'plus souventement'::text,
   'c'::text),
  (7::integer, 4::integer, 'B1'::text,
   'L''adverbe formé sur « heureux » est ___ .'::text,
   'heureurement'::text, 'heureuxement'::text, 'heureusment'::text, 'heureusement'::text,
   'd'::text),
  (7::integer, 5::integer, 'B1'::text,
   'Il a ___ compris la consigne.'::text,
   'bien'::text, 'bon'::text, 'bonne'::text, 'mieux'::text,
   'a'::text),
  (7::integer, 6::integer, 'B2'::text,
   'Elle chante ___ que sa sœur.'::text,
   'meilleur'::text, 'mieux'::text, 'plus bien'::text, 'bonne'::text,
   'b'::text),
  (7::integer, 7::integer, 'B2'::text,
   'L''adverbe correspondant à « patient » est ___ .'::text,
   'patientement'::text, 'patiement'::text, 'patiemment'::text, 'patienceusement'::text,
   'c'::text),
  (7::integer, 8::integer, 'C1'::text,
   'Dans « Il a toujours dit la vérité », l''adverbe se place ___ .'::text,
   'avant le verbe'::text, 'après le participe'::text, 'en début de phrase uniquement'::text, 'entre l''auxiliaire et le participe'::text,
   'd'::text),
  (7::integer, 9::integer, 'C1'::text,
   '« Gentil » → adverbe : ___ .'::text,
   'gentiment'::text, 'gentillement'::text, 'gentilement'::text, 'gentimentement'::text,
   'a'::text),
  (7::integer, 10::integer, 'C2'::text,
   'Choisis la phrase où l''adverbe est correctement placé.'::text,
   'Il probablement a raison.'::text, 'Il a probablement raison.'::text, 'Il a raison probablement toujours ici.'::text, 'Probablementment il a raison.'::text,
   'b'::text),
  (8::integer, 1::integer, 'A1'::text,
   'J''habite ___ Paris.'::text,
   'à'::text, 'en'::text, 'dans'::text, 'au'::text,
   'a'::text),
  (8::integer, 2::integer, 'A1'::text,
   'Je vais ___ Maroc cet été.'::text,
   'à'::text, 'au'::text, 'en'::text, 'dans'::text,
   'b'::text),
  (8::integer, 3::integer, 'A2'::text,
   'Le cours commence ___ 9 heures.'::text,
   'en'::text, 'dans'::text, 'à'::text, 'sur'::text,
   'c'::text),
  (8::integer, 4::integer, 'B1'::text,
   'Elle est née ___ 1998.'::text,
   'à'::text, 'dans'::text, 'sur'::text, 'en'::text,
   'd'::text),
  (8::integer, 5::integer, 'B1'::text,
   'Je rêve ___ voyager au Japon.'::text,
   'de'::text, 'à'::text, 'pour'::text, 'en'::text,
   'a'::text),
  (8::integer, 6::integer, 'B2'::text,
   'Il s''intéresse ___ l''histoire de l''art.'::text,
   'de'::text, 'à'::text, 'pour'::text, 'sur'::text,
   'b'::text),
  (8::integer, 7::integer, 'B2'::text,
   'Nous pensons ___ nos amis lointains.'::text,
   'de'::text, 'pour'::text, 'à'::text, 'sur'::text,
   'c'::text),
  (8::integer, 8::integer, 'C1'::text,
   'Ce livre est ___ Victor Hugo.'::text,
   'à'::text, 'par'::text, 'pour'::text, 'de'::text,
   'd'::text),
  (8::integer, 9::integer, 'C1'::text,
   'Elle a réussi ___ force de travail.'::text,
   'à'::text, 'de'::text, 'par'::text, 'en'::text,
   'a'::text),
  (8::integer, 10::integer, 'C2'::text,
   'Il dépend ___ ses parents jusqu''à la fin de ses études.'::text,
   'à'::text, 'de'::text, 'sur'::text, 'pour'::text,
   'b'::text),
  (9::integer, 1::integer, 'A1'::text,
   'Tu veux du thé ___ du café ?'::text,
   'ou'::text, 'et'::text, 'mais'::text, 'donc'::text,
   'a'::text),
  (9::integer, 2::integer, 'A1'::text,
   'Il fait froid, ___ je mets mon manteau.'::text,
   'ou'::text, 'donc'::text, 'ni'::text, 'car'::text,
   'b'::text),
  (9::integer, 3::integer, 'A2'::text,
   'Je voudrais venir ___ je suis malade.'::text,
   'et'::text, 'ou'::text, 'mais'::text, 'donc'::text,
   'c'::text),
  (9::integer, 4::integer, 'B1'::text,
   '___ il pleuve, le match aura lieu.'::text,
   'Parce qu'''::text, 'Alors qu'''::text, 'Depuis qu'''::text, 'Bien qu'''::text,
   'd'::text),
  (9::integer, 5::integer, 'B1'::text,
   'Elle est partie ___ personne ne le remarque.'::text,
   'avant que'::text, 'parce que'::text, 'depuis que'::text, 'pendant que'::text,
   'a'::text),
  (9::integer, 6::integer, 'B2'::text,
   'Je t''attendrai ___ tu auras fini.'::text,
   'pendant que'::text, 'jusqu''à ce que'::text, 'depuis que'::text, 'alors que'::text,
   'b'::text),
  (9::integer, 7::integer, 'B2'::text,
   '___ tu sois d''accord, nous signerons le contrat.'::text,
   'Parce que'::text, 'Alors que'::text, 'Pourvu que'::text, 'Depuis que'::text,
   'c'::text),
  (9::integer, 8::integer, 'C1'::text,
   'Il est venu ___ je l''avais invité.'::text,
   'pour que'::text, 'bien que'::text, 'à condition que'::text, 'parce que'::text,
   'd'::text),
  (9::integer, 9::integer, 'C1'::text,
   '___ les résultats soient encore incomplets, la tendance est claire.'::text,
   'Bien que'::text, 'Parce que'::text, 'Alors que'::text, 'Depuis que'::text,
   'a'::text),
  (9::integer, 10::integer, 'C2'::text,
   'Nous avancerons ___ chacun fasse sa part.'::text,
   'parce que'::text, 'à condition que'::text, 'depuis que'::text, 'pendant que'::text,
   'b'::text)
)
INSERT INTO public.revision_questions (
  point_id,
  ordre,
  niveau,
  question_texte,
  choix_a,
  choix_b,
  choix_c,
  choix_d,
  bonne_reponse
)
SELECT
  p.id,
  s.ordre,
  s.niveau,
  s.question_texte,
  s.choix_a,
  s.choix_b,
  s.choix_c,
  s.choix_d,
  s.bonne_reponse
FROM questions_seed s
JOIN public.revision_unites u ON u.numero = 2
JOIN public.revision_points p
  ON p.unite_id = u.id
 AND p.numero = s.point_numero
WHERE NOT EXISTS (
  SELECT 1
  FROM public.revision_questions q
  WHERE q.point_id = p.id
    AND q.ordre = s.ordre
);

NOTIFY pgrst, 'reload schema';
