/*
  # Seed : 120 questions Révision — Unité 4 Le Pronom

  12 points × 10 questions (QCM format TCF).
  point_id résolu via revision_unites.numero = 4 + revision_points.numero.
  Idempotent : n'insère pas si (point_id, ordre) existe déjà.
*/

WITH questions_seed (
  point_numero,
  ordre,
  niveau,
  question_texte,
  choix_a,
  choix_b,
  choix_c,
  choix_d,
  bonne_reponse
) AS (
  VALUES
  (1::integer, 1::integer, 'A1'::text,
   'Marie est belge. ___ habite à Bruxelles.'::text,
   'Elle'::text, 'Il'::text, 'Lui'::text, 'La'::text,
   'a'::text),
  (1::integer, 2::integer, 'A1'::text,
   'Paul et moi, ___ allons au cinéma.'::text,
   'ils'::text, 'nous'::text, 'on'::text, 'vous'::text,
   'b'::text),
  (1::integer, 3::integer, 'A2'::text,
   'Toi et Sophie, ___ partez demain ?'::text,
   'tu'::text, 'elles'::text, 'vous'::text, 'nous'::text,
   'c'::text),
  (1::integer, 4::integer, 'B1'::text,
   'Les étudiants ? ___ préparent l''examen.'::text,
   'Elles'::text, 'On'::text, 'Leur'::text, 'Ils'::text,
   'd'::text),
  (1::integer, 5::integer, 'B1'::text,
   'Mes sœurs ? ___ travaillent à l''hôpital.'::text,
   'Elles'::text, 'Ils'::text, 'Elle'::text, 'Leur'::text,
   'a'::text),
  (1::integer, 6::integer, 'B2'::text,
   'On dit souvent « ___ » pour parler de façon impersonnelle.'::text,
   'il'::text, 'on'::text, 'eux'::text, 'nous'::text,
   'b'::text),
  (1::integer, 7::integer, 'B2'::text,
   'Toi qui ___ si fort, aide-nous !'::text,
   'parle'::text, 'parlez'::text, 'parles'::text, 'parlent'::text,
   'c'::text),
  (1::integer, 8::integer, 'C1'::text,
   'Ce sont elles qui ___ décidé de partir.'::text,
   'a'::text, 'avons'::text, 'êtes'::text, 'ont'::text,
   'd'::text),
  (1::integer, 9::integer, 'C1'::text,
   'Nul autre que lui ___ capable de résoudre ce problème.'::text,
   'n''est'::text, 'ne sont'::text, 'n''êtes'::text, 'ne suis'::text,
   'a'::text),
  (1::integer, 10::integer, 'C2'::text,
   'Quiconque ___ cet avertissement le regrettera.'::text,
   'ignores'::text, 'ignore'::text, 'ignorez'::text, 'ignorent'::text,
   'b'::text),
  (2::integer, 1::integer, 'A1'::text,
   'Tu as mon stylo ? Oui, je ___ ai.'::text,
   'l'''::text, 'le'::text, 'la'::text, 'les'::text,
   'a'::text),
  (2::integer, 2::integer, 'A1'::text,
   'Tu connais Anne ? Oui, je ___ connais bien.'::text,
   'le'::text, 'la'::text, 'lui'::text, 'les'::text,
   'b'::text),
  (2::integer, 3::integer, 'A2'::text,
   'Où sont les clés ? Je ___ cherche partout.'::text,
   'leur'::text, 'la'::text, 'les'::text, 'y'::text,
   'c'::text),
  (2::integer, 4::integer, 'B1'::text,
   'Ce rapport, je ___ ai lu hier soir.'::text,
   'le'::text, 'lui'::text, 'en'::text, 'l'''::text,
   'd'::text),
  (2::integer, 5::integer, 'B1'::text,
   'Ces photos, elle ___ a prises pendant les vacances.'::text,
   'les'::text, 'leur'::text, 'la'::text, 'en'::text,
   'a'::text),
  (2::integer, 6::integer, 'B2'::text,
   'Le directeur ? Je ne ___ ai pas encore vu.'::text,
   'lui'::text, 'l'''::text, 'le'::text, 'y'::text,
   'b'::text),
  (2::integer, 7::integer, 'B2'::text,
   'La vérité, il faut ___ dire.'::text,
   'le'::text, 'lui'::text, 'la'::text, 'en'::text,
   'c'::text),
  (2::integer, 8::integer, 'C1'::text,
   'Ces conseils, je ___ ai suivis à la lettre.'::text,
   'leur'::text, 'en'::text, 'y'::text, 'les'::text,
   'd'::text),
  (2::integer, 9::integer, 'C1'::text,
   'La lettre que tu m''as envoyée, je ___ ai reçue ce matin.'::text,
   'l'''::text, 'la'::text, 'lui'::text, 'en'::text,
   'a'::text),
  (2::integer, 10::integer, 'C2'::text,
   'Ces règles, peu d''étudiants ___ respectent vraiment.'::text,
   'leur'::text, 'les'::text, 'en'::text, 'y'::text,
   'b'::text),
  (3::integer, 1::integer, 'A1'::text,
   'Je parle à Paul. Je ___ parle.'::text,
   'lui'::text, 'le'::text, 'la'::text, 'leur'::text,
   'a'::text),
  (3::integer, 2::integer, 'A1'::text,
   'Tu écris à tes parents ? Oui, je ___ écris chaque semaine.'::text,
   'les'::text, 'leur'::text, 'lui'::text, 'en'::text,
   'b'::text),
  (3::integer, 3::integer, 'A2'::text,
   'Donne ce livre à Marie. Donne-___ ce livre.'::text,
   'la'::text, 'le'::text, 'lui'::text, 'leur'::text,
   'c'::text),
  (3::integer, 4::integer, 'B1'::text,
   'Je téléphone à mes amis. Je ___ téléphone ce soir.'::text,
   'les'::text, 'lui'::text, 'y'::text, 'leur'::text,
   'd'::text),
  (3::integer, 5::integer, 'B1'::text,
   'Elle a répondu à ton message ? Oui, elle ___ a répondu.'::text,
   'lui'::text, 'le'::text, 'la'::text, 'en'::text,
   'a'::text),
  (3::integer, 6::integer, 'B2'::text,
   'Ces clients, nous ___ avons proposé une réduction.'::text,
   'les'::text, 'leur'::text, 'lui'::text, 'en'::text,
   'b'::text),
  (3::integer, 7::integer, 'B2'::text,
   'Ne ___ dis rien pour le moment.'::text,
   'le'::text, 'la'::text, 'lui'::text, 'y'::text,
   'c'::text),
  (3::integer, 8::integer, 'C1'::text,
   'Ces étudiants, le professeur ___ explique toujours clairement les consignes.'::text,
   'les'::text, 'lui'::text, 'en'::text, 'leur'::text,
   'd'::text),
  (3::integer, 9::integer, 'C1'::text,
   'Tu as parlé à la directrice ? Oui, je ___ ai parlé ce matin.'::text,
   'lui'::text, 'la'::text, 'le'::text, 'leur'::text,
   'a'::text),
  (3::integer, 10::integer, 'C2'::text,
   'Aux personnes concernées, nous ___ enverrons un courriel détaillé.'::text,
   'les'::text, 'leur'::text, 'lui'::text, 'en'::text,
   'b'::text),
  (4::integer, 1::integer, 'A1'::text,
   'Qui est là ? C''est ___ !'::text,
   'moi'::text, 'je'::text, 'me'::text, 'mon'::text,
   'a'::text),
  (4::integer, 2::integer, 'A1'::text,
   'Tu viens avec ___ ?'::text,
   'je'::text, 'moi'::text, 'me'::text, 'mon'::text,
   'b'::text),
  (4::integer, 3::integer, 'A2'::text,
   'Elle parle de ___ tout le temps.'::text,
   'il'::text, 'le'::text, 'lui'::text, 'son'::text,
   'c'::text),
  (4::integer, 4::integer, 'B1'::text,
   'Moi, je préfère le thé ; ___, elle préfère le café.'::text,
   'lui'::text, 'la'::text, 'soi'::text, 'elle'::text,
   'd'::text),
  (4::integer, 5::integer, 'B1'::text,
   'C''est pour ___ que j''ai préparé ce cadeau.'::text,
   'toi'::text, 'tu'::text, 'te'::text, 'ton'::text,
   'a'::text),
  (4::integer, 6::integer, 'B2'::text,
   '___ non plus, je ne suis pas d''accord.'::text,
   'Je'::text, 'Moi'::text, 'Me'::text, 'Mon'::text,
   'b'::text),
  (4::integer, 7::integer, 'B2'::text,
   'Entre ___ et moi, il n''y a plus de secret.'::text,
   'tu'::text, 'te'::text, 'toi'::text, 'ton'::text,
   'c'::text),
  (4::integer, 8::integer, 'C1'::text,
   'Chacun pour ___ , dit le proverbe.'::text,
   'lui'::text, 'eux'::text, 'elle'::text, 'soi'::text,
   'd'::text),
  (4::integer, 9::integer, 'C1'::text,
   'C''est à ___ de décider, pas à moi.'::text,
   'toi'::text, 'tu'::text, 'te'::text, 'ton'::text,
   'a'::text),
  (4::integer, 10::integer, 'C2'::text,
   'Quant à ___, ils n''ont rien dit pendant la réunion.'::text,
   'ils'::text, 'eux'::text, 'leur'::text, 'elles'::text,
   'b'::text),
  (5::integer, 1::integer, 'A1'::text,
   'Tu vas à Paris ? Oui, j''___ vais demain.'::text,
   'y'::text, 'en'::text, 'le'::text, 'là'::text,
   'a'::text),
  (5::integer, 2::integer, 'A1'::text,
   'Tu veux du pain ? Oui, j''___ veux bien.'::text,
   'y'::text, 'en'::text, 'le'::text, 'de'::text,
   'b'::text),
  (5::integer, 3::integer, 'A2'::text,
   'Il reste du café ? Oui, il ___ a encore.'::text,
   'en'::text, 'y'::text, 'y en'::text, 'le'::text,
   'c'::text),
  (5::integer, 4::integer, 'B1'::text,
   'Tu penses à tes vacances ? Oui, j''___ pense souvent.'::text,
   'en'::text, 'leur'::text, 'les'::text, 'y'::text,
   'd'::text),
  (5::integer, 5::integer, 'B1'::text,
   'Tu as besoin d''aide ? Oui, j''___ ai vraiment besoin.'::text,
   'en'::text, 'y'::text, 'le'::text, 'la'::text,
   'a'::text),
  (5::integer, 6::integer, 'B2'::text,
   'Cette ville, je m''___ souviens parfaitement.'::text,
   'y'::text, 'en'::text, 'la'::text, 'lui'::text,
   'b'::text),
  (5::integer, 7::integer, 'B2'::text,
   'Au concert ? Nous ___ assistons chaque année.'::text,
   'en'::text, 'le'::text, 'y'::text, 'lui'::text,
   'c'::text),
  (5::integer, 8::integer, 'C1'::text,
   'De cette affaire, il ne veut plus ___ entendre parler.'::text,
   'y'::text, 'le'::text, 'la'::text, 'en'::text,
   'd'::text),
  (5::integer, 9::integer, 'C1'::text,
   'Ces documents, prends-___ deux exemplaires.'::text,
   'en'::text, 'y'::text, 'les'::text, 'leur'::text,
   'a'::text),
  (5::integer, 10::integer, 'C2'::text,
   'Sur ce sujet délicat, mieux vaut ne pas trop ___ insister.'::text,
   'en'::text, 'y'::text, 'le'::text, 'lui'::text,
   'b'::text),
  (6::integer, 1::integer, 'A2'::text,
   'Tu donnes le livre à Marie ? Oui, je ___ donne.'::text,
   'le lui'::text, 'lui le'::text, 'la lui'::text, 'le leur'::text,
   'a'::text),
  (6::integer, 2::integer, 'A2'::text,
   'Tu montres les photos à tes parents ? Oui, je ___ montre.'::text,
   'leur les'::text, 'les leur'::text, 'les lui'::text, 'leur le'::text,
   'b'::text),
  (6::integer, 3::integer, 'B1'::text,
   'Donne-moi ce stylo. Donne-___ .'::text,
   'moi-le'::text, 'me-le'::text, 'le-moi'::text, 'le-me'::text,
   'c'::text),
  (6::integer, 4::integer, 'B1'::text,
   'Tu expliques la règle aux élèves ? Oui, je ___ explique.'::text,
   'leur la'::text, 'les leur'::text, 'leur le'::text, 'la leur'::text,
   'd'::text),
  (6::integer, 5::integer, 'B1'::text,
   'Ne me dis pas la vérité ? Si, je ___ dis.'::text,
   'te la'::text, 'la te'::text, 'toi la'::text, 'la toi'::text,
   'a'::text),
  (6::integer, 6::integer, 'B2'::text,
   'Tu m''envoies la facture ? Oui, je ___ envoie ce soir.'::text,
   'la te'::text, 'te la'::text, 'toi la'::text, 'me la'::text,
   'b'::text),
  (6::integer, 7::integer, 'B2'::text,
   'Donne-lui ces clés. Donne-___ .'::text,
   'lui-les'::text, 'les-le'::text, 'les-lui'::text, 'leur-les'::text,
   'c'::text),
  (6::integer, 8::integer, 'C1'::text,
   'Ne me les donne pas. À l''impératif négatif : Ne ___ pas.'::text,
   'les me donne'::text, 'donne-moi-les'::text, 'me donne les'::text, 'me les donne'::text,
   'd'::text),
  (6::integer, 9::integer, 'C1'::text,
   'Tu en parles à Paul ? Oui, je ___ parle.'::text,
   'lui en'::text, 'en lui'::text, 'le en'::text, 'en le'::text,
   'a'::text),
  (6::integer, 10::integer, 'C2'::text,
   'Remets-nous-en ! L''ordre correct à l''impératif est ___ .'::text,
   'Remets-en-nous'::text, 'Remets-nous-en'::text, 'Nous en remets'::text, 'En remets-nous'::text,
   'b'::text),
  (7::integer, 1::integer, 'A1'::text,
   'Voici la femme ___ parle anglais.'::text,
   'qui'::text, 'que'::text, 'dont'::text, 'où'::text,
   'a'::text),
  (7::integer, 2::integer, 'A1'::text,
   'C''est le film ___ j''adore.'::text,
   'qui'::text, 'que'::text, 'dont'::text, 'où'::text,
   'b'::text),
  (7::integer, 3::integer, 'A2'::text,
   'La ville ___ nous habitons est calme.'::text,
   'qui'::text, 'que'::text, 'où'::text, 'dont'::text,
   'c'::text),
  (7::integer, 4::integer, 'B1'::text,
   'C''est le sujet ___ tout le monde discute.'::text,
   'que'::text, 'qui'::text, 'où'::text, 'dont'::text,
   'd'::text),
  (7::integer, 5::integer, 'B1'::text,
   'L''homme ___ tu as vu est mon oncle.'::text,
   'que'::text, 'qui'::text, 'dont'::text, 'où'::text,
   'a'::text),
  (7::integer, 6::integer, 'B2'::text,
   'Voici le projet ___ dépend notre budget.'::text,
   'que'::text, 'dont'::text, 'qui'::text, 'où'::text,
   'b'::text),
  (7::integer, 7::integer, 'B2'::text,
   'Le jour ___ il est arrivé, il pleuvait.'::text,
   'que'::text, 'qui'::text, 'où'::text, 'dont'::text,
   'c'::text),
  (7::integer, 8::integer, 'C1'::text,
   'C''est une opportunité ___ il faut profiter.'::text,
   'que'::text, 'qui'::text, 'à laquelle'::text, 'dont'::text,
   'd'::text),
  (7::integer, 9::integer, 'C1'::text,
   'Voici le collègue ___ le bureau se trouve au deuxième étage.'::text,
   'dont'::text, 'que'::text, 'qui'::text, 'où'::text,
   'a'::text),
  (7::integer, 10::integer, 'C2'::text,
   'Tout ___ vous avez dit sera consigné dans le rapport.'::text,
   'ce qui'::text, 'ce que'::text, 'que'::text, 'dont'::text,
   'b'::text),
  (8::integer, 1::integer, 'A2'::text,
   'Voici la table sur ___ j''ai posé mon sac.'::text,
   'laquelle'::text, 'qui'::text, 'que'::text, 'dont'::text,
   'a'::text),
  (8::integer, 2::integer, 'B1'::text,
   'Le train dans ___ nous sommes montés était bondé.'::text,
   'qui'::text, 'lequel'::text, 'que'::text, 'dont'::text,
   'b'::text),
  (8::integer, 3::integer, 'B1'::text,
   'Les amis avec ___ je voyage sont partis tôt.'::text,
   'qui'::text, 'que'::text, 'lesquels'::text, 'dont'::text,
   'c'::text),
  (8::integer, 4::integer, 'B1'::text,
   'C''est le problème ___ il faut s''attaquer.'::text,
   'duquel'::text, 'lequel'::text, 'dont'::text, 'auquel'::text,
   'd'::text),
  (8::integer, 5::integer, 'B2'::text,
   'La société pour ___ il travaille est internationale.'::text,
   'laquelle'::text, 'qui'::text, 'dont'::text, 'où'::text,
   'a'::text),
  (8::integer, 6::integer, 'B2'::text,
   'Les dossiers à ___ tu fais référence sont classés.'::text,
   'desquels'::text, 'auxquels'::text, 'lesquels'::text, 'dont'::text,
   'b'::text),
  (8::integer, 7::integer, 'B2'::text,
   'L''immeuble devant ___ nous habitons sera rénové.'::text,
   'qui'::text, 'dont'::text, 'lequel'::text, 'où'::text,
   'c'::text),
  (8::integer, 8::integer, 'C1'::text,
   'Voici la cause ___ découle toute la discussion.'::text,
   'à laquelle'::text, 'laquelle'::text, 'dont'::text, 'de laquelle'::text,
   'd'::text),
  (8::integer, 9::integer, 'C1'::text,
   'Les critères selon ___ le jury décide sont publics.'::text,
   'lesquels'::text, 'qui'::text, 'dont'::text, 'que'::text,
   'a'::text),
  (8::integer, 10::integer, 'C2'::text,
   'C''est une question au cœur ___ se trouve un enjeu éthique.'::text,
   'à laquelle'::text, 'de laquelle'::text, 'duquel'::text, 'dont'::text,
   'b'::text),
  (9::integer, 1::integer, 'A1'::text,
   'Tu préfères ce livre ou ___ ?'::text,
   'celui-là'::text, 'celle-là'::text, 'ceux-là'::text, 'ceci'::text,
   'a'::text),
  (9::integer, 2::integer, 'A1'::text,
   'Cette robe ? Non, je préfère ___ .'::text,
   'celui-ci'::text, 'celle-ci'::text, 'ceux-ci'::text, 'ceci'::text,
   'b'::text),
  (9::integer, 3::integer, 'A2'::text,
   'Ces chaussures sont trop petites. Prends ___ .'::text,
   'ceux-là'::text, 'celle-là'::text, 'celles-là'::text, 'celui-là'::text,
   'c'::text),
  (9::integer, 4::integer, 'B1'::text,
   'Parmi ces deux plans, ___ me semble plus réaliste.'::text,
   'celle-ci'::text, 'ceux-ci'::text, 'ceci'::text, 'celui-ci'::text,
   'd'::text),
  (9::integer, 5::integer, 'B1'::text,
   '___ qui veulent s''inscrire doivent le faire avant vendredi.'::text,
   'Ceux'::text, 'Celui'::text, 'Celles'::text, 'Ce'::text,
   'a'::text),
  (9::integer, 6::integer, 'B2'::text,
   'J''ai lu ton article et ___ de ton collègue.'::text,
   'celle'::text, 'celui'::text, 'ceux'::text, 'ce'::text,
   'b'::text),
  (9::integer, 7::integer, 'B2'::text,
   '___ dont tu parles n''est plus d''actualité.'::text,
   'Celle'::text, 'Ceux'::text, 'Celui'::text, 'Ce'::text,
   'c'::text),
  (9::integer, 8::integer, 'C1'::text,
   'Les résultats de cette année dépassent ___ de l''an dernier.'::text,
   'celui'::text, 'celles'::text, 'ce'::text, 'ceux'::text,
   'd'::text),
  (9::integer, 9::integer, 'C1'::text,
   '___ à quoi je m''attendais n''est pas arrivé.'::text,
   'Ce'::text, 'Celui'::text, 'Celle'::text, 'Ceux'::text,
   'a'::text),
    (9::integer, 10::integer, 'C2'::text,
   'Les méthodes d''aujourd''hui diffèrent de ___ d''autrefois.'::text,
   'celle'::text, 'celles'::text, 'ceux'::text, 'ce'::text,
   'b'::text),
  (10::integer, 1::integer, 'A1'::text,
   'Ce stylo est à moi. C''est ___ .'::text,
   'le mien'::text, 'la mienne'::text, 'les miens'::text, 'le tien'::text,
   'a'::text),
  (10::integer, 2::integer, 'A1'::text,
   'Cette idée est à elle. C''est ___ .'::text,
   'le sien'::text, 'la sienne'::text, 'les siennes'::text, 'la mienne'::text,
   'b'::text),
  (10::integer, 3::integer, 'A2'::text,
   'Ces bagages sont à nous. Ce sont ___ .'::text,
   'le nôtre'::text, 'la nôtre'::text, 'les nôtres'::text, 'les vôtres'::text,
   'c'::text),
  (10::integer, 4::integer, 'B1'::text,
   'Ta voiture est plus rapide que ___ .'::text,
   'le mien'::text, 'les miennes'::text, 'ma'::text, 'la mienne'::text,
   'd'::text),
  (10::integer, 5::integer, 'B1'::text,
   'Vos arguments sont intéressants, mais je préfère ___ .'::text,
   'les miens'::text, 'le mien'::text, 'la mienne'::text, 'mes'::text,
   'a'::text),
  (10::integer, 6::integer, 'B2'::text,
   'Ton projet est ambitieux ; ___ l''est aussi.'::text,
   'la mienne'::text, 'le mien'::text, 'les miens'::text, 'mon'::text,
   'b'::text),
  (10::integer, 7::integer, 'B2'::text,
   'Cette responsabilité est ___ , pas la vôtre.'::text,
   'le nôtre'::text, 'les nôtres'::text, 'la nôtre'::text, 'notre'::text,
   'c'::text),
  (10::integer, 8::integer, 'C1'::text,
   'Ils ont perdu ___ dans l''incendie.'::text,
   'le leur'::text, 'la leur'::text, 'leurs'::text, 'les leurs'::text,
   'd'::text),
  (10::integer, 9::integer, 'C1'::text,
   'À chacun ___ : ne touche pas au travail d''autrui.'::text,
   'le sien'::text, 'la sienne'::text, 'les siens'::text, 'son'::text,
   'a'::text),
  (10::integer, 10::integer, 'C2'::text,
   'Les priorités des uns ne sont pas toujours ___ .'::text,
   'le leur'::text, 'les leurs'::text, 'la leur'::text, 'leurs'::text,
   'b'::text),
  (11::integer, 1::integer, 'A1'::text,
   '___ a sonné à la porte.'::text,
   'Quelqu''un'::text, 'Quelque chose'::text, 'Personne'::text, 'Chacun'::text,
   'a'::text),
  (11::integer, 2::integer, 'A1'::text,
   'Je n''ai vu ___ dans la salle.'::text,
   'quelqu''un'::text, 'personne'::text, 'rien'::text, 'aucun'::text,
   'b'::text),
  (11::integer, 3::integer, 'A2'::text,
   'Tu veux ___ à boire ?'::text,
   'quelqu''un'::text, 'rien'::text, 'quelque chose'::text, 'tout'::text,
   'c'::text),
  (11::integer, 4::integer, 'B1'::text,
   '___ des candidats n''a obtenu la note maximale.'::text,
   'Personne'::text, 'Rien'::text, 'Quelqu''un'::text, 'Aucun'::text,
   'd'::text),
  (11::integer, 5::integer, 'B1'::text,
   '___ doit respecter le règlement.'::text,
   'Chacun'::text, 'Tout'::text, 'Personne'::text, 'Rien'::text,
   'a'::text),
  (11::integer, 6::integer, 'B2'::text,
   'Il n''y a ___ à craindre.'::text,
   'personne'::text, 'rien'::text, 'aucun'::text, 'nul'::text,
   'b'::text),
  (11::integer, 7::integer, 'B2'::text,
   '___ ce qui brille n''est pas or.'::text,
   'Tous'::text, 'Chaque'::text, 'Tout'::text, 'Aucun'::text,
   'c'::text),
  (11::integer, 8::integer, 'C1'::text,
   '___ ne saurait ignorer ces faits.'::text,
   'Rien'::text, 'Aucun'::text, 'Tout'::text, 'Nul'::text,
   'd'::text),
  (11::integer, 9::integer, 'C1'::text,
   'Ils se sont disputés, puis ___ a repris son calme.'::text,
   'chacun'::text, 'tout'::text, 'quelqu''un'::text, 'personne'::text,
   'a'::text),
  (11::integer, 10::integer, 'C2'::text,
   '___ d''entre eux n''était préparé à une telle issue.'::text,
   'Tous'::text, 'Pas un'::text, 'Chacun'::text, 'Quelques-uns'::text,
   'b'::text),
  (12::integer, 1::integer, 'A1'::text,
   '___ est ton nom ?'::text,
   'Quel'::text, 'Quelle'::text, 'Quels'::text, 'Qui'::text,
   'a'::text),
  (12::integer, 2::integer, 'A1'::text,
   '___ as-tu vu au marché ?'::text,
   'Que'::text, 'Qui'::text, 'Quoi'::text, 'Quel'::text,
   'b'::text),
  (12::integer, 3::integer, 'A2'::text,
   '___ veux-tu boire ?'::text,
   'Qui'::text, 'Quel'::text, 'Que'::text, 'Lequel'::text,
   'c'::text),
  (12::integer, 4::integer, 'B1'::text,
   '___ de ces deux robes préfères-tu ?'::text,
   'Lequel'::text, 'Lesquelles'::text, 'Quel'::text, 'Laquelle'::text,
   'd'::text),
  (12::integer, 5::integer, 'B1'::text,
   'À ___ penses-tu ?'::text,
   'qui'::text, 'quoi'::text, 'que'::text, 'lequel'::text,
   'a'::text),
  (12::integer, 6::integer, 'B2'::text,
   '___ est la raison de ton absence ?'::text,
   'Quel'::text, 'Quelle'::text, 'Quels'::text, 'Qui'::text,
   'b'::text),
  (12::integer, 7::integer, 'B2'::text,
   'De ___ s''agit-il exactement ?'::text,
   'qui'::text, 'que'::text, 'quoi'::text, 'lequel'::text,
   'c'::text),
  (12::integer, 8::integer, 'C1'::text,
   '___ que soient vos arguments, la décision est prise.'::text,
   'Quel'::text, 'Quelle'::text, 'Qui'::text, 'Quels'::text,
   'd'::text),
  (12::integer, 9::integer, 'C1'::text,
   'Sur ___ vous basez-vous pour affirmer cela ?'::text,
   'quoi'::text, 'qui'::text, 'que'::text, 'lequel'::text,
   'a'::text),
  (12::integer, 10::integer, 'C2'::text,
   '___ d''entre ces hypothèses vous paraît la plus crédible ?'::text,
   'Lequel'::text, 'Laquelle'::text, 'Lesquelles'::text, 'Quelle'::text,
   'b'::text)
)
INSERT INTO public.revision_questions (
  point_id,
  ordre,
  niveau,
  question_texte,
  choix_a,
  choix_b,
  choix_c,
  choix_d,
  bonne_reponse
)
SELECT
  p.id,
  s.ordre,
  s.niveau,
  s.question_texte,
  s.choix_a,
  s.choix_b,
  s.choix_c,
  s.choix_d,
  s.bonne_reponse
FROM questions_seed s
JOIN public.revision_unites u ON u.numero = 4
JOIN public.revision_points p
  ON p.unite_id = u.id
 AND p.numero = s.point_numero
WHERE NOT EXISTS (
  SELECT 1
  FROM public.revision_questions q
  WHERE q.point_id = p.id
    AND q.ordre = s.ordre
);

NOTIFY pgrst, 'reload schema';
