/*
  # Seed : 120 questions Révision — Unité 6 Vocabulaire

  12 points × 10 questions (QCM format TCF).
  point_id résolu via revision_unites.numero = 6 + revision_points.numero.
  Idempotent : n'insère pas si (point_id, ordre) existe déjà.

  Point 11 : niveaux A2–B1 uniquement.
  Point 12 : niveaux B2–C2 uniquement.
*/

WITH questions_seed (
  point_numero,
  ordre,
  niveau,
  question_texte,
  choix_a,
  choix_b,
  choix_c,
  choix_d,
  bonne_reponse
) AS (
  VALUES
  (1::integer, 1::integer, 'A1'::text,
   'Le contraire de « possible » est ___ .'::text,
   'impossible'::text, 'dépossible'::text, 'inpossible'::text, 'malpossible'::text,
   'a'::text),
  (1::integer, 2::integer, 'A1'::text,
   'Le contraire de « content » est ___ .'::text,
   'décontent'::text, 'mécontent'::text, 'incontent'::text, 'noncontent'::text,
   'b'::text),
  (1::integer, 3::integer, 'A2'::text,
   'Un enfant qui n''est pas sage est ___ .'::text,
   'inobéissant'::text, 'malobéissant'::text, 'désobéissant'::text, 'réobéissant'::text,
   'c'::text),
  (1::integer, 4::integer, 'B1'::text,
   'Le préfixe de « reprendre » indique une action ___ .'::text,
   'négative'::text, 'avant'::text, 'contre'::text, 'faite à nouveau'::text,
   'd'::text),
  (1::integer, 5::integer, 'B1'::text,
   '« Prévoir » signifie voir ___ .'::text,
   'à l''avance'::text, 'en retard'::text, 'mal'::text, 'à nouveau'::text,
   'a'::text),
  (1::integer, 6::integer, 'B2'::text,
   'Un texte ___ n''est pas encore publié.'::text,
   'déédit'::text, 'inédit'::text, 'malédit'::text, 'réédit'::text,
   'b'::text),
  (1::integer, 7::integer, 'B2'::text,
   '« Antivol » désigne un dispositif ___ le vol.'::text,
   'avant'::text, 'sans'::text, 'contre'::text, 'après'::text,
   'c'::text),
  (1::integer, 8::integer, 'C1'::text,
   '« Coexister » signifie exister ___ .'::text,
   'après'::text, 'contre'::text, 'sans'::text, 'ensemble'::text,
   'd'::text),
  (1::integer, 9::integer, 'C1'::text,
   'Un argument ___ va à l''encontre de la thèse principale.'::text,
   'contradictoire'::text, 'prédictoire'::text, 'inddictoire'::text, 'surdictoire'::text,
   'a'::text),
  (1::integer, 10::integer, 'C2'::text,
   '« Ultramoderne » signifie ___ moderne.'::text,
   'peu'::text, 'extrêmement'::text, 'anciennement'::text, 'moyennement'::text,
   'b'::text),
  (2::integer, 1::integer, 'A1'::text,
   'Quelqu''un qui enseigne est un ___ .'::text,
   'enseignant'::text, 'enseignure'::text, 'enseignisme'::text, 'enseignette'::text,
   'a'::text),
  (2::integer, 2::integer, 'A1'::text,
   'La qualité d''être rapide s''appelle la ___ .'::text,
   'rapidement'::text, 'rapidité'::text, 'rapidation'::text, 'rapidisme'::text,
   'b'::text),
  (2::integer, 3::integer, 'A2'::text,
   'Un petit livre peut s''appeler un ___ .'::text,
   'livrage'::text, 'livrisme'::text, 'livret'::text, 'livrure'::text,
   'c'::text),
  (2::integer, 4::integer, 'B1'::text,
   'Le suffixe « -eur » dans « lecteur » désigne souvent ___ .'::text,
   'un lieu'::text, 'une action négative'::text, 'un diminutif'::text, 'une personne'::text,
   'd'::text),
  (2::integer, 5::integer, 'B1'::text,
   '« Blanchiment » est formé sur le verbe ___ .'::text,
   'blanchir'::text, 'blanc'::text, 'blancheur'::text, 'blanchâtre'::text,
   'a'::text),
  (2::integer, 6::integer, 'B2'::text,
   '« Enfantillage » a une nuance ___ .'::text,
   'diminutive neutre'::text, 'péjorative'::text, 'méliorative'::text, 'technique'::text,
   'b'::text),
  (2::integer, 7::integer, 'B2'::text,
   'Le nom formé sur « créer » avec « -tion » est ___ .'::text,
   'créage'::text, 'créure'::text, 'création'::text, 'créisme'::text,
   'c'::text),
  (2::integer, 8::integer, 'C1'::text,
   '« Savoir-faire » et « savoir-être » : le suffixe verbal n''apparaît pas, ce sont des ___ .'::text,
   'adjectifs'::text, 'préfixes'::text, 'adverbes'::text, 'noms composés'::text,
   'd'::text),
  (2::integer, 9::integer, 'C1'::text,
   '« -able » dans « lavable » indique souvent ___ .'::text,
   'la possibilité'::text, 'la négation'::text, 'le métier'::text, 'le lieu'::text,
   'a'::text),
  (2::integer, 10::integer, 'C2'::text,
   '« -âtre » dans « verdâtre » exprime souvent une qualité ___ .'::text,
   'parfaite'::text, 'approximative ou péjorative'::text, 'officielle'::text, 'collective'::text,
   'b'::text),
  (3::integer, 1::integer, 'A1'::text,
   'Le verbe de la famille de « travail » est ___ .'::text,
   'travailler'::text, 'travaillisme'::text, 'travaillure'::text, 'travaillable'::text,
   'a'::text),
  (3::integer, 2::integer, 'A1'::text,
   'L''adjectif de la famille de « bonheur » est ___ .'::text,
   'bonheureux'::text, 'heureux'::text, 'bonheurique'::text, 'bonheural'::text,
   'b'::text),
  (3::integer, 3::integer, 'A2'::text,
   'Le nom d''action de « décider » est ___ .'::text,
   'décideur'::text, 'décidage'::text, 'décision'::text, 'décide'::text,
   'c'::text),
  (3::integer, 4::integer, 'B1'::text,
   'Dans la famille de « nation », on trouve ___ .'::text,
   'nater'::text, 'natir'::text, 'nationner'::text, 'national'::text,
   'd'::text),
  (3::integer, 5::integer, 'B1'::text,
   'Le contraire adjectival dans la famille de « utilité » est ___ .'::text,
   'inutile'::text, 'désutile'::text, 'malutile'::text, 'réutile'::text,
   'a'::text),
  (3::integer, 6::integer, 'B2'::text,
   '« Illisible » appartient à la famille de ___ .'::text,
   'livre'::text, 'lire'::text, 'lit'::text, 'liste'::text,
   'b'::text),
  (3::integer, 7::integer, 'B2'::text,
   'Le nom de métier formé sur « journal » est ___ .'::text,
   'journalisme'::text, 'journalité'::text, 'journaliste'::text, 'journalage'::text,
   'c'::text),
  (3::integer, 8::integer, 'C1'::text,
   '« Préparation », « préparer », « préparatoire » : le radical commun est ___ .'::text,
   'pré-'::text, 'ation'::text, 'atoire'::text, 'prépar-'::text,
   'd'::text),
  (3::integer, 9::integer, 'C1'::text,
   'Lequel n''appartient PAS à la famille de « écrit » ?'::text,
   'écrire'::text, 'écriture'::text, 'écrivain'::text, 'écrin'::text,
   'a'::text),
  (3::integer, 10::integer, 'C2'::text,
   '« Transmettre », « transmission », « transmissible » partagent le sens d''un ___ .'::text,
   'blocage'::text, 'passage / transfert'::text, 'diminutif'::text, 'lieu'::text,
   'b'::text),
  (4::integer, 1::integer, 'A1'::text,
   'Un synonyme de « content » est ___ .'::text,
   'heureux'::text, 'triste'::text, 'fatigué'::text, 'fâché'::text,
   'a'::text),
  (4::integer, 2::integer, 'A1'::text,
   'Un synonyme de « commencer » est ___ .'::text,
   'finir'::text, 'débuter'::text, 'arrêter'::text, 'continuer'::text,
   'b'::text),
  (4::integer, 3::integer, 'A2'::text,
   '« Maison » et « demeure » : « demeure » est plus ___ .'::text,
   'familier'::text, 'technique'::text, 'soutenu'::text, 'négatif'::text,
   'c'::text),
  (4::integer, 4::integer, 'B1'::text,
   '« Regarder » et « observer » : « observer » insiste davantage sur ___ .'::text,
   'la vitesse'::text, 'le hasard'::text, 'le bruit'::text, 'l''attention'::text,
   'd'::text),
  (4::integer, 5::integer, 'B1'::text,
   'Un synonyme nuancé de « dire » dans un contexte officiel est ___ .'::text,
   'déclarer'::text, 'bavarder'::text, 'chuchoter'::text, 'crier'::text,
   'a'::text),
  (4::integer, 6::integer, 'B2'::text,
   '« Pauvre » et « démuni » : « démuni » insiste sur ___ .'::text,
   'la maladie'::text, 'le manque de ressources'::text, 'l''âge'::text, 'la taille'::text,
   'b'::text),
  (4::integer, 7::integer, 'B2'::text,
   'Entre « étonné » et « stupéfait », « stupéfait » est ___ .'::text,
   'plus faible'::text, 'identique'::text, 'plus fort'::text, 'négatif seulement'::text,
   'c'::text),
  (4::integer, 8::integer, 'C1'::text,
   '« Persuader » et « convaincre » sont proches ; « persuader » insiste davantage sur ___ .'::text,
   'la preuve pure'::text, 'la menace'::text, 'le silence'::text, 'l''adhésion affective'::text,
   'd'::text),
  (4::integer, 9::integer, 'C1'::text,
   'Un synonyme soutenu de « aider » est ___ .'::text,
   'assister'::text, 'filer un coup'::text, 'filer'::text, 'bosser'::text,
   'a'::text),
  (4::integer, 10::integer, 'C2'::text,
   '« Ambigu » et « équivoque » : les deux concernent ___ .'::text,
   'une certitude'::text, 'une pluralité d''interprétations'::text, 'une erreur orthographique'::text, 'un registre familier'::text,
   'b'::text),
  (5::integer, 1::integer, 'A1'::text,
   'Le contraire de « grand » est ___ .'::text,
   'petit'::text, 'gros'::text, 'haut'::text, 'large'::text,
   'a'::text),
  (5::integer, 2::integer, 'A1'::text,
   'Le contraire de « ouvrir » est ___ .'::text,
   'entrer'::text, 'fermer'::text, 'sortir'::text, 'poser'::text,
   'b'::text),
  (5::integer, 3::integer, 'A2'::text,
   'Le contraire de « tôt » est ___ .'::text,
   'vite'::text, 'lentement'::text, 'tard'::text, 'souvent'::text,
   'c'::text),
  (5::integer, 4::integer, 'B1'::text,
   'Le contraire de « accepter » est ___ .'::text,
   'recevoir'::text, 'proposer'::text, 'demander'::text, 'refuser'::text,
   'd'::text),
  (5::integer, 5::integer, 'B1'::text,
   'Le contraire de « rare » est ___ .'::text,
   'fréquent'::text, 'unique'::text, 'spécial'::text, 'ancien'::text,
   'a'::text),
  (5::integer, 6::integer, 'B2'::text,
   'Le contraire de « temporaire » est ___ .'::text,
   'bref'::text, 'permanent'::text, 'soudain'::text, 'récent'::text,
   'b'::text),
  (5::integer, 7::integer, 'B2'::text,
   'Le contraire de « optimiste » est ___ .'::text,
   'réaliste'::text, 'naïf'::text, 'pessimiste'::text, 'prudent'::text,
   'c'::text),
  (5::integer, 8::integer, 'C1'::text,
   'Le contraire de « abstrait » est ___ .'::text,
   'complexe'::text, 'obscur'::text, 'vague'::text, 'concret'::text,
   'd'::text),
  (5::integer, 9::integer, 'C1'::text,
   'Le contraire de « abondance » est ___ .'::text,
   'pénurie'::text, 'richesse'::text, 'excès'::text, 'surplus'::text,
   'a'::text),
  (5::integer, 10::integer, 'C2'::text,
   'Le contraire de « transparent » (au sens figuré : clair) est ___ .'::text,
   'lucide'::text, 'opaque'::text, 'évident'::text, 'net'::text,
   'b'::text),
  (6::integer, 1::integer, 'A1'::text,
   '« Mer », « mère » et « maire » : on parle d''___ .'::text,
   'homonymes'::text, 'synonymes'::text, 'antonymes'::text, 'préfixes'::text,
   'a'::text),
  (6::integer, 2::integer, 'A2'::text,
   'Le ___ de la ville a inauguré la nouvelle école.'::text,
   'mère'::text, 'maire'::text, 'mer'::text, 'mers'::text,
   'b'::text),
  (6::integer, 3::integer, 'A2'::text,
   'J''ai mal à la ___ .'::text,
   'tette'::text, 'tait'::text, 'tête'::text, 'tes'::text,
   'c'::text),
  (6::integer, 4::integer, 'B1'::text,
   '« Air », « aire » et « ère » sont des ___ .'::text,
   'synonymes'::text, 'suffixes'::text, 'antonymes'::text, 'homonymes'::text,
   'd'::text),
  (6::integer, 5::integer, 'B1'::text,
   'Ne confonds pas « éminent » et « imminent » : « imminent » signifie ___ .'::text,
   'qui va se produire bientôt'::text, 'très respecté'::text, 'ancien'::text, 'invisible'::text,
   'a'::text),
  (6::integer, 6::integer, 'B2'::text,
   '« Collision » et « collusion » sont des ___ .'::text,
   'synonymes parfaits'::text, 'paronymes'::text, 'antonymes'::text, 'préfixes'::text,
   'b'::text),
  (6::integer, 7::integer, 'B2'::text,
   'Une ___ entre deux voitures a bloqué la route.'::text,
   'collusion'::text, 'collection'::text, 'collision'::text, 'collation'::text,
   'c'::text),
  (6::integer, 8::integer, 'C1'::text,
   '« Allocation » et « allocution » : une allocution est ___ .'::text,
   'une aide financière'::text, 'un logement'::text, 'une amende'::text, 'un discours'::text,
   'd'::text),
  (6::integer, 9::integer, 'C1'::text,
   '« Effraction » et « infraction » : une infraction est ___ .'::text,
   'une violation d''une règle'::text, 'une entrée par force'::text, 'une invention'::text, 'une signature'::text,
   'a'::text),
  (6::integer, 10::integer, 'C2'::text,
   '« Conjecture » et « conjoncture » : la conjoncture désigne surtout ___ .'::text,
   'une hypothèse savante'::text, 'la situation économique du moment'::text, 'une conjonction'::text, 'un contrat'::text,
   'b'::text),
  (7::integer, 1::integer, 'A1'::text,
   'Dans « la feuille de l''arbre », « feuille » désigne ___ .'::text,
   'une partie de la plante'::text, 'une page'::text, 'un document administratif'::text, 'un journal'::text,
   'a'::text),
  (7::integer, 2::integer, 'A2'::text,
   'Dans « tourner la page », « page » a un sens ___ .'::text,
   'uniquement botanique'::text, 'figuré'::text, 'mathématique'::text, 'musical'::text,
   'b'::text),
  (7::integer, 3::integer, 'A2'::text,
   '« Une clé » peut désigner un objet pour ouvrir, ou ___ .'::text,
   'un animal'::text, 'une couleur'::text, 'une solution / une explication'::text, 'un métier'::text,
   'c'::text),
  (7::integer, 4::integer, 'B1'::text,
   'Dans « un courant d''air » et « le courant électrique », « courant » est ___ .'::text,
   'un antonyme'::text, 'un préfixe'::text, 'un suffixe'::text, 'polysémique'::text,
   'd'::text),
  (7::integer, 5::integer, 'B1'::text,
   '« Opération » peut désigner un calcul, une intervention chirurgicale, ou ___ .'::text,
   'une action militaire / commerciale'::text, 'un synonyme de « sommeil »'::text, 'un fruit'::text, 'un prénom'::text,
   'a'::text),
  (7::integer, 6::integer, 'B2'::text,
   'Dans « ce problème est épineux », « épineux » signifie ___ .'::text,
   'plein d''épines seulement'::text, 'difficile / délicat'::text, 'amusant'::text, 'transparent'::text,
   'b'::text),
  (7::integer, 7::integer, 'B2'::text,
   '« Volume » peut désigner un livre, un espace, ou ___ .'::text,
   'une émotion'::text, 'un pays'::text, 'une intensité sonore'::text, 'un métier'::text,
   'c'::text),
  (7::integer, 8::integer, 'C1'::text,
   'Dans « porter plainte » et « porter un manteau », le verbe « porter » change de ___ .'::text,
   'conjugaison obligatoire'::text, 'genre grammatical'::text, 'registre uniquement'::text, 'sens selon le complément'::text,
   'd'::text),
  (7::integer, 9::integer, 'C1'::text,
   '« Charge » peut désigner un fardeau, une accusation, ou ___ .'::text,
   'une responsabilité / une fonction'::text, 'un synonyme de « silence »'::text, 'une couleur'::text, 'un adverbe'::text,
   'a'::text),
  (7::integer, 10::integer, 'C2'::text,
   'La polysémie se distingue de l''homonymie en ce que les sens d''un mot polysémique ___ .'::text,
   'n''ont aucun lien'::text, 'sont historiquement liés'::text, 'sont toujours antonymes'::text, 'concernent seulement les verbes'::text,
   'b'::text),
  (8::integer, 1::integer, 'A1'::text,
   '« Salut ! » est plutôt un registre ___ .'::text,
   'familier'::text, 'soutenu'::text, 'administratif'::text, 'scientifique'::text,
   'a'::text),
  (8::integer, 2::integer, 'A2'::text,
   '« Bonjour, comment allez-vous ? » est un registre ___ .'::text,
   'très familier'::text, 'courant / poli'::text, 'argotique'::text, 'péjoratif'::text,
   'b'::text),
  (8::integer, 3::integer, 'A2'::text,
   '« Bouquin » est un synonyme familier de ___ .'::text,
   'stylo'::text, 'chaise'::text, 'livre'::text, 'fenêtre'::text,
   'c'::text),
  (8::integer, 4::integer, 'B1'::text,
   '« Décéder » appartient plutôt au registre ___ .'::text,
   'familier'::text, 'enfantin'::text, 'sportif'::text, 'soutenu'::text,
   'd'::text),
  (8::integer, 5::integer, 'B1'::text,
   '« Boulot » signifie ___ en langage courant/familier.'::text,
   'travail'::text, 'repas'::text, 'voyage'::text, 'argent public'::text,
   'a'::text),
  (8::integer, 6::integer, 'B2'::text,
   '« Il est fâché » (courant) → plus soutenu : ___ .'::text,
   'Il est vénère'::text, 'Il est courroucé'::text, 'Il est en rogne'::text, 'Il est chaud'::text,
   'b'::text),
  (8::integer, 7::integer, 'B2'::text,
   'Dans un mail professionnel, on évite plutôt ___ .'::text,
   '« Madame, Monsieur »'::text, '« Cordialement »'::text, '« Salut mec »'::text, '« Je vous prie d''agréer… »'::text,
   'c'::text),
  (8::integer, 8::integer, 'C1'::text,
   '« Apercevoir » est plus ___ que « voir » dans certains contextes.'::text,
   'familier'::text, 'argotique'::text, 'incorrect'::text, 'soutenu / précis'::text,
   'd'::text),
  (8::integer, 9::integer, 'C1'::text,
   '« Quérir » est un verbe de registre ___ .'::text,
   'soutenu / littéraire'::text, 'familier'::text, 'enfantin'::text, 'SMS'::text,
   'a'::text),
  (8::integer, 10::integer, 'C2'::text,
   'Passer du familier au soutenu : « Il a capoté » → ___ .'::text,
   'Il a réussi brillamment'::text, 'Il a échoué / a fait un échec'::text, 'Il a mangé'::text, 'Il a dormi'::text,
   'b'::text),
  (9::integer, 1::integer, 'A1'::text,
   'Une personne qui cherche un emploi envoie souvent un ___ .'::text,
   'CV'::text, 'menu'::text, 'roman'::text, 'permis'::text,
   'a'::text),
  (9::integer, 2::integer, 'A1'::text,
   'Le lieu où l''on travaille s''appelle le ___ .'::text,
   'cinéma'::text, 'bureau / lieu de travail'::text, 'jardin'::text, 'stade'::text,
   'b'::text),
  (9::integer, 3::integer, 'A2'::text,
   'Un ___ est une rencontre pour un éventuel emploi.'::text,
   'concert'::text, 'match'::text, 'entretien'::text, 'voyage'::text,
   'c'::text),
  (9::integer, 4::integer, 'B1'::text,
   'Le ___ fixe les droits et devoirs du salarié.'::text,
   'bulletin'::text, 'prospectus'::text, 'calendrier scolaire'::text, 'contrat'::text,
   'd'::text),
  (9::integer, 5::integer, 'B1'::text,
   'Être ___ signifie n''avoir plus d''emploi.'::text,
   'au chômage'::text, 'en congé payé seulement'::text, 'à la retraite obligatoire'::text, 'en stage réussi'::text,
   'a'::text),
  (9::integer, 6::integer, 'B2'::text,
   'La ___ est l''ensemble des compétences d''une personne.'::text,
   'cantine'::text, 'qualification'::text, 'pause'::text, 'badge'::text,
   'b'::text),
  (9::integer, 7::integer, 'B2'::text,
   'Un ___ hiérarchique est la personne au-dessus de vous.'::text,
   'collègue latéral'::text, 'client'::text, 'supérieur'::text, 'stagiaire'::text,
   'c'::text),
  (9::integer, 8::integer, 'C1'::text,
   'La ___ des tâches permet de répartir le travail.'::text,
   'démission'::text, 'sanction'::text, 'fermeture'::text, 'répartition / délégation'::text,
   'd'::text),
  (9::integer, 9::integer, 'C1'::text,
   'Un conflit au travail peut être porté devant les ___ .'::text,
   'prud''hommes'::text, 'archives'::text, 'cantines'::text, 'parkings'::text,
   'a'::text),
  (9::integer, 10::integer, 'C2'::text,
   'La ___ professionnelle désigne l''évolution de carrière à long terme.'::text,
   'pause café'::text, 'trajectoire / mobilité'::text, 'badgeuse'::text, 'tampon'::text,
   'b'::text),
  (10::integer, 1::integer, 'A1'::text,
   'Protéger la nature, c''est protéger l''___ .'::text,
   'environnement'::text, 'emploi'::text, 'examen'::text, 'immeuble'::text,
   'a'::text),
  (10::integer, 2::integer, 'A2'::text,
   'Le ___ est un gaz lié au réchauffement climatique.'::text,
   'oxygène pur'::text, 'CO2 / dioxyde de carbone'::text, 'hélium'::text, 'azote alimentaire'::text,
   'b'::text),
  (10::integer, 3::integer, 'A2'::text,
   'Recycler, c''est ___ les déchets.'::text,
   ' Ignorer'::text, 'brûler seulement'::text, 'réutiliser / transformer'::text, 'cacher'::text,
   'c'::text),
  (10::integer, 4::integer, 'B1'::text,
   'Une ___ sociale vise à aider les plus vulnérables.'::text,
   'publicité'::text, 'recette'::text, 'chanson'::text, 'politique'::text,
   'd'::text),
  (10::integer, 5::integer, 'B1'::text,
   'Les ___ annoncent les événements du jour.'::text,
   'médias / journaux'::text, 'outils'::text, 'meubles'::text, 'épices'::text,
   'a'::text),
  (10::integer, 6::integer, 'B2'::text,
   'La ___ désigne le fait de produire moins de déchets.'::text,
   'consommation maximale'::text, 'réduction / sobriété'::text, 'pollution'::text, 'spéculation'::text,
   'b'::text),
  (10::integer, 7::integer, 'B2'::text,
   'Un ___ durable cherche un équilibre économique, social et écologique.'::text,
   'déficit'::text, 'conflit'::text, 'développement'::text, 'embouteillage'::text,
   'c'::text),
  (10::integer, 8::integer, 'C1'::text,
   'La ___ énergétique consiste à moins consommer d''énergie.'::text,
   'explosion'::text, 'inflation'::text, 'censure'::text, 'transition / sobriété'::text,
   'd'::text),
  (10::integer, 9::integer, 'C1'::text,
   'Une ___ publique est un débat d''intérêt collectif.'::text,
   'question / consultation'::text, 'recette'::text, 'publicité privée'::text, 'pause'::text,
   'a'::text),
  (10::integer, 10::integer, 'C2'::text,
   'La ___ climatique désigne l''ensemble des mesures face au changement climatique.'::text,
   'décoration'::text, 'gouvernance / action'::text, 'ponctuation'::text, 'conjugaison'::text,
   'b'::text),
  (11::integer, 1::integer, 'A2'::text,
   'J''ai très ___ : je vais manger.'::text,
   'faim'::text, 'soif de travail'::text, 'sommeil de mer'::text, 'peur du pain'::text,
   'a'::text),
  (11::integer, 2::integer, 'A2'::text,
   'Il ___ des cordes aujourd''hui : prends ton parapluie.'::text,
   'neige'::text, 'pleut'::text, 'vente'::text, 'brûle'::text,
   'b'::text),
  (11::integer, 3::integer, 'A2'::text,
   'Tu peux me donner un ___ de main ?'::text,
   'pied'::text, 'bras'::text, 'coup'::text, 'doigt'::text,
   'c'::text),
  (11::integer, 4::integer, 'A2'::text,
   'Je ___ sommeil : je vais me coucher.'::text,
   'fais'::text, 'suis'::text, 'prends'::text, 'ai'::text,
   'd'::text),
  (11::integer, 5::integer, 'B1'::text,
   '___ attention à la marche !'::text,
   'Fais'::text, 'Prends'::text, 'Donne'::text, 'Mets'::text,
   'a'::text),
  (11::integer, 6::integer, 'B1'::text,
   '« Avoir soif » signifie ___ .'::text,
   'avoir faim'::text, 'désirer boire'::text, 'être fatigué'::text, 'avoir peur'::text,
   'b'::text),
  (11::integer, 7::integer, 'B1'::text,
   '« Il fait un froid de canard » signifie qu''il fait ___ .'::text,
   'très chaud'::text, 'du vent doux'::text, 'très froid'::text, 'beau'::text,
   'c'::text),
  (11::integer, 8::integer, 'B1'::text,
   'Je suis ___ l''heure : le bus part dans deux minutes.'::text,
   'en'::text, 'de'::text, 'sur'::text, 'à'::text,
   'd'::text),
  (11::integer, 9::integer, 'B1'::text,
   '« Être en retard » signifie ___ .'::text,
   'arriver après l''heure prévue'::text, 'arriver trop tôt'::text, 'ne pas venir'::text, 'être en avance'::text,
   'a'::text),
  (11::integer, 10::integer, 'B1'::text,
   'Merci pour ton ___ de pouce !'::text,
   'pied'::text, 'coup'::text, 'œil'::text, 'nez'::text,
   'b'::text),
  (12::integer, 1::integer, 'B2'::text,
   'Depuis hier, il ___ le cafard.'::text,
   'a'::text, 'fait'::text, 'prend'::text, 'donne'::text,
   'a'::text),
  (12::integer, 2::integer, 'B2'::text,
   'Elle m''a ___ un lapin : elle n''est pas venue au rendez-vous.'::text,
   'donné'::text, 'posé'::text, 'fait'::text, 'mis'::text,
   'b'::text),
  (12::integer, 3::integer, 'B2'::text,
   'Ses questions m''ont ___ la puce à l''oreille.'::text,
   'posé'::text, 'fait'::text, 'mis'::text, 'donné'::text,
   'c'::text),
  (12::integer, 4::integer, 'B2'::text,
   '« Avoir un chat dans la gorge » signifie ___ .'::text,
   'avoir faim'::text, 'être allergique'::text, 'avoir peur des chats'::text, 'avoir la voix enrouée'::text,
   'd'::text),
  (12::integer, 5::integer, 'C1'::text,
   'Il ___ la chandelle par les deux bouts.'::text,
   'brûle'::text, 'allume'::text, 'coupe'::text, 'jette'::text,
   'a'::text),
  (12::integer, 6::integer, 'C1'::text,
   'Elle est ___ dans les pommes pendant la cérémonie.'::text,
   'montée'::text, 'tombée'::text, 'entrée'::text, 'restée'::text,
   'b'::text),
  (12::integer, 7::integer, 'C1'::text,
   '« Mettre de l''eau dans son vin » signifie ___ .'::text,
   'boire trop'::text, 'changer de métier'::text, 'modérer ses exigences'::text, 'quitter la table'::text,
   'c'::text),
  (12::integer, 8::integer, 'C1'::text,
   'Ce scandale a ___ le pot aux roses.'::text,
   'cassé'::text, 'fermé'::text, 'caché'::text, 'découvert'::text,
   'd'::text),
  (12::integer, 9::integer, 'C2'::text,
   '« Couper l''herbe sous le pied » à quelqu''un, c''est ___ .'::text,
   'le devancer / le priver d''un avantage'::text, 'l''aider au jardin'::text, 'le féliciter'::text, 'l''ignorer poliment'::text,
   'a'::text),
  (12::integer, 10::integer, 'C2'::text,
   '« Péter les plombs » signifie ___ .'::text,
   'réparer une panne'::text, 's''énerver violemment'::text, 'devenir calme'::text, 'partir en vacances'::text,
   'b'::text)
)
INSERT INTO public.revision_questions (
  point_id,
  ordre,
  niveau,
  question_texte,
  choix_a,
  choix_b,
  choix_c,
  choix_d,
  bonne_reponse
)
SELECT
  p.id,
  s.ordre,
  s.niveau,
  s.question_texte,
  s.choix_a,
  s.choix_b,
  s.choix_c,
  s.choix_d,
  s.bonne_reponse
FROM questions_seed s
JOIN public.revision_unites u ON u.numero = 6
JOIN public.revision_points p
  ON p.unite_id = u.id
 AND p.numero = s.point_numero
WHERE NOT EXISTS (
  SELECT 1
  FROM public.revision_questions q
  WHERE q.point_id = p.id
    AND q.ordre = s.ordre
);

NOTIFY pgrst, 'reload schema';
