/*
  # Seed : 120 questions Révision — Unité 1 Conjugaison

  12 points × 10 questions (format TCF texte à trous).
  point_id résolu via revision_unites.numero = 1 + revision_points.numero.
  Idempotent : n'insère pas si (point_id, ordre) existe déjà.

  Niveaux par point : ~3 A1–A2, ~4 B1–B2, ~3 C1–C2.

  Note : pas de commentaires -- à l'intérieur du VALUES (sécurité au collage).
*/

WITH questions_seed (
  point_numero,
  ordre,
  niveau,
  question_texte,
  choix_a,
  choix_b,
  choix_c,
  choix_d,
  bonne_reponse
) AS (
  VALUES
  (1::integer, 1::integer, 'A1'::text,
   'Nous ___ (parler) français en classe. (1er groupe)'::text,
   'parlons'::text, 'parlez'::text, 'parlent'::text, 'parle'::text,
   'a'::text),
  (1::integer, 2::integer, 'A1'::text,
   'Tu ___ (finir) toujours tes exercices. (2e groupe)'::text,
   'finit'::text, 'finis'::text, 'finisses'::text, 'finissons'::text,
   'b'::text),
  (1::integer, 3::integer, 'A2'::text,
   'Ils ___ (vendre) leur voiture. (3e groupe)'::text,
   'vendons'::text, 'vendez'::text, 'vendent'::text, 'vend'::text,
   'c'::text),
  (1::integer, 4::integer, 'B1'::text,
   'Vous ___ (choisir) le menu du jour ? (2e groupe)'::text,
   'choisis'::text, 'choisissent'::text, 'choisiez'::text, 'choisissez'::text,
   'd'::text),
  (1::integer, 5::integer, 'B1'::text,
   'Je ___ (prendre) le petit-déjeuner à 8 heures. (3e groupe)'::text,
   'prends'::text, 'prend'::text, 'prenez'::text, 'prennent'::text,
   'a'::text),
  (1::integer, 6::integer, 'B2'::text,
   'Nous ___ (réussir) grâce à un travail régulier. (2e groupe, radical en -iss-)'::text,
   'réussions'::text, 'réussissons'::text, 'réussons'::text, 'réussissent'::text,
   'b'::text),
  (1::integer, 7::integer, 'B2'::text,
   'J''___ (offrir) un cadeau à mon ami. (verbe en -ir conjugé comme le 1er groupe)'::text,
   'offris'::text, 'offres'::text, 'offre'::text, 'offrirais'::text,
   'c'::text),
  (1::integer, 8::integer, 'C1'::text,
   'Nous ___ (haïr) l''injustice sous toutes ses formes.'::text,
   'haissons'::text, 'haïons'::text, 'hairons'::text, 'haïssons'::text,
   'd'::text),
  (1::integer, 9::integer, 'C1'::text,
   'Ils ___ (mentir) rarement, mais cette fois c''est évident. (3e groupe en -ir)'::text,
   'mentent'::text, 'mentissent'::text, 'mentons'::text, 'ment'::text,
   'a'::text),
  (1::integer, 10::integer, 'C2'::text,
   'Je ___ (cueillir) des herbes aromatiques dans le jardin.'::text,
   'cueillis'::text, 'cueille'::text, 'cueillez'::text, 'cueiller'::text,
   'b'::text),
  (2::integer, 1::integer, 'A1'::text,
   'Chaque matin, je ___ (manger) des fruits.'::text,
   'mange'::text, 'manges'::text, 'mangeons'::text, 'mangé'::text,
   'a'::text),
  (2::integer, 2::integer, 'A1'::text,
   'Tu ___ (être) très gentil avec tes amis.'::text,
   'est'::text, 'es'::text, 'suis'::text, 'êtes'::text,
   'b'::text),
  (2::integer, 3::integer, 'A2'::text,
   'Nous ___ (avoir) un examen demain.'::text,
   'avez'::text, 'ont'::text, 'avons'::text, 'avons eu'::text,
   'c'::text),
  (2::integer, 4::integer, 'B1'::text,
   'Ils ___ (venir) souvent le week-end.'::text,
   'viennent pas'::text, 'venons'::text, 'vient'::text, 'viennent'::text,
   'd'::text),
  (2::integer, 5::integer, 'B1'::text,
   'Vous ___ (prendre) le bus ou le métro ?'::text,
   'prenez'::text, 'prend'::text, 'prennent'::text, 'prenons'::text,
   'a'::text),
  (2::integer, 6::integer, 'B2'::text,
   'Elle ___ (aller) à la bibliothèque après les cours.'::text,
   'vais'::text, 'va'::text, 'allez'::text, 'vont'::text,
   'b'::text),
  (2::integer, 7::integer, 'B2'::text,
   'Je ___ (faire) mes devoirs tous les soirs.'::text,
   'fait'::text, 'faisons'::text, 'fais'::text, 'font'::text,
   'c'::text),
  (2::integer, 8::integer, 'C1'::text,
   'Ces chercheurs ___ (acquérir) une expérience précieuse sur le terrain.'::text,
   'acquèrent'::text, 'acquiert'::text, 'acquérent'::text, 'acquièrent'::text,
   'd'::text),
  (2::integer, 9::integer, 'C1'::text,
   'Tu ___ (savoir) vraiment ce que tu veux ?'::text,
   'sais'::text, 'sait'::text, 'savons'::text, 'savez'::text,
   'a'::text),
  (2::integer, 10::integer, 'C2'::text,
   'Nous ___ (résoudre) ce problème étape par étape.'::text,
   'résolons'::text, 'résolvons'::text, 'résoudons'::text, 'résolvions'::text,
   'b'::text),
  (3::integer, 1::integer, 'A1'::text,
   'Hier, j''___ (manger) une pizza.'::text,
   'ai mangé'::text, 'mangeais'::text, 'mange'::text, 'avais mangé'::text,
   'a'::text),
  (3::integer, 2::integer, 'A2'::text,
   'Quand j''étais petit, je ___ (jouer) dans le jardin.'::text,
   'ai joué'::text, 'jouais'::text, 'joue'::text, 'avais joué'::text,
   'b'::text),
  (3::integer, 3::integer, 'A2'::text,
   'Elle ___ (aller) au cinéma samedi dernier.'::text,
   'allait'::text, 'va'::text, 'est allée'::text, 'était allée'::text,
   'c'::text),
  (3::integer, 4::integer, 'B1'::text,
   'Il ___ (pleuvoir) quand nous sommes sortis.'::text,
   'a plu'::text, 'pleut'::text, 'avait plu'::text, 'pleuvait'::text,
   'd'::text),
  (3::integer, 5::integer, 'B1'::text,
   'Nous ___ (finir) le rapport avant midi.'::text,
   'avons fini'::text, 'finissions'::text, 'finissons'::text, 'avions fini'::text,
   'a'::text),
  (3::integer, 6::integer, 'B2'::text,
   'Pendant que tu ___ (dormir), le téléphone a sonné.'::text,
   'as dormi'::text, 'dormais'::text, 'dors'::text, 'avais dormi'::text,
   'b'::text),
  (3::integer, 7::integer, 'B2'::text,
   'Ils ___ (découvrir) la vérité ce jour-là.'::text,
   'découvraient'::text, 'découvrent'::text, 'ont découvert'::text, 'avaient découvert'::text,
   'c'::text),
  (3::integer, 8::integer, 'C1'::text,
   'Chaque fois qu''il ___ (venir), il apportait des fleurs.'::text,
   'est venu'::text, 'vient'::text, 'était venu'::text, 'venait'::text,
   'd'::text),
  (3::integer, 9::integer, 'C1'::text,
   'Soudain, quelqu''un ___ (crier) dans la rue.'::text,
   'a crié'::text, 'criait'::text, 'crie'::text, 'avait crié'::text,
   'a'::text),
  (3::integer, 10::integer, 'C2'::text,
   'Alors que la conférence ___ (se dérouler), une panne d''électricité a interrompu tout.'::text,
   's''est déroulée'::text, 'se déroulait'::text, 'se déroule'::text, 's''était déroulée'::text,
   'b'::text),
  (4::integer, 1::integer, 'A1'::text,
   'Demain, je ___ (aller) au marché. (futur proche)'::text,
   'vais aller'::text, 'irai'::text, 'allais'::text, 'suis allé'::text,
   'a'::text),
  (4::integer, 2::integer, 'A2'::text,
   'Attention ! Tu ___ (tomber) ! (futur proche)'::text,
   'tomberas'::text, 'vas tomber'::text, 'tombes'::text, 'es tombé'::text,
   'b'::text),
  (4::integer, 3::integer, 'A2'::text,
   'L''année prochaine, nous ___ (habiter) à Lyon. (futur simple)'::text,
   'allons habiter'::text, 'habitions'::text, 'habiterons'::text, 'avons habité'::text,
   'c'::text),
  (4::integer, 4::integer, 'B1'::text,
   'Dans dix minutes, le train ___ (partir). (futur simple)'::text,
   'va partir'::text, 'part'::text, 'est parti'::text, 'partira'::text,
   'd'::text),
  (4::integer, 5::integer, 'B1'::text,
   'Ils ___ (venir) nous voir ce soir. (futur proche)'::text,
   'vont venir'::text, 'viendront'::text, 'viennent'::text, 'sont venus'::text,
   'a'::text),
  (4::integer, 6::integer, 'B2'::text,
   'Vous ___ (recevoir) votre réponse sous 48 heures. (futur simple)'::text,
   'allez recevoir'::text, 'recevrez'::text, 'recevez'::text, 'avez reçu'::text,
   'b'::text),
  (4::integer, 7::integer, 'B2'::text,
   'Je ___ (être) disponible après 18 h. (futur simple)'::text,
   'vais être'::text, 'suis'::text, 'serai'::text, 'étais'::text,
   'c'::text),
  (4::integer, 8::integer, 'C1'::text,
   'Dès que tu ___ (arriver), appelle-moi. (futur simple après « dès que »)'::text,
   'arrives'::text, 'vas arriver'::text, 'es arrivé'::text, 'arriveras'::text,
   'd'::text),
  (4::integer, 9::integer, 'C1'::text,
   'Nous ___ (acquérir) de nouvelles compétences grâce à cette formation. (futur simple)'::text,
   'acquerrons'::text, 'acquérirons'::text, 'allons acquérir'::text, 'acquérons'::text,
   'a'::text),
  (4::integer, 10::integer, 'C2'::text,
   'Quand il ___ (savoir) la vérité, il comprendra mieux la situation. (futur simple)'::text,
   'sait'::text, 'saura'::text, 'va savoir'::text, 'a su'::text,
   'b'::text),
  (5::integer, 1::integer, 'A2'::text,
   'Quand je suis arrivé, elle ___ déjà (partir).'::text,
   'était partie'::text, 'a parti'::text, 'est partie'::text, 'avait partir'::text,
   'a'::text),
  (5::integer, 2::integer, 'A2'::text,
   'Il ___ (finir) ses études avant de trouver un emploi.'::text,
   'a fini'::text, 'avait fini'::text, 'finit'::text, 'finissait'::text,
   'b'::text),
  (5::integer, 3::integer, 'B1'::text,
   'Nous ___ (manger) quand le facteur a sonné.'::text,
   'avons mangé'::text, 'mangeâmes'::text, 'avions mangé'::text, 'mangions'::text,
   'c'::text),
  (5::integer, 4::integer, 'B1'::text,
   'Dans ce roman, le héros ___ (entrer) dans la salle et salua tout le monde. (passé simple)'::text,
   'est entré'::text, 'entrait'::text, 'était entré'::text, 'entra'::text,
   'd'::text),
  (5::integer, 5::integer, 'B1'::text,
   'Ils ___ (voir) ce film deux fois avant cette séance.'::text,
   'avaient vu'::text, 'ont vu'::text, 'virent'::text, 'voyaient'::text,
   'a'::text),
  (5::integer, 6::integer, 'B2'::text,
   'Elle ___ (prendre) sa décision bien avant la réunion.'::text,
   'a pris'::text, 'avait pris'::text, 'prit'::text, 'prenait'::text,
   'b'::text),
  (5::integer, 7::integer, 'B2'::text,
   'Le roi ___ (ordonner) que l''on ferme les portes. (passé simple)'::text,
   'a ordonné'::text, 'ordonnait'::text, 'ordonna'::text, 'avait ordonné'::text,
   'c'::text),
  (5::integer, 8::integer, 'C1'::text,
   'Il ___ (ouvrir) la lettre, lut les premières lignes, puis sourit. (passé simple)'::text,
   'a ouvert'::text, 'ouvrait'::text, 'avait ouvert'::text, 'ouvrit'::text,
   'd'::text),
  (5::integer, 9::integer, 'C1'::text,
   'Vous ___ (écrire) trois messages avant d''obtenir une réponse.'::text,
   'aviez écrit'::text, 'avez écrit'::text, 'écrivîtes'::text, 'écriviez'::text,
   'a'::text),
  (5::integer, 10::integer, 'C2'::text,
   'Ils ___ (naître) dans un petit village, puis partirent pour la capitale. (passé simple)'::text,
   'sont nés'::text, 'naquirent'::text, 'naissaient'::text, 'étaient nés'::text,
   'b'::text),
  (6::integer, 1::integer, 'A1'::text,
   '___ (écouter) bien la consigne ! (tutoiement)'::text,
   'Écoute'::text, 'Écoutes'::text, 'Écoutez'::text, 'Écoutons'::text,
   'a'::text),
  (6::integer, 2::integer, 'A1'::text,
   'S''il te plaît, ___ (venir) avec moi.'::text,
   'vient'::text, 'viens'::text, 'venez'::text, 'venir'::text,
   'b'::text),
  (6::integer, 3::integer, 'A2'::text,
   '___ (ne pas oublier) vos papiers ! (vouvoiement)'::text,
   'N''oublie pas'::text, 'Ne pas oubliez'::text, 'N''oubliez pas'::text, 'N''oublies pas'::text,
   'c'::text),
  (6::integer, 4::integer, 'B1'::text,
   '___ (aller) à la page 12, s''il vous plaît.'::text,
   'Va'::text, 'Allons'::text, 'Aller'::text, 'Allez'::text,
   'd'::text),
  (6::integer, 5::integer, 'B1'::text,
   '___ (finir) cet exercice avant de sortir. (tutoiement)'::text,
   'Finis'::text, 'Fini'::text, 'Finissez'::text, 'Finisons'::text,
   'a'::text),
  (6::integer, 6::integer, 'B2'::text,
   '___ (avoir) un peu de patience ! (vouvoiement)'::text,
   'Avez'::text, 'Ayez'::text, 'Aie'::text, 'Ayons'::text,
   'b'::text),
  (6::integer, 7::integer, 'B2'::text,
   '___ (être) prêts pour 8 heures ! (vouvoiement)'::text,
   'Êtes'::text, 'Sois'::text, 'Soyez'::text, 'Soyons'::text,
   'c'::text),
  (6::integer, 8::integer, 'C1'::text,
   '___-en un autre exemplaire, s''il te plaît. (verbe prendre)'::text,
   'Prend'::text, 'Prenez'::text, 'Prendre'::text, 'Prends'::text,
   'd'::text),
  (6::integer, 9::integer, 'C1'::text,
   'Ne ___ (se lever) pas avant la fin du discours. (vouvoiement)'::text,
   'vous levez'::text, 'te lève'::text, 'se levez'::text, 'vous lever'::text,
   'a'::text),
  (6::integer, 10::integer, 'C2'::text,
   '___ (savoir) que cette décision n''est pas définitive. (vouvoiement)'::text,
   'Savez'::text, 'Sachez'::text, 'Saches'::text, 'Sachons'::text,
   'b'::text),
  (7::integer, 1::integer, 'A2'::text,
   'Il faut que tu ___ (venir) demain.'::text,
   'viennes'::text, 'viens'::text, 'viendras'::text, 'venais'::text,
   'a'::text),
  (7::integer, 2::integer, 'A2'::text,
   'Je veux que vous ___ (être) à l''heure.'::text,
   'êtes'::text, 'soyez'::text, 'serez'::text, 'étiez'::text,
   'b'::text),
  (7::integer, 3::integer, 'B1'::text,
   'Il est important que nous ___ (finir) ce projet.'::text,
   'finissons'::text, 'finirons'::text, 'finissions'::text, 'avons fini'::text,
   'c'::text),
  (7::integer, 4::integer, 'B1'::text,
   'Bien que je ___ (avoir) peu de temps, je t''aiderai.'::text,
   'ai'::text, 'aurai'::text, 'avais'::text, 'aie'::text,
   'd'::text),
  (7::integer, 5::integer, 'B1'::text,
   'Elle souhaite que son frère ___ (partir) plus tôt.'::text,
   'parte'::text, 'part'::text, 'partira'::text, 'partait'::text,
   'a'::text),
  (7::integer, 6::integer, 'B2'::text,
   'Pourvu qu''il ___ (faire) beau ce week-end !'::text,
   'fait'::text, 'fasse'::text, 'fera'::text, 'faisait'::text,
   'b'::text),
  (7::integer, 7::integer, 'B2'::text,
   'Je doute qu''ils ___ (pouvoir) réussir sans aide.'::text,
   'peuvent'::text, 'pourront'::text, 'puissent'::text, 'pouvaient'::text,
   'c'::text),
  (7::integer, 8::integer, 'C1'::text,
   'Il est nécessaire que l''on ___ (prendre) des mesures immédiates.'::text,
   'prend'::text, 'prendra'::text, 'prenait'::text, 'prenne'::text,
   'd'::text),
  (7::integer, 9::integer, 'C1'::text,
   'Quoique vous ___ (dire), la décision est déjà prise.'::text,
   'disiez'::text, 'dites'::text, 'direz'::text, 'disiez pas'::text,
   'a'::text),
  (7::integer, 10::integer, 'C2'::text,
   'Il convient que chacun ___ (savoir) exactement son rôle.'::text,
   'sait'::text, 'sache'::text, 'saura'::text, 'savait'::text,
   'b'::text),
  (8::integer, 1::integer, 'A2'::text,
   'Si j''avais le temps, je ___ (voyager) plus.'::text,
   'voyagerais'::text, 'voyage'::text, 'voyagerai'::text, 'ai voyagé'::text,
   'a'::text),
  (8::integer, 2::integer, 'A2'::text,
   'Tu ___ (pouvoir) m''aider, s''il te plaît ? (demande polie)'::text,
   'peux'::text, 'pourrais'::text, 'pourras'::text, 'as pu'::text,
   'b'::text),
  (8::integer, 3::integer, 'B1'::text,
   'Nous ___ (aimer) visiter ce musée un jour.'::text,
   'aimons'::text, 'aimerons'::text, 'aimerions'::text, 'avons aimé'::text,
   'c'::text),
  (8::integer, 4::integer, 'B1'::text,
   'S''il avait su, il ___ (venir) plus tôt. (conditionnel passé)'::text,
   'viendrait'::text, 'est venu'::text, 'venait'::text, 'serait venu'::text,
   'd'::text),
  (8::integer, 5::integer, 'B1'::text,
   'Vous ___ (devoir) vérifier vos sources avant de publier.'::text,
   'devriez'::text, 'devez'::text, 'devrez'::text, 'avez dû'::text,
   'a'::text),
  (8::integer, 6::integer, 'B2'::text,
   'Sans ton aide, je n''___ jamais ___ (réussir). (conditionnel passé)'::text,
   'ai / réussi'::text, 'aurais / réussi'::text, 'réussirais /'::text, 'avais / réussi'::text,
   'b'::text),
  (8::integer, 7::integer, 'B2'::text,
   'Ils ___ (être) ravis de participer à l''atelier.'::text,
   'sont'::text, 'seront'::text, 'seraient'::text, 'étaient'::text,
   'c'::text),
  (8::integer, 8::integer, 'C1'::text,
   'Si elle avait écouté les conseils, elle ___ (éviter) cette erreur. (conditionnel passé)'::text,
   'éviterait'::text, 'a évité'::text, 'évitait'::text, 'aurait évité'::text,
   'd'::text),
  (8::integer, 9::integer, 'C1'::text,
   'On ___ (croire) qu''il connaissait déjà la réponse.'::text,
   'croirait'::text, 'croit'::text, 'croira'::text, 'a cru'::text,
   'a'::text),
  (8::integer, 10::integer, 'C2'::text,
   'À ta place, j''___ (faire) autrement dès le début. (conditionnel passé)'::text,
   'ferais'::text, 'aurais fait'::text, 'ai fait'::text, 'faisais'::text,
   'b'::text),
  (9::integer, 1::integer, 'A2'::text,
   'Il est sorti en ___ (chanter).'::text,
   'chantant'::text, 'chanté'::text, 'chanter'::text, 'chante'::text,
   'a'::text),
  (9::integer, 2::integer, 'A2'::text,
   '___ (lire) ce livre, j''ai beaucoup appris. (participe présent)'::text,
   'Lu'::text, 'Lisant'::text, 'Lire'::text, 'Lis'::text,
   'b'::text),
  (9::integer, 3::integer, 'B1'::text,
   'Elle prépare le dîner en ___ (écouter) la radio.'::text,
   'écouté'::text, 'écouter'::text, 'écoutant'::text, 'écoute'::text,
   'c'::text),
  (9::integer, 4::integer, 'B1'::text,
   'Les personnes ___ (vivre) ici connaissent bien le quartier. (participe présent)'::text,
   'vécu'::text, 'vivre'::text, 'vivent'::text, 'vivant'::text,
   'd'::text),
  (9::integer, 5::integer, 'B1'::text,
   'Il a réussi en ___ (travailler) régulièrement.'::text,
   'travaillant'::text, 'travaillé'::text, 'travailler'::text, 'travaille'::text,
   'a'::text),
  (9::integer, 6::integer, 'B2'::text,
   '___ (savoir) la vérité, elle a changé d''avis. (participe présent)'::text,
   'Su'::text, 'Sachant'::text, 'Savoir'::text, 'Sait'::text,
   'b'::text),
  (9::integer, 7::integer, 'B2'::text,
   'Nous progressons en ___ (pratiquer) chaque jour.'::text,
   'pratiqué'::text, 'pratiquer'::text, 'pratiquant'::text, 'pratiquons'::text,
   'c'::text),
  (9::integer, 8::integer, 'C1'::text,
   '___ (avoir) peu de moyens, ils ont tout de même organisé l''événement. (participe présent)'::text,
   'Eu'::text, 'Avoir'::text, 'Ont'::text, 'Ayant'::text,
   'd'::text),
  (9::integer, 9::integer, 'C1'::text,
   'Il s''est blessé en ___ (courir) trop vite.'::text,
   'courant'::text, 'couru'::text, 'courir'::text, 'court'::text,
   'a'::text),
  (9::integer, 10::integer, 'C2'::text,
   'Les arguments ___ (convaincre) le jury étaient particulièrement solides. (participe présent)'::text,
   'convaincu'::text, 'convainquant'::text, 'convaincre'::text, 'convainquent'::text,
   'b'::text),
  (10::integer, 1::integer, 'A2'::text,
   'Elle est ___ (allé) au marché.'::text,
   'allée'::text, 'allé'::text, 'allés'::text, 'allées'::text,
   'a'::text),
  (10::integer, 2::integer, 'A2'::text,
   'Ils sont ___ (parti) très tôt.'::text,
   'parti'::text, 'partis'::text, 'partie'::text, 'parties'::text,
   'b'::text),
  (10::integer, 3::integer, 'B1'::text,
   'La lettre que j''ai ___ (écrire) est sur le bureau.'::text,
   'écrit'::text, 'écrits'::text, 'écrite'::text, 'écrites'::text,
   'c'::text),
  (10::integer, 4::integer, 'B1'::text,
   'Les pommes que nous avons ___ (acheter) sont délicieuses.'::text,
   'acheté'::text, 'achetés'::text, 'achetée'::text, 'achetées'::text,
   'd'::text),
  (10::integer, 5::integer, 'B1'::text,
   'Elle s''est ___ (laver) les mains. (COD = les mains)'::text,
   'lavé'::text, 'lavée'::text, 'lavés'::text, 'lavées'::text,
   'a'::text),
  (10::integer, 6::integer, 'B2'::text,
   'Les décisions qu''ils ont ___ (prendre) sont contestées.'::text,
   'pris'::text, 'prises'::text, 'prise'::text, 'prisses'::text,
   'b'::text),
  (10::integer, 7::integer, 'B2'::text,
   'Elle s''est ___ (souvenir) de mon anniversaire.'::text,
   'souvenu'::text, 'souvenus'::text, 'souvenue'::text, 'souvenues'::text,
   'c'::text),
  (10::integer, 8::integer, 'C1'::text,
   'La chanson que tu as ___ (entendre) hier passait à la radio.'::text,
   'entendu'::text, 'entendus'::text, 'entendues'::text, 'entendue'::text,
   'd'::text),
  (10::integer, 9::integer, 'C1'::text,
   'Ils se sont ___ (écrire) de longues lettres. (COD = de longues lettres)'::text,
   'écrit'::text, 'écrits'::text, 'écrite'::text, 'écrites'::text,
   'a'::text),
  (10::integer, 10::integer, 'C2'::text,
   'Les efforts qu''elle s''est ___ (imposer) ont fini par payer.'::text,
   'imposé'::text, 'imposés'::text, 'imposée'::text, 'imposées'::text,
   'b'::text),
  (11::integer, 1::integer, 'A2'::text,
   'Ce livre ___ (écrire) par une auteure canadienne. (présent passif)'::text,
   'est écrit'::text, 'écrit'::text, 'a écrit'::text, 'est écrire'::text,
   'a'::text),
  (11::integer, 2::integer, 'A2'::text,
   'La porte ___ (fermer) chaque soir à 21 h. (présent passif)'::text,
   'ferme'::text, 'est fermée'::text, 'a fermé'::text, 'est fermer'::text,
   'b'::text),
  (11::integer, 3::integer, 'B1'::text,
   'Les résultats ___ (publier) hier. (passé composé passif)'::text,
   'sont publiés'::text, 'ont publié'::text, 'ont été publiés'::text, 'étaient publiés'::text,
   'c'::text),
  (11::integer, 4::integer, 'B1'::text,
   'Cette décision ___ (prendre) par le comité. (passé composé passif)'::text,
   'est prise'::text, 'a pris'::text, 'était prise'::text, 'a été prise'::text,
   'd'::text),
  (11::integer, 5::integer, 'B1'::text,
   'Les documents ___ (envoyer) demain. (futur passif)'::text,
   'seront envoyés'::text, 'sont envoyés'::text, 'enverront'::text, 'ont été envoyés'::text,
   'a'::text),
  (11::integer, 6::integer, 'B2'::text,
   'Le bâtiment ___ (construire) en 1920. (passé composé passif)'::text,
   'est construit'::text, 'a été construit'::text, 'a construit'::text, 'était construit'::text,
   'b'::text),
  (11::integer, 7::integer, 'B2'::text,
   'Ces règles ___ (respecter) par tous les participants. (présent passif)'::text,
   'respectent'::text, 'ont respecté'::text, 'sont respectées'::text, 'sont respecter'::text,
   'c'::text),
  (11::integer, 8::integer, 'C1'::text,
   'La proposition ___ (rejeter) à l''unanimité. (passé composé passif)'::text,
   'est rejetée'::text, 'a rejeté'::text, 'était rejetée'::text, 'a été rejetée'::text,
   'd'::text),
  (11::integer, 9::integer, 'C1'::text,
   'On dit que le tableau ___ (voler) pendant la nuit. (passé composé passif)'::text,
   'a été volé'::text, 'est volé'::text, 'a volé'::text, 'était volé'::text,
   'a'::text),
  (11::integer, 10::integer, 'C2'::text,
   'Si les mesures ___ (appliquer) plus tôt, la crise aurait été limitée. (plus-que-parfait passif)'::text,
   'étaient appliquées'::text, 'avaient été appliquées'::text, 'ont été appliquées'::text, 'seraient appliquées'::text,
   'b'::text),
  (12::integer, 1::integer, 'A2'::text,
   'Il a dit : « Je suis fatigué. » → Il a dit qu''il ___ fatigué.'::text,
   'était'::text, 'est'::text, 'sera'::text, 'soit'::text,
   'a'::text),
  (12::integer, 2::integer, 'A2'::text,
   'Elle a dit : « Je viendrai demain. » → Elle a dit qu''elle ___ le lendemain.'::text,
   'viendra'::text, 'viendrait'::text, 'vient'::text, 'venait'::text,
   'b'::text),
  (12::integer, 3::integer, 'B1'::text,
   'Ils ont affirmé : « Nous avons fini. » → Ils ont affirmé qu''ils ___ .'::text,
   'ont fini'::text, 'finissaient'::text, 'avaient fini'::text, 'finiraient'::text,
   'c'::text),
  (12::integer, 4::integer, 'B1'::text,
   'Tu m''as demandé : « Où habites-tu ? » → Tu m''as demandé où j''___ .'::text,
   'habite'::text, 'habiterai'::text, 'habiterais'::text, 'habitais'::text,
   'd'::text),
  (12::integer, 5::integer, 'B1'::text,
   'Il a promis : « Je t''appellerai. » → Il a promis qu''il m''___ .'::text,
   'appellerait'::text, 'appellera'::text, 'appelle'::text, 'appelait'::text,
   'a'::text),
  (12::integer, 6::integer, 'B2'::text,
   'Elle a dit : « Je faisais mes devoirs. » → Elle a dit qu''elle ___ ses devoirs.'::text,
   'a fait'::text, 'faisait'::text, 'ferait'::text, 'fasse'::text,
   'b'::text),
  (12::integer, 7::integer, 'B2'::text,
   'Le guide a expliqué : « Visitez la salle suivante. » → Le guide a expliqué qu''il ___ visiter la salle suivante.'::text,
   'faut'::text, 'faudra'::text, 'fallait'::text, 'fallût'::text,
   'c'::text),
  (12::integer, 8::integer, 'C1'::text,
   'Il a déclaré : « Je partirai dès que j''aurai terminé. » → Il a déclaré qu''il ___ dès qu''il ___ terminé.'::text,
   'partira / aura'::text, 'partait / avait'::text, 'parte / ait'::text, 'partirait / aurait'::text,
   'd'::text),
  (12::integer, 9::integer, 'C1'::text,
   'Elle a dit : « Si j''avais su, je serais venue. » → Elle a dit que si elle ___ , elle ___ .'::text,
   'avait su / serait venue'::text, 'aurait su / serait venue'::text, 'savait / venait'::text, 'a su / est venue'::text,
   'a'::text),
  (12::integer, 10::integer, 'C2'::text,
   'Ils ont soutenu : « Nous ne pouvons pas accepter cette condition. » → Ils ont soutenu qu''ils ___ pas accepter cette condition.'::text,
   'ne peuvent'::text, 'ne pouvaient'::text, 'ne pourraient'::text, 'n''avaient pu'::text,
   'b'::text)
)
INSERT INTO public.revision_questions (
  point_id,
  ordre,
  niveau,
  question_texte,
  choix_a,
  choix_b,
  choix_c,
  choix_d,
  bonne_reponse
)
SELECT
  p.id,
  s.ordre,
  s.niveau,
  s.question_texte,
  s.choix_a,
  s.choix_b,
  s.choix_c,
  s.choix_d,
  s.bonne_reponse
FROM questions_seed s
JOIN public.revision_unites u ON u.numero = 1
JOIN public.revision_points p
  ON p.unite_id = u.id
 AND p.numero = s.point_numero
WHERE NOT EXISTS (
  SELECT 1
  FROM public.revision_questions q
  WHERE q.point_id = p.id
    AND q.ordre = s.ordre
);

NOTIFY pgrst, 'reload schema';
